### ISSUE TITLE
update input file read/write functions to work with upcoming SSv3.30

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#103]
SS_readdat, SS_writedat and similar functions for starter and forecast need to be updated to work with SSv3.30.
It would be possible have either a user-specified switch within a single function or separate functions for 3.24 and 3.30.. The second option would result in cleaner code. Given that there will be an SS function to transition between 3.24 and 3.30, I don't think it's worth augmenting these functions to do the conversion. If folks have an opinion on which approach is better, feel free to comment here.

**Comment by kellijohnson** [comment]
@taylori I prefer to keep a single function and have it default to the newer version. I also agree that you do not need to write conversions.

**Comment by allanhicks** [comment]
You could have a wrapper function that figures out which version and calls
the appropriate and "clean" sub function. You then wouldn't have to recode
the current function and could write a new one for ss3.3.

I apologize for writing 'you' when it should be 'we'!

**Comment by taylori** [comment]
Thanks @kellijohnson and @allanhicks and other offline for the feedback.
I'm thinking that the following changes would 
rename SS_readdat to SS_readdat_3.24
write new SS_readdat_3.30
add a wrapper function called SS_readdat such as the draft version below. The default version could be updated in the future once 3.30 is released or we could make it smarter to look for telltale signs of which version it was reading and make it automatic.

**Example wrapper function**
SS_readdat <- function(version="3.24", ...){
  # wrapper function to call old or new version of SS_readdat

  # call function for SS version 3.24
  if(version=="3.24"){ # should work whether "version" is character or numeric
    datlist <- SS_readdat_3.24(...)
  }

  # call function for SS version 3.30
  if(version=="3.30" | version==3.3){ # turns out 3.30 != "3.30" in R
    datlist <- SS_readdat_3.30(...)
  }

  # return the result
  return(datlist)
}

**Comment by allanhicks** [comment]
Great idea Ian and good job with the pseudo-code.  What if the default was
to determine the version automatically? Not sure if it is worth it, but it
is possible. Here is an example for the data file (which requires that SS
was previously run to get data.ss_new).

SS_readdat <- function(version=NULL, file, ...){
# wrapper function to call old or new version of SS_readdat

if(is.null(version)) {
#extract just the directory from file
version <-
scan(file.path(directory,"data.ss_new"),what=character(),nlines=1)
version <- substring(version,3,6)
}

# call function for SS version 3.24
...


This could also be done for SS_output by reading in the version from the
Report.sso file.  It assumes a consistent labeling on the first line of
these files.

Allan

**Comment by taylori** [comment]
The automatic version testing makes sense but since the majority of existing uses are for 3.24 and are associated with files that aren't necessarily from data.ss_new and don't necessarily have the version number at the top, I would still keep the default at 3.24 and have that default be overruled if it sees 3.30 at the top.

SS_output already has version number processing with multiple redundant variables. Someday this could be cleaned up but if it's not broken....
```
  # warn if SS version used to create rep file is too old or too new for this code
  # note: SS_versionCode is new with V3.20
  # perhaps in the future we will use it to replace SS_versionshort throughout r4ss?
  SS_versionCode <- rephead[grep("#V",rephead)]
  SS_version <- rephead[grep("Stock_Synthesis",rephead)]
  SS_version <- SS_version[substring(SS_version,1,2)!="#C"] # remove any version numbering in the comments
  SS_versionshort <- toupper(substr(SS_version,1,8))
  SS_versionNumeric <- as.numeric(substring(SS_versionshort,5))

```

**Comment by taylori** [comment]
Wrapper function and separate versions of readdat now in place. The function SS_readdat_3.30 is currently just a copy of SS_readdat_3.24 and needs to be revised to work with the new format of 3.30. No change to read/write functions for other input files has been attempted so far.

**Comment by taylori** [comment]
Recent commits 06ae18dbcac001a2e29c6a54825df4f7b5e12d86 and 0c732c6e32e6c8c471e33944d4eccafc466f068e have made progress on SS_readdat_3.30 and read/write of starter files. Starter file format is similar enough there was no need to separate into 3.24 and 3.30 versions with wrapper.

**Comment by taylori** [comment]
The read/write functions for data, forecast, and starter have all been updated for SS version 3.30. The read/write functions for the control file have not been updated, but that's a bigger task and not necessarily a top priority, so will close this issue and open a new one specific to that task.

**Comment by taylori** [comment]
In closing this issue, I failed to note that the SS_writedat hasn't been updated to work with 3.30. Following the pattern set for the readdat functions, I'll be working on converting that to a wrapper function for new functions SS_writedat_3.24 and SS_writedat_3.30. This will be developed in the SSv3.30.10 branch and may not work for early 3.30 versions of SS.

**Comment by taylori** [comment]
As noted in discussion of issue #138, the read/write functions now work for 3.30 with the exception of SS_readctl_3.30 which hasn't been written yet. However, the original functions discussed here are working so I'm closing the issue.
