### ISSUE TITLE
improve default index comparisons in SSplotComparisons

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#105]
When any model has more than 1 index, you have to manually input a vector of index numbers by model. This made sense for the original use of this function, but the vast majority of cases have identical sets of observed indices so the defaults should be improved to plot all the comparisons and only require manual input when the number of observations or the table of fleet numbers by index differ.
-Ian

**Comment by taylori** [comment]
Prompted by question from Jemery Day, this fix is overdue, but can be worked around with a command like
```
# make plots comparing each index (need to be the same in both models)
mod.summary <- SSsummarize(list(model1, model2))
for(f in unique(model1$cpue$Fleet)){
  SSplotComparisons(mod.summary, indexfleets=c(f,f), indexUncertainty=TRUE, 
                    print=TRUE, plotdir='comparison_plots', subplot=11:12)
}
```

**Comment by iantaylor-NOAA** [comment]
Changes in `default_indices` branch allow `SSplotComparisons()` to automatically create comparison plots for all indices if the associated fleet numbers match across the models being compared. 

A bit more detail on the argument which controls which indices get plotted:
- `indexfleets = NULL` (the default) make a plot for each index
- `indexfleets = 5` compare the index fits for fleet 5 across all models
- `indexfleets = c(5, 7)` compare the index for fleet 5 in model 1 to the index for fleet 7 in model 2. Note that this option can be used to compare different indices within the same model (as long as the scale was comparable), via a command like `SSplotComparisons(SSsummarize(list(model1, model1)), subplot=13, indexfleets = c(2,3))`
- `indexfleets = list(model1 = c(1,2), model2 = c(1,3)`, (a new option) compare the index for fleet 1 across both models in one plot and the index for Model 1 Fleet 2 vs the index for Model 2 Fleet 3 in a second plot). List elements must be the same length but the names of the list elements don't matter and can be absent.

When the plots are written to PNG files, the filenames will be something like "compare13_indices_flt5.png" if the index is associated with fleet 5 for all models being compared, or "compare13_indices_index1.png" if the fleet numbering is different among models, where the number is just the relative position in the sequence of index plots. If the plots are displayed within R or written to PDF it's up to the user to keep track of which index plot is which.

I also changed the default to `indexUncertainty = TRUE` to add uncertainty intervals around the points because I think that's useful information and often is left out because the default was `FALSE`. By default only the intervals associated with the first model are shown. If extra standard error is estimated within the model, the intervals may differ among models in which case you can add the argument `indexPlotEach = TRUE` to show the intervals for each one. I think that in many cases the differences are subtle enough that it's not worth making the plot busy with extra points and lines. In the future the function could be made smarter to use `indexPlotEach = TRUE` automatically if it see differences in index values or index uncertainty.

Feel free to comment if you have any questions, comments, or concerns about these changes. I'm going to be on leave for a bit so this branch won't get merged until July 9 at the earliest.

**Comment by iantaylor-NOAA** [comment]
This was sorted out in 2020, but issue never closed.
