### ISSUE TITLE
add key to figure showing ageing error

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#106]
Andre Punt seems to have trouble intuiting that the white colors are 1.0 and red 0.0 with yellows and oranges in between in the [ageing_matrix_fun](https://github.com/r4ss/r4ss/blob/master/R/SSplotNumbers.R#L658) inside SSplotNumbers. Adding a key to the plot would help. Expanding the caption would be a simpler step in the same direction.

**Comment by taylori** [comment]
Alternative to key would be replacing image plot with something containing histograms in the style of the example created for issue #101

**Comment by taylori** [comment]
New function SSplotAgeMatrix should be adequate without a key and can replace the heat map created by image that Andre had issues with. I'll close issue after the function has been replaced.

**Comment by taylori** [comment]
New plots have been added to default set but old figures have been left in place for now. In example figures before, new plot (gray) makes it easier to evaluate the magnitude of the imprecision while in the older plot (red), the pattern is easy to discern but judging the relative magnitude of different colors is hard (and I don't think a key would help much).
![numbers10_ageerror_matrix_6](https://cloud.githubusercontent.com/assets/4992918/19174753/2813dc10-8be6-11e6-9c2f-8ac867daa0d5.png)
Distribution of observed age at true age for ageing error type 6
file: numbers10_ageerror_matrix_6.png

![numbers5_ageerror_matrix_6](https://cloud.githubusercontent.com/assets/4992918/19174759/357cee00-8be6-11e6-83aa-066f1fd19678.png)
Ageing imprecision: matrix for method 6 
(White = 1.0, Orange = 0.5, Red = 0.0)
file: numbers5_ageerror_matrix_6.png

**Comment by iantaylor-NOAA** [comment]
Older ageing error plot using colored image has been removed from the set (in the `cleanup` branch, but soon to be in `main`) as it was more difficult to interpret than the newer plots showing with histograms showing the distribution of observed age at true age and the redundant plots were just adding clutter.
