### ISSUE TITLE
add function for calculating Mohn's ρ from retrospective analyses

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#115]
The r4ss package includes the SS_doRetro command to facilitate running retrospective analyses. These are typically summarized using the SSgetoutput, SSsummarize, and SSplotComparisons functions. It could be useful to augment one of these functions or add a new one to calculate Mohn's _ρ_ or other statistics in common use to describe the magnitude of retrospective patterns.

**Comment by taylori** [comment]
Note that discussion of Mohn's _ρ_ can be found in recent papers by
Tim Miller ([http://www.sciencedirect.com/science/article/pii/S016578361630251X](http://www.sciencedirect.com/science/article/pii/S016578361630251X)) and 
Felipe Hurtado-Ferro ([http://icesjms.oxfordjournals.org/content/72/1/99.full](http://icesjms.oxfordjournals.org/content/72/1/99.full)) among other sources.

**Comment by taylori** [comment]
Lee Cronin-Fine is also using Mohn's _ρ_ for retrospective analyses and might be convinced to help add an r4ss function to calculate this statistic for retrospective analyses.

**Comment by kellijohnson** [comment]
Also, @fhurtado calculated this for his [2015 paper](https://academic.oup.com/icesjms/article/72/1/99/2804338/Looking-in-the-rear-view-mirror-bias-and), which was based on SS output. Cody S or @juanlvalero might be able to get the code because it was never put on github.

**Comment by taylori** [comment]
We may also wish to calculate the "Woods Hole rho" as noted here: https://www.nefsc.noaa.gov/GARM-Public/2.%20Models%20Meeting/for%20review/TOR4%20Retrospective%20Patt/WP%204.1_Report_of_the_Retrospective_Working_Group.pdf

**Comment by CWetzel** [comment]
Lee from UW provided me the framework of how to calculate the Monh's rho
from our retrospectives.  I would be happy to put together a function for
this, but it won't happen until early July.  If you would like to know how
I have done this, contact me directly (chantel.wetzel@noaa.gov).

**Comment by taylori** [comment]
Thanks to @CWetzel,  `[SSmohnsrho](https://github.com/r4ss/r4ss/blob/master/R/SSmohnsrho.R)` has been available since Jul 31, 2017.
Thanks to @careymcg, a new "Alaska Fisheries Science Center and Hurtado-Ferro et al. (2015) Mohn's rho" option has been recently added.
Finally, thanks to @yukio-takeuchi for pointed out a missing `}` in the recent commit, which has been fixed in commit 7dcfb67.

As part of that recent commit, I applied some formatting to the function for consistency with other r4ss functions (different indents and line breaks), incremented the r4ss version number to 1.30.2, and added @careymcg as to the list of package co-authors.

I think this issue can be closed now. If anyone has a problem with the `SSmohnsrho` function, please open a new issue.
