### ISSUE TITLE
add figure showing diagnostics for tuning sigmaR

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#120]
suggestions from Methot and Taylor (2011) could be represented graphically.
@James-Thorson has used code in the past which could be generalized for all models.

**Comment by kellijohnson** [comment]
I also have code that I used for sablefish in 2015, though I believe 
that I tuned using different methods than @James-Thorson.

**Comment by taylori** [comment]
Recent commit added $sigma_R_info table to list produced by SS_output which includes columns Var_of_devs and mean_SEsquared as well as the square-root of their sum, representing the components and results of the calculations used in 2015 Canary assessment by @James-Thorson extracted below:

![canary_sigma_r_tuning_extract](https://cloud.githubusercontent.com/assets/4992918/21407969/1e71f322-c787-11e6-97b9-82497a10aa01.PNG)

I don't have advice on the best time-period over which to tune sigmaR but will note that the simulation analysis in Methot and Taylor (2011) used the "main" period while the Canary assessment also included "early" recruit devs.

This new output could be used within some future function to iterate over sigma_R values.

**Comment by taylori** [comment]
New output should be sufficient for now. Closing issue.
