### ISSUE TITLE
F plot in SSplotComparisons doesn't work for retrospectives

### ISSUE THREAD

**Issue by gavinfay** [r4ss/r4ss#126]
In SSplotComparisons, the F derived quantities are not modified to account for different end years as other quantities are. (useful say for retrospective analyses).

Simple fix - requires addition of a couple of lines around line 553 to the effect of:

Fvalue[Fvalue$Yr >= endyr, imodel] <- NA
FvalueLower[Fvalue$Yr >= endyr, imodel] <- NA
FvalueUpper[Fvalue$Yr >= endyr, imodel] <- NA

**Comment by taylori** [comment]
Thank you @gavinfay for fixing this with recent commit: https://github.com/r4ss/r4ss/commit/7b4b0d3e8d77b82213f02b4e62cf303aaacedc3c.
