### ISSUE TITLE
Problem with fleet names in legend of catch plots for SS 3.30

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#133]
Fishing fleets and surveys (with no catch) can be in any order in SS 3.30 but SSplotCatch assumes fleets with catch all occur prior to surveys in ordering. Fix is on the way, just logging here to track progress.

**Comment by taylori** [comment]
Thanks to Melissa Haltuch for reporting this issue.  Recent commits 9a7418209ff1cc3c312c1b1a9cc3e816d54b415b and c2170d2f4bd930a2e14fe94d8bb60f31e0ea78c7 should fix, but will leave issue open pending further testing.

**Comment by taylori** [comment]
No further complains have arisen so closing this issue. Can always re-open if needed.

**Comment by taylori** [comment]
Reopening because function needs work to be robust to fleets with catch not grouped in first set of fleets. Will be easy to fix if it's switched to relying on catches in the $catch table (wasn't available when this function was first written) rather than catches in the $timeseries.

**Comment by CWetzel** [comment]
I will volunteer to test this when corrected.  I have a sensitivity which has a fishing fleet added after surveys.  Currently, the catch is being plotted by r4ss for all fishing fleets (including the one after the surveys) but the labeling is grabbing the wrong element for the final out of order fleet (e.g. recognized 4 fishing fleets, labels them according to fleet/survey 1:4, although the fishery fleets are 1:3 and the 9th fleets.

**Comment by taylori** [comment]
Thank you. Turns out that my earlier "will be easy" claim was overly optimistic. I have an unfinished fix that I will revisit as soon as possible.

**Comment by taylori** [comment]
A revised `SSplotCatch` function with a fix to the legend of for models with catch fleets not grouped in the first set of fleets has been committed to a branch `SSplotCatch_revision` in commit 7f18ecb3ef133054bd2cdaf74166e0ea37ab40c1. Using a branch will allow testing without messing up the trunk for folks working over the weekend in case this Friday afternoon commit has any issues.

To test the change, you can load the branch using 
`devtools::install_github('r4ss/r4ss', ref='SSplotCatch_revision')`

Thanks @CWetzel for agreeing to test this. No rush to do so.

**Comment by CWetzel** [comment]
This correction seems to be working for models with fishery fleets grouped
first and with models that do not group the fishery fleets.  May want to
test on additional models prior to merging branch.

**Comment by taylori** [comment]
Seems to be working OK, so merging branch and closing issue.
