### ISSUE TITLE
inconsistent variable names throughout r4ss

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#141]
In issue #138, @kellijohnson pointed out inconsistent variable names (Nsurv vs Nsurveys). In that case, Nsurveys is definitely more common (although this input has gone away in SS version 3.30 as surveys have become regular fleets that just don't have catch).

Unfortunately, throughout the package there are many more inconsistencies (though hopefully not within any particular function). For instance, "N_areas", "Nareas", and "nareas" all occur. I think that notation with the capital N and no space is more common, so for these variables that represent model dimensions, I would suggest doing a big find/replace to make it "Nareas", "Nfleets", and "Nsurveys". I would also change "Nfleet" to "Nfleets".

However, I don't think it's worth trying to go too crazy. In issue #77, I suggested that the package should try to follow Hadley Wickham's Style Guide: http://adv-r.had.co.nz/Style.html which says:

> Variable and function names should be lowercase. Use an underscore (_) to separate words within a name. Generally, variable names should be nouns and function names should be verbs. Strive for names that are concise and meaningful (this is not easy!).
> 
> # Good
> day_one
> day_1
> 
> # Bad
> first_day_of_the_month
> DayOne
> dayone
> djm1

I still agree with that idea and the r4ss package has tons of variable names of the "bad" variety, but I think that a large-scale clean up would be hard work and would likely break things so it would be better to just try to improve things incrementally as part of the normal process of editing functions for other, more important, reasons. 

I'm open to ideas on all this, however.

**Comment by yukio-takeuchi** [comment]
I also suggest to consider consistency to what is used in control.ss_new and data_ss_new to understand the the meaning of variable easily.

For example at the top of data.ss_bew following terminologies are used in one example run

#_observed data: 
1971 #_styr
2001 #_endyr
1 #_nseas
 12 #_months/season
1 #_spawn_seas
1 #_Nfleet
2 #_Nsurveys
1 #_N_areas

When I developed SS_readctl_3.24 in particular.
I mainly  relied on those shown in control.ss_new and data.ss_new.

It might be better to collaborate the development team of SS for that purpose.

**Comment by iagomosqueira** [comment]
I agree with taking it easy, but it would be good having it done at some 
point. For example, year and Yr are used as column names in different 
data.frames from SS_output (cpue and ageselex).

**Comment by cgrandin** [comment]
I've changed over to using no capitals ever and dots to separate words. This is mostly because I get tired of pressing the shift key thousands of times. e.g.:

make.sample.table
run.model

**Comment by taylori** [comment]
Good points. Cleaning up some of the inconsistencies in Report file headers and the like is already on the SS issues list. I'll try to see if progress can be made on that front which would indeed make it easier to clean up r4ss since often the headers are taken directly from Report.sso.

**Comment by taylori** [comment]
The following changes to align names in the SS output files have just been made in development code:
```
Previously                                              Now

Year = Yr                                               Yr
Gender = Sex                                            Sex
F_report_basis = F_std_basis = F_std_method             F_report_basis
SPR_ratio_basis = SPR_report_basis = SPR_std_method     SPR_report_basis
SSB = SPB                                               SSB
Spbio = spawn_bio = SpawnBio                            SpawnBio
BirthSeas = Birthseas = Bseas                           BirthSeas
Pr_ = PR_ = Prior_                                      Pr_
r.m.s.e. = rmse = RMSE                                  RMSE
Supr_Per = SuprPer                                      SuprPer
Y/R = YPR                                               YPR
```

Now the task will begin to get r4ss working with the new terms. 

I'm thinking of making those changes in a branch with the intent that once it's merged, the r4ss package will be compatible with both SS 3.24 and future 3.30 versions, but not worry about compatibility with the beta versions of 3.30 prior to this alignment of terminology. That is, once 3.30 is properly released soon, beta testers will have to switch over to the new stuff if they want to use r4ss.

**Comment by taylori** [comment]
Changes to adapt to new terms begun in branch [output_changes_in_SS_3.30.01.15](https://github.com/r4ss/r4ss/tree/output_changes_in_SS_3.30.01.15), which can be installed using the command:
`devtools::install_github('r4ss/r4ss', ref='output_changes_in_SS_3.30.01.15')`
SS_output is now working again for a simple 3.30 model but produces a few warnings when applied to a 3.24 model. 

SS_plots does not yet work because associated changes in plotting functions remain to be completed.

I'm attempting to rename column headers as read from older SS versions to match new conventions so that dependent functions can be cleaner by just using new terms (see commit abef5e26fb568a9e2533dc2b68d5883491d92861).

Apologies to anyone whose code breaks as a result of the change in terms.

**Comment by taylori** [comment]
Terminology in various places has been cleaned up to match more consistent output starting with 3.30.01.15 and beyond while maintaining compatibility to 3.24 (and perhaps earlier). The r4ss code is now simpler in many cases where column names are sorted out in SS_output so that the dependent functions don't need to have version-specific commands. There are still many inconsistent variable names in r4ss but I will close this issue for now.

**Comment by iagomosqueira** [comment]
What is the current status on master of these changes? Using commit 51343cd I still find differences in between natage, wtatage and endgrowth, for example Gnder vs. Sex, and Yr vs. Year.

**Comment by taylori** [comment]
Here's what I've done so far:
- make sure SS_output works with 3.24 and 3.30 models
- try to make all functions work with the new variable names associated with SS 3.30
- rename variables read from 3.24 models to match the new conventions using df.rename in SS_output: https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L131

However, there are still many inconsistencies:
- wtatage.sso didn't get the updated variable names in the revised 3.30 output
- any table from 3.24 that has the old names but isn't used by an r4ss plotting function hasn't yet been renamed to match 3.30 because it didn't cause an error (or the errors haven't yet been found).

**Comment by iagomosqueira** [comment]
Wanted to check if these changes have been merged to master, or if the naming convention of watatage.sso is kept in SS_output or brought to line with all other list elements

**Comment by taylori** [comment]
Thanks for asking. The changes described in https://github.com/r4ss/r4ss/issues/141#issuecomment-308796698 are part of master, but wtatage.sso headings haven't been changed in either SS or r4ss. I will work on that.

**Comment by iagomosqueira** [comment]
Not sure if it was in your list, but I just noticed a disagreement in `SS_output(...)$natage`: BirthSeason instead of BirthSeas
