### ISSUE TITLE
Pearson Plot: Year labeling when one year of age data for both sexes

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#148]
The pearson residual plot incorrectly labels the residuals for males and females as different years when only one year of age data are available.  I am running SS 3.30.01.12.

**Comment by taylori** [comment]
Should be sorted out with commit 3445778. A seasonal model with only one observation for a given fleet will show no indication of season value associated with that observation (as opposed to multiple observations which would be shown in their appropriate position among the year labels on the axis), but presumably that could be sorted out in the caption.

Thanks for reporting this @CWetzel. Let me know if the issue isn't resolved, or feel free to close the issue if it is.

**Comment by CWetzel** [comment]
Thank you!
