### ISSUE TITLE
Adding proportion legend placement to SSplotComparisons() and other functions that use legendfun()

### ISSUE THREAD

**Issue by John-R-Wallace** [r4ss/r4ss#154]
The following additional code will allow the user to give the desired exact placement of a legend in a SSplotComparisons() subplot on a proportion basis where 0 is the lower limit of an axis and 1 is the upper limit. 

Example:

SSplotComparisons(..., legendloc = c(0.7, 0.98), ...) 
places the upper left corner of the legend 70% from the bottom of x-axis and 98% from the bottom on the y-axis. 

This is especially handy for subplot 1 where the y-axis limits in millions of eggs may be hidden from the user.

I am unsure of the use of the 'cumulative' flag so some editing may be needed to legendfun()

....
legendfun <- function(legendlabels, cumulative = FALSE) {
        if (cumulative) {
            legendloc = "topleft"
        }
        if(is.numeric(legendloc)) {
            Usr <- par()$usr
            legendloc <- list(x = Usr[1] + legendloc[1] * (Usr[2] - Usr[1]), y = Usr[3] + legendloc[2] * (Usr[4] - Usr[3]))

...

**Comment by taylori** [comment]
Good idea, @John-R-Wallace . I implemented your code in commit 8394981 and updated the help in commit 155540e to read 
```
legendloc 
Location of legend. Either a string like "topleft" or a vector
of two numeric values representing the fraction of the maximum in the x and y
dimensions, respectively. See ?legend for more info on the string options.
```
