### ISSUE TITLE
test less common functions with 3.30 models

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#155]
SS_output and SS_plots (and all the associated plotting functions) have been fairly well tested for 3.30 models, but many less commonly used r4ss functions have not. This has the potential to create angst close to assessment deadlines when stuff no longer works as expected. 

The untested functions include functions related to likelihood profiles (SS_profile, SSplotProfile, and PinerPlot),  functions for jittering and populating forecast files (SS_RunJitter, SS_ForeCatch), and various other things that aren't coming to mind at the moment. I probably could have completed some of that testing in the time it took to post this issue, but fixing anything that isn't working will take a bit longer.

**Comment by CWetzel** [comment]
The SSplotProfile and PinerPlot functions on are working for SS version
3.30.01.12.

**Comment by taylori** [comment]
There are surely some functions that need updating, but enough testing has happened that I'm closing this issue. In some cases, the executable needs to be specified to be "ss" for 3.30 where the default is "ss3", as in `SS_RunJitter(..., model="ss")`.
