### ISSUE TITLE
Ghost fleets for ages not plotting with SS_plots() 

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#156]
The ghost fleets for age composition data are not plotting.  However, the ghost fleet fits to length composition data are working with SS_plots().

**Comment by taylori** [comment]
I think that this is due to SS mistakenly reporting these observations as associated with super periods, which is fixed in 3.30.02.00. Assuming you're not using super periods, you could see the plots by finding and replacing "Sup" with "No" in CompReport.sso.

**Comment by CWetzel** [comment]
This has been fixed in the 3.30.03.02 version of SS.
