### ISSUE TITLE
Error where covar.sso not written

### ISSUE THREAD

**Issue by colemonnahan** [r4ss/r4ss#162]
I have a simple ss3sim model that runs totally fine: gets good gradient, no issues inverting hessian, writes .cor file and everything makes sense. But SS doesn't write the covar file and r4ss throws this error:

````
Error in SS_output(m, model = m, verbose = TRUE, covar = T) : 
  problem with covar file: file contains the warning
'Variances are 0.0 for first two elements, so do not write '
Change input to covar=FALSE, or modify 'covarfile' input.
````

Does anyone know why this could be happening? I tried tracking it down in the .tpl but quickly ran into functions that I didn't understand. I"m happy to provide input files if needed. I need the covar file to get out some SEs of derived quantities. Any advice is gladly welcome!

Thanks,
Cole

**Comment by taylori** [comment]
I think that the conditions causing SS to not write the covar file should also have the .cor file show 0 in the std.dev column for the first 2 parameters. Feel free to email me input files and note which SS version you're using.

**Comment by colemonnahan** [comment]
@taylori thanks for the quick response. I tried rerunning from the .par file and now it works. (???) I must have been doing something dumb. -Cole
