### ISSUE TITLE
Use fleetnames all plots created by SS_plots()

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#166]
Currently, the mean length plot for francis weighting is not using the input fleetname variables.  Update to have these plots use the same user specified naming convention.

**Comment by taylori** [comment]
Optional "fleetnames" input to SS_plots (which replace those used by SS and can have spaces in the names) is now passed to the Francis weighting functions in commit c76f2a0. If there are other functions that needs modification to use this input, please post here.

**Comment by CWetzel** [comment]
Looks good.
