### ISSUE TITLE
SSexecutivesummary additions for MS Word tables

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [r4ss/r4ss#175]
To make Chantel's handy SSexecutivesummary() function work better with MS Word tables, I modified the table output with tabs, so that they paste easily into Word.  I also added subset of columns as separate tables for easy pasting into the second and third columns of a decision table.

I personally hope to move away from MS Word for 2019, but if others can benefit from this I can either add these tables as an option to SSexecutivesummary(), now that I have more time, and do an official pull request or give the code to Chantel and she can decide what she wants to do.

**Comment by CWetzel** [comment]
I think it would be nice to have options for the user on how they want the files created.  Currently, I have created the code such that the user gets a separate csv file for each table with two goals in mind.  First, if the code fails on your model for some reason, the code creates all the tables up until the point where it encounters an error (avoiding the all or nothing trap).  And secondly, with the end goal that people may want to use the code to create files that can easily be read into other interfaces (e.g. R, R-markdown) to create documents, a single csv option the method of choice for this approach.

I would propose adding an input to the function where the user can specify how they want their tables created and formatted.  

John- please send me your modified code and I will integrate it into the function.

**Comment by John-R-Wallace** [comment]
Sent to your NOAA email.

**Comment by iantaylor-NOAA** [comment]
No longer focused on support for MS Word
