### ISSUE TITLE
age selex in readctl_3.24

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#178]
When reading a ctl file with some age selex, lines 665 and 666 of readctl_3.24.R should I think change to

```
 paste0("AgeeSpline_Knot_",1:ctllist$age_selex_types[j,4],"_",fleetnames[j],"_",j),
 paste0("AgeeSpline_Val_",1:ctllist$age_selex_types[j,4],"_",fleetnames[j],"_",j))
```

instead of using `size_selex_types` to get the right number of parameters when building the labels.

Also, in line 146, when reading blocks, we have

```
k0<-sum(ctllist$age_selex_parms[,13]>0)+sum(ctllist$size_selex_parms[,13]>0)
```

but this not tell us, as far as I can see, how many rows to expect. In the case I am working with at the moment there are 9 blocks that change 2 parameters each, so k0 should be 18. I could not find a way yet to get the right number of rows from the information available in ctllist. Maybe this will need some extra argument supplied by the user.

@yukio-takeuchi

**Comment by taylori** [comment]
Without testing anything, I agree the change from `size` to `age` in line 665-666 looks right. You should be able to get the number of expected parameters controling time-varying selectivity by combining the the block number from the 13th parameter column (which goes into that k0 calculation) as well as either ctllist$blocks_per_pattern or ctllist$Block_Design.

**Comment by iagomosqueira** [comment]
Thanks. I have drafted something to get k0 right, but please check that it will work on other settings, where the number of params changed per block are different, I can put together a pull request if you prefer it

```
# FIND relevant blocks
blks <- ctllist$blocks_per_pattern

# SUBSET params for Block > 0
pbks <- subset(ctlistl$age_selex_parms, Block > 0)

# MULTIPLY number of blocks by number of params per block
rbks <- blks[blks > 1] * pbks[!duplicated(pbks$Block), "Block_Fxn"]

# No. of rows
k0 <- sum(rbks)
```

**Comment by iagomosqueira** [comment]
Forgot to say that when I pass k0 the right number it all seems to work and load fine. Will check `SS_writectl` later.

**Comment by taylori** [comment]
A pull request would be great. As noted during discussion of workflow in issue #77, I think that's the ideal method to implement changes. I've also just added you as member so you can commit directly if that's easier.

**Comment by iagomosqueira** [comment]
Submitted at https://github.com/r4ss/r4ss/pull/179

**Comment by taylori** [comment]
Looks good. Thank you @iagomosqueira.

**Comment by iagomosqueira** [comment]
Working now on a ctl file where blocks are defined in size_selex instead. The calculation of k0 is fine, but I had wrongly hardcoded in https://github.com/r4ss/r4ss/blob/master/R/SS_readctl_3.24.R#L708 to get blocks from age_selex. I now need to do instead

```
pbks <- subset(ctllist$size_selex_pars, Block > 0)
```

but this should work across both options.

But first, can the file specify blocks for age_selex and size_selex at the same time? If not, we would need to check where to look for them. Or can I safely rbind both data.frames?

```
pbksa <- subset(ctllist$age_selex_parms, Block > 0)
pbkss <- subset(ctllist$size_selex_parms, Block > 0)
pbks <- rbind(pbksa, pbkss)
```

**Comment by taylori** [comment]
It's not common to have both age and length selectivity processes in place, and even less common to have blocks in both dimensions, but it's definitely possible to set it up this way. 

I believe that block parameters for length selectivity would come after the age selectivity parameters but before any block parameters for age selectivity.

**Comment by iagomosqueira** [comment]
I only have with me examples of either length or age-based selectivities. On those two the fix above appears to work. I will test further and submit a pull request.

**Comment by taylori** [comment]
Thanks for getting this done @iagomosqueira.
If you want an example of a more complex model to test with in the future, let me know. However, given that there's likely to be migration to 3.30 over time, it's probably not worth trying to get SS_readctl_3.24 to do everything.

**Comment by iagomosqueira** [comment]
Sure, this makes it work for what I need. I'll check when I start getting some 3.30 models.
