### ISSUE TITLE
inconsistent application of lognormal assumption for recruitment uncertainty

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#181]
Uncertainty intervals calculated by r4ss are based on a normal assumption (which matches the underlying ADMB calculation) with the exception of the derived quantities for recruitment. Years ago, the SSplotTimeseries function was set to assume lognormal with a note "[assume recruitments have log-normal distribution from first principals (multiplicative survival probabilities)](https://github.com/r4ss/r4ss/blob/master/R/SSplotTimeseries.R#L343)". The fact that recdevs are assumed to be normal and recruitment is based on the exponential of these devs further supports that assumption. Unfortunately, the intervals for recruitment calculated by the SSsummarize function which feeds into the plots produced by SSplotComparisons are based on a normal assumption. The figure below shows the SSplotTimeseries intervals in blue compared to the SSsummarize/SSplotComparisons intervals in red for the same model:
![image](https://user-images.githubusercontent.com/4992918/27496078-5e02a7da-5809-11e7-8a76-ea7f1bfcccfb.png)

I think it would be better to use the lognormal assumption in both cases, which would be an easy change to make, but am posting here to give warning or opportunity for feedback rather than making that decision unilaterally.

Note: for models that use MCMC, the SSplotTimeseries doesn't show the MCMC results (as noted in Issue #11 ) and the SSsummarize function calculates intervals on quantiles of the posterior.

**Comment by taylori** [comment]
This issue raised by Trevor Branch at the hake SRG meeting. Will go ahead with plan to change recruitment plot created by SSplotComparisons to represent a lognormal assumption.

**Comment by iantaylor-NOAA** [comment]
This issue has finally been resolved in commit 460bd07, which switches from normal to lognormal assumption in `SSsummarize()` and also switches the calculation in `SSplotTimeseries` from 1.96 standard deviations to using the `qlnorm()` function. Plotting recruitment from the same model using the two functions now results in identical intervals.
