### ISSUE TITLE
SS_plots and latest version of SS (3.30.06.02) failing

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#188]
The SS_plots function errors during the biology plots for my model with the latest SS version.  The error to the screen is:

Finished defining objects
Plots will be written to PNG files in the directory:
   E:/POP_2017/SS/model_2017 - Copy/plots 
Starting biology plots (group 1)
Error in png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  : 
  unable to start png() device
In addition: Warning messages:
1: In SS_plots(base) :
  covar information unavailable, changing 'uncertainty' to FALSE
2: In png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  :
  unable to open file 'E:/POP_2017/SS/model_2017 - Copy/plots/bio14_time-varying_Change?.png' for writing
3: In png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  :
  opening device failed

**Comment by taylori** [comment]
Thanks @CWetzel for reporting this. A small change in commit 112c164 fixes the issue. It was caused by new "Change?" column in the MGparm_By_Year_after_adjustments being mistaken for a parameter that was changing, rather than a flag to indicate if any parameters were changing.
