### ISSUE TITLE
Switch to allow prior likelihood to be turned off in the SS_profile function

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#192]
Currently, the SS_profile function requires that the prior likelihood contribution be turned on within the starter file.  There are situations where we need to profile without this included in the profile.  This should be changed to be either a switch or not checked by the SS_profile function.

**Comment by taylori** [comment]
Good point @CWetzel. Please try the new input `prior_check=FALSE` and see if that does the trick.

The intent of the check was for profiles over steepness or natural mortality where priors are used but often the values are fixed. Excluding the prior likelihood contribution when the parameters are not estimated gets in the way of seeing the impact of the prior on the profile. However, I'm sure you're right that there are cases where you want to exclude it.

**Comment by iantaylor-NOAA** [comment]
The prior_check option seems to be working adequately (or nobody has used in since 2017).
