### ISSUE TITLE
add Jason's sensitivity plot to package

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#200]
Add code from @shcaba to r4ss (perhaps called by the SSplotComparisons function) in order to make figures like this one (from the Gertseva and Cope 2017 Yelloweye Rockfish assessment, http://www.pcouncil.org/wp-content/uploads/2017/08/E8_Att5_Yelloweye_FullDoc_E-Only_SEPT2017BB.pdf) available to users
![image](https://user-images.githubusercontent.com/4992918/33506640-a6f69ab2-d6a5-11e7-8993-a1d2aed82d6e.png)

**Comment by taylori** [comment]
As discussed today, next steps for this addition are for @shcaba to modify the plotting function to work with the output created by the `SSsummarize` function, which returns elements $likelihoods, $pars, $SpawnBio, $Bratio, $quants which should be able to provide all the information required for the plot. Then @taylori can integrate the plotting code into the r4ss package.

**Comment by taylori** [comment]
Note that a working version of this is available at https://github.com/shcaba/Stock-Assessment-Sensitivity-Plots but still needs to be incorporated into r4ss.

**Comment by iantaylor-NOAA** [comment]
The relative sensitivity plot from Jason Cope (@shcaba) as described in an in-press paper by Cope and Gertseva has been copied from https://github.com/shcaba/Stock-Assessment-Sensitivity-Plots and added to r4ss in a branch `sensitivity_plot_issue_200`. An example is below.

The branch can be installed via 
```
remotes::install_github('r4ss/r4ss@sensitivity_plot_issue_200')
```

The plot depends on packages `ggplots2`, `flextable`, `reshape2`, and `ggpubr` which in turn depend on about 30 other packages. For now, the dependencies have been listed under "suggests" in the r4ss `DESCRIPTION` file but won't get installed automatically. Running the plot without those packages installed will result in message like `Error in loadNamespace(name) : there is no package called ‘flextable’`. In the future, an informative message could be added when first calling the function if those packages aren't installed rather than waiting until the first call to `flextable::as_grouped_data()` which produces the error.

The next steps include doing some testing and improving the documentation by 
- [ ] adding an example function call to the documentation at the top of the function https://github.com/r4ss/r4ss/blob/sensitivity_plot_issue_200/R/SS_Sensi_plot.R and 
- [ ] checking the existing documentation available via `?SS_Sensi_plot` when the branch has been installed.

![Sensi_logREplot_all](https://user-images.githubusercontent.com/4992918/85638930-18e25300-b63c-11ea-8fcb-e986a4c08d65.png)

**Comment by iantaylor-NOAA** [comment]
Here's an easier-to-understand example plot where I need to sort out the cropped headers ![Sensi_logREplot_SB_Dep_F_MSY](https://user-images.githubusercontent.com/4992918/85639921-19301d80-b63f-11ea-8b79-e2dab4bc3062.png)

**Comment by iantaylor-NOAA** [comment]
New function SS_Sensi_plot() described in this issue above has been added to the `development` branch in Pull Request #509.
See `help(SS_Sensi_plot)` for example usage.
