### ISSUE TITLE
make things smoother if some output files are missing

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#208]
Currently if the CompReport.sso file is missing, you have to specify `NoCompOK=TRUE`, but it would be easier if there were just a warning about the file missing and allow it to play through smoothly. Also, specifying `compfile=NULL` should allow you to skip reading of the CompReport.sso to save time if you're not interested in that output.

Similar changes could be made for other output files like forecast.ss.

**Comment by iagomosqueira** [comment]
Thinking on `SS_output()`, it could check with `file.exists()` for those not essential, issue a warning, if `verbose=TRUE`, and keep going, but only if the file name has not been set to NULL.

**Comment by iantaylor-NOAA** [comment]
This was resolved 4 years ago in https://github.com/r4ss/r4ss/pull/412.
