### ISSUE TITLE
error finding stdtable in ss_plots

### ISSUE THREAD

**Issue by mkapur** [r4ss/r4ss#211]
Hi Ian
My name is Maia Kapur, stock assessment at PIFSC (Honolulu). I'm using r4ss v 1.24.0 with SS3 3.4.0. After executing my model with hessian, I'm unable to get SS_plots to render the uncertainty with the following error:

```
Skipping spawning biomass with uncertainty plot because 'SPB_Virgin' not in derived quantites.
   Try changing 'min yr for Spbio_sdreport' in starter file to -1.
Error in biofunc(subplot = subplot) : object 'stdtable' not found
```
The error is retained when `min yr` is set to `-1`, though I think the error is not specific to SPbio. Our log_det_hessian is positive definite.

I looked into the source code [here](https://rdrr.io/cran/r4ss/src/R/SS_output.R) and it appears to be searching within covar.sso, which is returned successfuly from SS_output. I'm happy to provide in/output files if needed. 

Thanks for your help!

MK

**Comment by taylori** [comment]
Hi Maia,
Sorry for your troubles. Unfortunately r4ss version 1.24.0 available on CRAN is out of date and doesn't work for many models. Please try to install r4ss from github using the commands on the README file at https://github.com/r4ss/r4ss (which I just updated to show installing from GitHub is the recommended method). If you have troubles with the installation, or that doesn't make the error go away, please let me know. If the error persists in the newer r4ss (v1.30.2), please send your SS input files to me at Ian.Taylor@noaa.gov so I can try to debug the issue.
Thanks,
-Ian

**Comment by mkapur** [comment]
Hi Ian
Thank you so much for the quick reply. Installing r4ss from github solved my problem! Feel free to close. MK

**Comment by taylori** [comment]
Happy to help.
Please report any future issues you face.
