### ISSUE TITLE
head(out$Kobe) appears broken

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#212]
Using r4ss 1.30.1, Report.sso from SS3 3.24.z, the Kobe data.frame coming from SS_output looks like this

```
> head(out$Kobe)
     MSY_basis:_calculate_FMSY NoName    NoName
4815                        NA     NA        NA
4816                      1950  3.826 3.099e-05
```

with names tangled. The problem appears to be in either line 1941 or 1945 of SS_output.R, which are both tested to FALSE, so shift remains 1 instead of 2.

Kobe_head looks like this

```
                     Kobe_Plot  NoName      NoName
4814 MSY_basis:_calculate_FMSY                    
4815                      Year  B/Bmsy      F/Fmsy
4816                      1950 3.82568 3.09886e-05
```

so shift needs to be 2 to use the line starting with 4815 as header. I assume the test that should detect this is the one in line 1945, but it is looking at line 2 of Kobe_head, instead of line 1, as the first comment line is being used as header by

```
Kobe_head <- matchfun2("Kobe_Plot",0,"Kobe_Plot",3,header=TRUE)
```

Changing this to

```
Kobe_head <- matchfun2("Kobe_Plot",0,"Kobe_Plot",3,header=FALSE)
```

or

checking for MSY_basis on the first two lines

```
    if(length(grep("MSY_basis",Kobe_head[1:2,1]))>0){
      shift <- shift+1
      Kobe_MSY_basis <- Kobe_head[2,1]
    }
```

but I am not sure it won't break in some mother cases.

**Comment by iagomosqueira** [comment]
This is working fine in r4ss 1.24.0, R 3.3.3, on the very same file

**Comment by iagomosqueira** [comment]
One alternative way of calculating shift is to search from 'Year' and assume that is the header of the table

```
Kobe_head <- matchfun2("Kobe_Plot",0,"Kobe_Plot",3,header=TRUE)
    shift <- grep("Year", Kobe_head[,1])
    Kobe_warn <- NA
    Kobe_MSY_basis <- NA
    if(length(grep("_basis_is_not",Kobe_head[1,1]))>0){
      Kobe_warn <- Kobe_head[1,1]
    }
    if(length(grep("MSY_basis",Kobe_head[1,1]))>0){
      Kobe_MSY_basis <- Kobe_head[1,1]
    }
    Kobe <- matchfun2("Kobe_Plot",shift,"SPAWN_RECRUIT",-1,header=TRUE)
```

**Comment by taylori** [comment]
Thanks for catching this @iagomosqueira, and for taking time to look into the details and propose a solution.
Seeing my note
```
    # head of Kobe_Plot section differs by SS version,
    # but I haven't kept track of which is which
```
combined with the use of `if(SS_versionNumeric < 3.23)` supports my current view that switches based on things like which line has "Year" are more robust than switches based on version number.

Do you have time to try to test this out on the model you have an create a pull request? I can do further testing. In theory, every time something like this comes up we could create a new `testthat` test to ensure that future changes to SS or r4ss don't break the feature. But I'm not yet quick enough at writing those tests to have gotten to that level.

**Comment by iagomosqueira** [comment]
I can only test my proposal on 3.24 files but it would affect all versions, as the only version check for shift is in line 2039 and gets then overridden. Is there any repository of SS3 output files for different versions that could b used to test it?

**Comment by iagomosqueira** [comment]
Sorry, version check in 2039 is only relevant for spr. I hope finding "Year" is good enough for all versions

**Comment by taylori** [comment]
Thanks to advice from @kellijohnson, I revised the test functions in commit 3dfdf0e to make it easier to test individual pieces of the list returned by `SS_output` and added a simple test the `$Kobe` output (checks for the Year column being all numeric values within a reasonable range of years).

If somebody reports a bug in the Kobe output for a 3.23 model or earlier, then we can revise the version check at https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L2039. In general, I haven't been trying to provide more than minimal support (meaning the function doesn't crash) for SS versions prior to 3.24.

Regarding examples for testing, there's an effort just begun to build an updated set of SS models for use in testing and learning about SS. For now there are some examples of 3.24 and 3.30 models on VLab in Document Library/Examples and also the "simple" model in both 3.24 and 3.30 formats in the [/inst/extdata/](https://github.com/r4ss/r4ss/tree/master/inst/extdata) directory of this package that are used for the tests.

Thanks @iagomosqueira for reporting and fixing the bug and for adding the `lapply` function. We could probably use lots more of those throughout SS_output. Please close this issue if you're satisfied with where things stand now.
