### ISSUE TITLE
columns from SS_output labeled as NoName 

### ISSUE THREAD

**Issue by mkapur** [r4ss/r4ss#214]
Hey Ian, me again. Bumped into an error with the new r4ss (downloaded from git) that I suspect is happening during the `SS_output` stage. Using the `SS_output` function from the CRAN version does not produce the erro. I recognize the kobe situation is mentioned in #212 but figured add'l info may be of use. 

Issues identified in a `model` object returned by `SS_output()`:

1) `model$cpue`; the column previously known as "FleetNum" is now labeled "Fleet". This may be intentional, but is distinct from what is on CRAN (and pertains to the column which is actually the Fleet's number in SS). Easy for me to change in my personalized code, but wanted to let you know.

2) `model$index_var_tuning_check`: "fleetname" is now labeled as "NoName"

3) `model$kobe`: both B/BMSY and F/FMSY columns are called "NoName" - see above

We tested this on a couple different report files for different models and got the same result. Let me know if you need more info!

Thanks
MK

**Comment by taylori** [comment]
Thanks for reporting these things, MK. I really appreciate the detailed list of issues. Many people have code they have written which depends on r4ss, so there's going to be adaptation needed whenever I or others make a change here. I've tried to be transparent with things like the list of column header changes in #141, but lots of things slip through the cracks so it's great when folks report issues like yours.

Here are comments on each of the issues you reported:

1. The old "FleetNum" column was created within earlier versions of r4ss to deal with the format of that table in older SS versions where the "Fleet" column had a format that combined the number and the name, like "2_SURVEY1". Starting in some version of 3.24 the table reported by SS had separate columns "Fleet" for the number, and "Name", so there was no need to use `strsplit` to create a new column.
2. In some 3.24 versions of SS, the `INDEX_1` table in Report.sso, which `SS_output` returns as `$index_var_tuning_check` was missing a column name for the final column. However, this is easy to fix. As of commit d85575dc507829dfcd6d92d8d830145c0a5ede1f the column name should appear as "Name". Not many people use this table as SS option to estimate an extra variance parameter for indices of abundance has generally replaced iterative tuning of index variances, but there is still useful information there, and I see that the columns aren't even converted to be numeric. It would be easy to do so if that would be useful.
3. NoName columns in Kobe are likely related to the changes discussed in #212, but I just made a change in the processing of the Kobe table in commit f452cbaa58f676122b6c2f07f26f84e23c79250e to deal with a different problem for a model I just tested it on, and that change may fix your issue as well. If it still appears with "NoName" even after getting this latest change from GitHub, could you send your Report.sso file to ian.taylor@noaa.gov for me to find a better solution?

Thanks again,
-Ian

**Comment by mkapur** [comment]
Hi Ian
As usual, thanks for the rapid response! OK, that makes sense about the `FleetNum` in `CPUE` and thanks for referencing the header changes issue. I had a suspicion that the `tuning_check` was rarely used -- I tried running this again and it doesn't seem to work. With a cursory google I couldn't find the `df.rename` function added in commit  [https://github.com/r4ss/r4ss/commit/d85575dc507829dfcd6d92d8d830145c0a5ede1f](url) to test on my own (is it custom?). As you mentioned, this isn't pressing, and for now I can make do with the `Fleet` column (or even `NoName`) itself, so no urgency there.

Tested name fix for `Kobe` and it appears to be corrected, thanks! Feel free to close.

Maia

**Comment by taylori** [comment]
Good to hear that progress is being made.

The `df.rename` function is defined earlier inside `SS_output` (starting on line 133): https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L133 

I tried the revised `SS_output` on a couple different 3.24 models and a 3.30 model and the final column of `$index_variance_tuning_check` came out as "Name" in all cases. What version of SS are you using?

**Comment by mkapur** [comment]
Thanks for the link to `df.rename` -- I actually had missed a restart before writing my response about the `tuning_check`. Looks good now!

**Comment by taylori** [comment]
Great. Closing issue now. Please re-open or post a new one when problems arise in the future.
