### ISSUE TITLE
SS_output extraction of reference points 

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#215]
Before attempting to write the simple code to do it, I wanted to check if there is any reason why some reference points, particularly Fstd_MSY is not being returned by SS_output. Or is it just that there has been no need or request so far? Or am I missing something in the output?

Would returning a new list element be a problem?

**Comment by taylori** [comment]
There are a bunch of reference points in the DERIVED_QUANTITIES table in Report.sso that are reported by SS_output as `$derived_quants`.
You should be able to get Fstd_MSY as 
```
model$derived_quants["Fstd_MSY", "Value"]
```

You can also get a table comparing any values in `$parameters`, `$derived_quants`, and `$likelihoods_used` using the `SStableComparisons` function (where the arguments `names` and `likenames` control which quantities are returned, where the following should return SSB_MSY,  SPR_MSY, Fstd_MSY, Dead_Catch_MSY, and Ret_Catch_MSY:
```
SStableComparisons(SSsummarize(list(model1, model2)), names=c("MSY"))
```

**Comment by iagomosqueira** [comment]
Sorry for overlooking those. I think my old idea of some diagram showing the link between elements in Report.sso and those in SS_output might need to be revived.
