### ISSUE TITLE
table or diagram matching Report.sso sections to SS_output list

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#216]
As noted by @iagomosqueira in issue #215, it would be very useful to have a table or diagram matching Report.sso sections to the list returned by `SS_output`. This is surely long overdue.

A quick start on the first dozen keywords below was already informative in identifying 2 outputs that do not get read by `SS_output`.

I'll continue the list as I have time (or others with NOAA email addresses can contribute to [this Google Sheet](https://docs.google.com/spreadsheets/d/1oUlH9Y78wQIUuVC3Dyw1jtsQsnwvm5qhQZT91_Ammss/edit?usp=sharing), but I'm curious for input on the following questions:

1. Is there some other format that this information should take? @iagomosqueira did you have an example in mind with your use of the term "diagram"?
2. Where should this table be stored? It could be multiple locations as long as we keep them up to date, such as:
    - the help page for SS_output
    - the SS User Manual
    - a new wiki page at https://github.com/r4ss/r4ss/wiki
3. This list will reveal confusing differences between the Report.sso and SS_output names. Should further work be done to align these terms (as discussed to some extent in issue #141) or is it better to just increase awareness of the differences and not risk breaking  other people's code by changing things?

Please comment on this issue or email ian.taylor@noaa.gov if you have thoughts on these questions.

---
Start of the table:

Report.sso keyword | Objects in list created by SS_output function in r4ss
-- | --
DEFINITIONS | Split into separate variables: $nseasons, $seasfracs, $seasdurations, $FleetNames
LIKELIHOOD | $likelihoods_used, $likelihoods_by_fleet, and $Parm_devs_detail (not currently working)
Input_Variance_Adjustment | NA
PARAMETERS | $parameters
DERIVED_QUANTITIES | $derived_quants
MGparm_By_Year_after_adjustments | $MGparmAdj
selparm(Size)_By_Year_after_adjustments | $SelSizeAdj
selparm(Age)_By_Year_after_adjustments | $SelAgeAdj
RECRUITMENT_DIST | $recruitment_dist (a list containing $recruit_dist, $recruit_dist_Bmark, and $recruit_dist_endyr
MORPH_INDEXING | $morph_indexing
SIZEFREQ_TRANSLATION | NA (only present for models using generalized size frequency data)
MOVEMENT | $movement

**Comment by kellijohnson** [comment]
@iagomosqueira and @kellijohnson were trying to find out where some information in `endgrowth` was coming from and were reminded of this issue. I propose documenting where things are coming from in the call to `@return` within the function. I don't think everything needs to be documented as thoroughly as I am trying to capture some in aa8e0f84c2993487ef7eaa7bd7dee4468ee9f610 but the information was available. I am happy to at least try to include some of the list elements from `SS_output` in this manner to see if it is helpful. Thoughts? One can see my changes in the documentation branch.

**Comment by taylori** [comment]
Thanks @kellijohnson for the suggestion. Your documentation of `endgrowth` is wonderful, but I'm concerned that this level of description would be overwhelming in the context of the `@return` in the function help, if a similar treatment were applied to other tables with similarly complex and important information. But maybe there aren't that many? Others surely include `timeseries`, `recruit`, `sprseries`, as well as the meanings of the values in the `Factor` column in `sizeselex` and `ageselex`.

What about putting all these instead in an appendix to the SS User Manual? The information could be repeated in both places, but that would increase the maintenance burden.

While on the subject, should we go ahead and rename `endgrowth` to either `biology_at_age` or `Biology_at_age` as discussed at https://github.com/r4ss/r4ss/issues/233?

**Comment by iagomosqueira** [comment]
There is always the option of keeping it as a vignette in the package, linked from the `SS_output` help page.

**Comment by taylori** [comment]
The table of matching values is now filled out on the wiki page: https://github.com/r4ss/r4ss/wiki/Matching-Report.sso-keywords-to-r4ss
Vignette or expanded help files still seem like good ideas but will take more work.

Filling in the table revealed a number of elements of Report.sso that are not currently read by r4ss, so I will work on adding those to `SS_output`.

**Comment by CWetzel** [comment]
This is great.  Thank you for putting this together.

**Comment by iantaylor-NOAA** [comment]
A more detailed table will be available in the next version of the SS3 User Manual as discussed in https://github.com/nmfs-ost/ss3-doc/pull/238
