### ISSUE TITLE
Dirichlet-multinomial for length data

### ISSUE THREAD

**Issue by James-Thorson** [r4ss/r4ss#220]
Hi there,

I see that the code has not yet been written for models using Dirichlet-multinomial weighting for length comps:

```R
    if(!is.null(age_data_info)){
      age_data_info$CompError <- as.numeric(age_data_info$CompError)
      age_data_info$ParmSelect <- as.numeric(age_data_info$ParmSelect)
      if(!any(age_data_info$CompError==1)){
        stop("Problem Dirichlet-Multinomial parameters: ",
             "Report file indicates parameters exist, but no CompError values ",
             "in data.ss_new are equal to 1.")
      }
    }
    if(datfile$use_lencomp){
      len_info <- datfile$len_info
      if(any(len_info$CompError==1)){
        warning("r4ss doesn't yet account for Dirichlet-Multinomial likelihood ",
                "for length comps.")
      }
    }
```

The way its currently written throws an informative error if using DM for length but not ages.  Please tell me if I should help to get it up and running for the general case?

Jim

**Comment by taylori** [comment]
Sorry for forgetting to come back to this. I'll work on it today and let you know how far I get.

**Comment by taylori** [comment]
Thanks @James-Thorson for motivation to work on this. Changes made in commit b673d3a to the 'development' branch were pretty simple. Please try it out using 
```
devtools::install_github('r4ss/r4ss', ref='development')
```

Note that additional output for models that use Dirichlet-Multinomial parameters is `$Dirichlet_Multinomial_pars` element of list produced by `SS_output` (really just a subset of `$parameters` where those same lines occur) as well as revised text in composition plots and associated captions. 

See description at https://github.com/r4ss/r4ss/issues/129#issuecomment-358468468 for more detail.

**Comment by James-Thorson** [comment]
Thanks Ian!

Unfortunately, the code still erroneously throws a bug in line `SS_output` line 995.  After some sleuthing, I believe that SS3 generates the `age_data_info` and `len_data_info` if there is a Dirichlet-multinomial in either length of age-data inputs.  However, I have a case with only a D-M parameter for length.  Therefore, it generates `age_data_info` but all of the `CompError=0` in that block, so it erroneously kills the function.  The function appears to run properly if I comment out that error.  However, I don't really understand the logic well enough to propose a solution.  Could you advise on how I can help?

**Comment by taylori** [comment]
Sorry I didn't test the the length-only case. Nor have I tested the case of sharing the D-M parameters across fleets. I'll try to get to that later today. In the long run, additional outputs from SS would make the logic easier in r4ss but I haven't help get that implemented.

**Comment by James-Thorson** [comment]
no need to apologize ;)  I'm also sorry that I haven't helped more on the r4ss side on this, or really made any effort at testing the conditional age-at-length.

please tell me if I can help.

**Comment by taylori** [comment]
OK, code revised in commits a4cf136 and e4e6bce to 'development' branch works for a model with Dirichlet-Multinomial likelihood only applied to the length comps. Took a while for me to understand my own logic. @James-Thorson let me know if it works for your model.

**Comment by James-Thorson** [comment]
Ian,

Thanks again for your help!  The function now runs without error.  However, I recommend adding one new line between current lines 1633 and 1634:

```R
  returndat$len_data_info <- len_data_info
```

where as far as I can tell, you intended to return `returndat$len_data_info` as you do with `returndat$age_data_info`, but perhaps forgot to insert that line in this final section.  Feel free to add it or not according to your intended usage, but the code otherwise seems to behave as intended.

**Comment by taylori** [comment]
New line added as suggested.

Note that $age_data_info and $len_data_info both now returned by SS_output for models that use the D-M likelihood are coming from reading the data.ss_new file because that information is not yet available in the standard output files. There are some circumstances where data.ss_new may be missing or not match the current model where the values reported will not be correct. This can be fixed in a future version of SS.
