### ISSUE TITLE
`forecastplot` not working in SS_plots

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#222]
Thanks to Max Cardinale for reporting this.
Option in should work for time series as well as time-varying biology and selectivity plots.
In the past, $MGparmAdj excluded forecast years, so adding option there should be a quick fix. Not sure why timeseries isn't working.

**Comment by taylori** [comment]
I found an error in how the `forecastplot` input was working, changes in `development` branch should now have it working better, at least for some of the plots. Also see issue #251, related to the `minyr` and `maxyr` inputs which allow finer scale changes than `forecastplot=TRUE/FALSE`.

**Comment by iantaylor-NOAA** [comment]
Default value for `forecastplot` changed from TRUE to FALSE in `cleanup` branch to reduce the redundant time series plots. Users can change that to TRUE on the occasions that they are interested in forecasts, or use figures produced by `SSplotComparisons()`, which I think are better for forecasts anyway as facilitate comparing different harvest projections.
