### ISSUE TITLE
option to turn off unit scaling in density plots for SSplotcomparisons

### ISSUE THREAD

**Issue by mkapur-noaa** [r4ss/r4ss#229]
Hi Ian
Hope you're well. Didn't see this in other issues. I am working with the `SSB_virgin` density plots, and there doesn't seem to be a way to turn "off" the scaling of the x axis which results in the `"x axis has been divided by..."` message, in order to retain the raw values.

Not an urgent need, but this may be a simple add to the `if()` statements which define `xunits` starting ~line 1485. 

Let me know if I've missed something, and thanks!

MK

**Comment by iantaylor-NOAA** [comment]
This is a good idea. Recent commit 79a347b (also discussed in #335) to the `development` branch includes a `rescale = TRUE/FALSE` input added to `SSplotComparisons`.
