### ISSUE TITLE
Add dynamic B0 plots

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#23]
SS_output results include $Dynamic_Bzero. IATTC surely had nice use of this that could be used as inspiration.

**Comment by taylori** [comment]
Example plot from IATTC assessment is at 
![image](https://user-images.githubusercontent.com/4992918/43856343-14ab0d6a-9afd-11e8-96d1-5892011aa7c5.png)

The process to calculate the fleet-specific impacts requires manually removing catch from groups of fleets and re-running the model with parameters fixed at values in the .par file. An automated process may be forthcoming at some point in the future.

For the moment, r4ss should include the simpler plot showing just the bottom and top lines from that figure, based on the `$Dynamic_Bzero` table.

**Comment by iantaylor-NOAA** [comment]
Uncertainty in the estimated annual dynamic B0 values are now available in SS as discussed at https://github.com/nmfs-stock-synthesis/ss-documentation/issues/31 so whenever a figure gets added to r4ss, it can have uncertainty added as well when `Dyn_Bzero*` elements are found among the derived quantities.
