### ISSUE TITLE
SS_tune_comps for 3.24 models

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#232]
SS_tune_comps returns a table that can be inserted into the control file to apply either the McAllister-Ianelli or Francis data-weighting methods. Someone on the webinar with SEFSC pointed out that it doesn't currently work with 3.24 models. 

I just made a fix in commit 15d9d61d5c841e02a7b0db7badafed62b149f185 which got it working for at least one 3.24 model, but will leave this issue open pending further testing. Please comment if you try it with a 3.24 model and it doesn't work.

**Comment by taylori** [comment]
Correction: the function runs for 3.24 models without crashing, but the table it reports is in the 3.30 format. Returning a table of variance adjustments as required by 3.24 shouldn't be too hard, but still needs to be done.

**Comment by iantaylor-NOAA** [comment]
No longer supporting anything related to 3.24 and earlier except reading output and making comparison tables and plots.
