### ISSUE TITLE
adapt to changes in output format for 3.30.12

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#238]
SS version 3.30.12 will have a few format changes
Report.sso has expanded DEFINITIONS section and revised sections for summary of fit to length and age comps, among other changes.
CompReport.sso will include new "Month", "Subseas", and "Area" columns.

The 'development' branch of r4ss, installed via `devtools::install_github('r4ss/r4ss', ref='development')` contains changes to allow reading and interpretation of these changes while attempting to preserve backwards compatibility. 

The changes will be merged after more testing has taken place, likely in mid-July after I return from a research trip. Feel free to post any issues with the updated code as github issues while I'm away.

**Comment by taylori** [comment]
I think the remaining minor issues related to changes in format with SS version 3.30.12 have been ironed out.
Anyone using the 3.30.12beta with r4ss should install the 'development' branch via `devtools::install_github('r4ss/r4ss', ref='development')` and provide feedback on any issues you see.

Those working with any earlier version of SS, please feel free to test the development branch as well, as the changes should all preserve backwards compatibility.

The r4ss version number has been incremented to 1.32.0 (just in the development branch so far, to be merged after further testing, probably next week).

**Comment by taylori** [comment]
Branch now merged into trunk in commit babff68. Will leave issue open until official release of SS version 3.30.12 and further confirmation that main trunk of r4ss continues to work with it.

**Comment by kellijohnson** [comment]
Somewhere between 33d6cdddc1ae07f7a8fcad4a7c3a0ebe249823db and current development branch (i.e.,  c4bfc3873d22c86881eb2a6f3e861949a20e3eaf) `SS_output` was changed from searching for Sex to Sexes or something along those lines. Anyway in `SSplotComps`  on line 405
```
dbase_kind <- dbase_kind[dbase_kind$Fleet %in% fleets & dbase_kind$sex %in% sexes,]
```
"sex" is used to subset the data, where "Sex" is the column name in the dataframe. Not sure exactly how to fix this because the naming changes led to so many different commits. I found this when trying to compile the hake stock assessment and figure 25 failed.  Let me know if you need more details.

**Comment by taylori** [comment]
@kellijohnson, thanks for catching this.  I think I just got it fixed in commits 61e2282 and de77514.

The column naming in CompReport.sso has shifted multiple times, and is potentially confusing. Column names were being changed to match the 3.30.01 convention, which replaced "gender" with "sex", but had not yet been changed to match the 3.30.12 convention, where "Pick_sex" had been replaced with "Sexes", which was required to create the new lowercase "sex" column used by r4ss. Now both old and less-old models should all be mapped to the current standard. This seems to have restored the age-comp plots for the hake model which used 3.30.10.00. An explanation of the 3 similarly-named columns and the creation of the `sex` column are here: 
https://github.com/r4ss/r4ss/blob/de77514d0c241d6ad7179568a4869dd24dbd76fa/R/SS_output.R#L655-L670

**Comment by taylori** [comment]
In the previous comment, I pasted a link to a block of code, which causes the full block to appear on the github issues page. However, I see that email notifications only include the link, not the code itself. I'm pasting the code directly in this additional comment to increase awareness of the potentially confusing set of similarly-named columns: `Sexes`, `Sex`, and `sex`. That last one, which is created and used in r4ss, could be renamed to something different throughout r4ss to reduce the confusion.

Here's the block of code in lines 655-670 of SS_output (as linked in previous comment):
```
 # update to naming convention associated with 3.30.12 
 compdbase <- df.rename(compdbase, 
                        oldnames=c("Pick_sex", "Pick_gender", "Gender"), 
                        newnames=c("Sexes",    "Sexes",       "Sex")) 
 # "Sexes" (formerly "Pick_sex" or "Pick_gender"): 
 #         0 (unknown), 1 (female), 2 (male), or 3 (females and then males) 
 # this is the user input in the data file 
 # 
 # "Sex" (formerly "Gender"): 1 (unknown or female), or 2 (male) 
 # this is a code used internally by SS 
 # 
 # add new column in code below: 
 # "sex": 0 (unknown), 1 (female), or 2 (male) 
 # this is the code used by r4ss 
 compdbase$sex <- compdbase$Sexes 
 compdbase$sex[compdbase$Sexes==3] <- compdbase$Sex[compdbase$Sexes==3] 
```

**Comment by kellijohnson** [comment]
thanks @taylori for the fix and the documentation. the issue is now fixed with respect to the hake assessment.

**Comment by taylori** [comment]
r4ss seems to be working adequately with SS version 3.30.12 as well as 3.30.13-beta, so closing this issue.
