### ISSUE TITLE
PType column in output of SS_readctl_3.24

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#253]
SS_readctl_3.24 now adds a column named PType tp the SR, MGParms and initial_F data.frames. Is this correct for 3.24? A ctl file loaded and then saved fails to run in 3.24 unless I delete this column.

**Comment by taylori** [comment]
Thanks for reporting this. It looks like the PType was added by Neil Klaer as part of all the improvements he made back in May (in commit adeba650f2a8ca7427e714b3d7bc1893a5c75100), but Neil was focused on reading files and clearly the link to SS_writectl_3.24 was not tested.

Without knowing how PType is being used, I could see two easy options to fix this that hopefully wouldn't break anything. We could add a switch to SS_readctl_3.24 that turns on or off the addition of this column.

Or even easier would be to add the following to the printdf function in SS_writectl_3.24 (which would go before line 118: https://github.com/r4ss/r4ss/blob/master/R/SS_writectl_3.24.R#L118:
```
        if("PType" %in% names(dataframe)){
          dataframe <- dataframe[ ,names(dataframe)!="PType"]
        }
```

**Comment by iagomosqueira** [comment]
That should work, sure. Although code that manipulated the ctl list is also failing due to the extra column. My temporary fix was to drop PType from the various cbind calls, like line 513

```
ctllist$MG_parms_seas<-cbind(ctllist$MG_parms_seas,PType)
```

This could be controlled by an extra argument. ptype=TRUE. Will try to create a pull request.

**Comment by taylori** [comment]
Having the option to exclude the column seems to be the cleaner solution anyway, so pull request for that approach would be great. Thank you.
