### ISSUE TITLE
Run error related to installation

### ISSUE THREAD

**Issue by scribblefish** [r4ss/r4ss#256]
When I try to run a function in r4ss, I get the following error:

Error: lazy-load database 'C:/Users/llee1.AGENCY/Documents/R/win-library/3.5/r4ss/R/r4ss.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1

**Comment by kellijohnson** [comment]
Have you tried reinstalling r4ss after closing your current R session? If that doesn't work, then some information about your R workspace would be helpful. What does `sessionInfo()` return?

**Comment by taylori** [comment]
Thanks for responding @kellijohnson. I just got word from @scribblefish that restarting R and reinstalling r4ss worked, so closing issue.
