### ISSUE TITLE
proposed change in workflow for MCMC output

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#257]
I've been trying to explain the workflow for working with MCMC results in r4ss and getting myself confused, so I think it's time for some revisions to make things more straightforward. If anyone has suggested changes or improvements to this plan, please post them here.

First, I think the best workflow for running MCMC is to have separate directories where the MLE and MCMC results are located. This could involve an `mcmc` sub-directory within the directory where the MLE was run, or it could be parallel directories.

To facilitate this approach and reduce the confusing and inconsistent steps to get the output, I'm proposing the following changes to r4ss:
- Change the `SSgetMCMC` function to only work on a single directory, not a vector of multiple directories, and return the data.frame of MCMC results (each column a parameter, each row an MCMC sample), rather than a list, often with a single element, which contains this data.frame for each model. Thus, the `[[1]]` could be removed from various applications of `SSgetMCMC(... )[[1]]`
- Add to the `SS_output` function an optional input `dir.mcmc` which would cause the function to call `SSgetMCMC` and include the `$mcmc` data.frame in the list returned by this function.
- Change the `SSplotPars` function to take the output from `SS_output` rather than reading the Report.sso and posteriors.sso files directly.
- Change the `SSsummarize` function so that it looks for an `$mcmc` element in the models you get and automatically creating the `$mcmc` list in the summary output rather than requiring the user to run `SSgetMCMC` to form that list. The user would still have to specify `mcmcVec=TRUE/FALSE` to indicate which result should be plotted. To do a comparison of the MLE vs MCMC for the same model, you would do something like the following
```
# read model output, including MCMC
model1 <- SS_output(dir=mydir,
                    dir.mcmc="mcmc") # could also be absolute rather than relative path
# create summary of the same model twice
model.sum <- SSsummarize(list(model1, model1))

# plot comparison of MLE vs MCMC
SSplotComparisons(model.sum, mcmcVec=c(TRUE, FALSE))                               
```

**Comment by taylori** [comment]
Also, I propose revising the `mcmc.out` and `mcmc.nuisance` functions to work with the `$mcmc` element of the list created by the augmented `SS_output` rather than reading CSV files written by `SSgetMCMC`.

Alternatively, these two functions could be revised or replaced to make use of the `plotMCMC` package by @arnima-github as noted in issue #25 , but that would take slightly more work.

**Comment by iantaylor-NOAA** [comment]
Workflow changes proposed here have been implemented and seem to be working as intended.

**Comment by iantaylor-NOAA** [comment]
Commit 5e9a2983c0cb6978ab7e1dcfff2f9647042bc51a to the development branch allows `dir.mcmc` to be either a relative or an absolute path to the directory where the MCMC output files are located. Previously it could only be a relative path which was a source of confusion.
