### ISSUE TITLE
SSplotProfile crashes if minfraction input is too high

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#261]
Thanks to Max for reporting an issue with `SSplotProfile` which turns out to have been a problem with the `minfraction` input which filters which likelihood components get shown in the graph. A value of `minfraction=1` will generally filter to only the total likelihood, but the function couldn't handle having only 1 line to plot. 

As of commit 465e1c2e78a45e77c6196f82217060a577bc6a62 to the development branch, the function should work even if only the total is included and will stop with a warning if all components, including the total likelihood are filtered out by a value of `minfraction` which is too high.

The default `minfraction = 0.01` will show all components which have a change in likelihood of greater than 1% of the total likelihood change across the models included in the profile.

**Comment by taylori** [comment]
I should have noted that the change in the function was in the `development` branch.
