### ISSUE TITLE
SSprofile function giving error: missing digits when print(linenums) is called from within SS_changepars

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [r4ss/r4ss#280]
I got an error associated with the subfunction call to SS_changepars, where the line with print(linenums) gave an error b/c it wanted digits to be input when verbose=TRUE (the default).  Changing verbose=FALSE seems to have removed the issue (profile function now running), but just making a note of this conflict here.

**Comment by taylori** [comment]
@aaronmberger thanks for reporting this.  Sounds like `verbose=FALSE` makes the problem go away, so there's no need to spend more time on it now.

However, for the record, I wasn't able to replicate the problem. I just ran the commands:
```
  prof.table <- SS_profile(dir=dir.prof,
                           masterctlfile="simple_control.ss",
                           string="R0", profilevec=c(8.5, 9))
```
which successfully printed the following messages including the `print(linenums)` from `SS_changepars`.

```
running profile i=1/2
parameter names in control file matching input vector 'strings' (n=1):
[1] "SR_LN(R0)"
These are the ctl file lines as they currently exist:
    LO HI    INIT PRIOR PR_SD PR_type PHASE env-var use_dev dev_mnyr dev_mxyr
118  3 31 8.81505  10.3    10       0     1       0       0        0        0
    dev_PH Block Blk_Fxn     Label Linenum
118      0     0       0 SR_LN(R0)     118
line numbers in control file (n=1):
[1] 118

wrote new file to control_modified.ss with the following changes:
  oldvals newvals oldphase newphase oldlos newlos oldhis newhis     comment
1 8.81505     8.5        1       -1      3      3     31     31 # SR_LN(R0)
Running model in directory: c:/github/r4ss/inst/extdata/simple_3.30.12/profile 
```

Feel free to post the commands you used or the output that got printed to the R console which will help me debug.

**Comment by iantaylor-NOAA** [comment]
Haven't heard of this issue occurring again so closing the issue. Can be re-opened if it crops up in the future.
