### ISSUE TITLE
SS_output and Dirichlet-Multinomial but no data in data.ss_new

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#287]
If the starter file specifies that no data be placed in data.ss_new, then ```SS_output``` at the following step:
https://github.com/r4ss/r4ss/blob/dc0adf1bbacf0dc06c9911b38546769757e28e55/R/SS_output.R#L1119
cannot find which fleet to assign the Dirichlet-Multinomial parameters to. I wrote the below code for myself, as a quick fix, but I am not sure how to best fix this for future users. In my twisted mind, it was easier to write code to change r4ss than to rerun the model with an altered starter file that specifies at least one copy of the dat file.
```
    # figure out which fleet uses which parameter,
    # currently (as of SS version 3.30.10.00), requires reading data file
    if(verbose){
      message("Reading data.ss_new for info on Dirichlet-Multinomial parameters")
    }
    test <- readLines(file.path(dir, 'data.ss_new'))
    ndatfiles <- type.convert(strsplit(
      grep("Number_of_datafiles", test, value = TRUE), ":")[[1]][2])
    if (ndatfiles == 0) {
      # The following only works on Windows
      # datname <- system(paste0("findstr /i /m Number_of_datafiles ", dir, "\\*.ss"),
      #   intern = TRUE)
      starterf <- readLines(file.path(dir, "starter.ss"))
      while (grepl("^\\s*#", starterf[1])) starterf <- starterf[-1]
      datname <- file.path(dir, gsub("(.+)\\s*#.*|\\s", "\\1", starterf[1]))
    } else {
      datname <- file.path(dir, 'data.ss_new')
    }
    datfile <- SS_readdat_3.30(file = datname,
                               verbose=verbose)
```

**Comment by taylori** [comment]
Thanks @kellijohnson.
Could you try to fix just committed to `development` in 732ed18?
I followed your approach, but added a simpler check for empty datafile to the `SS_readdat_3.30` function by the simpler test of the number of lines less than 20 which works even if the string "Number of datafiles" is absent, and used `SS_readstarter` instead of your more efficient parsing of the starter file.

**Comment by taylori** [comment]
I should have noted that the longer-term solution is to include all important information about the Dirichlet-Multinomial parameters in the SS output files (as noted in the SS redmine issue number 28432) so that there's no need to read a data file to get that info.

**Comment by kellijohnson** [comment]
Thanks @taylori, I didn't see anything that needed changed. The fix worked for me.

**Comment by taylori** [comment]
Sounds good.
