### ISSUE TITLE
'string' not found error in SS_ForeCatch

### ISSUE THREAD

**Issue by mkapur** [r4ss/r4ss#291]
Hi Ian -- possibly related to #184. I am trying to automate some iterating parts of a catch-only update, previously using a base loop to write my forecast catches to the forecast file. I am now trying to run SS_ForeCatch on a v3.24 model and am getting the error that object 'string' not found. My replist$catch_units == 1 for every fleet, so I'm not sure why the string object isn't being assigned (~line 71 [here](https://github.com/r4ss/r4ss/blob/master/R/SS_ForeCatch.R) )

Let me know if I'm missing something obvious (like this feature doesn't work for 3.24)! 

If it helps, I'm working with the last North China Rockfish assessment.
Thanks
MK

**Comment by kellijohnson-NOAA** [comment]
Looks like replist$fleet_type isn't present when reading in a 3.24 but is for 3.3 models.

**Comment by iantaylor-NOAA** [comment]
Fix attempted in commit 006d1b3 to development.

**Comment by mkapur** [comment]
The commit worked for me, thanks!
