### ISSUE TITLE
error while installing r4ss in R version 3.6.0

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#294]
This isn't an r4ss issue, specifically, but a user reported this error while trying to update r4ss:
```
> devtools::install_github('r4ss/r4ss')
Downloading GitHub repo r4ss/r4ss@master
Error in poll(list(self), ms) : 
  LOGICAL() can only be applied to a 'logical', not a 'integer'
```
As far as we can tell, the issue is with devtools and only occurring on R version 3.6.0 from about 2 weeks ago (2019-04-26). If you're using that same version and not getting an error, please report that here. If you're using an older version of R you might want to hold off on upgrading for the moment.

**Comment by aleorio** [comment]
Hi, 
I also get an error when trying to install r4ss in 3.6.0 but in 3.5. it works perfectly.
Here is the error I get.

```
> devtools::install_github('r4ss/r4ss')
Downloading GitHub repo r4ss/r4ss@master
√  checking for file 'C:\Users\alor0001\AppData\Local\Temp\RtmpqiBHLm\remotes277476ee3485\r4ss-r4ss-c9feed8/DESCRIPTION' ... 
-  preparing 'r4ss': (1.1s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (545ms)
-  checking for empty or unneeded directories
-  building 'r4ss_1.35.1.tar.gz'
   
Installing package into ‘\\storage-lk.slu.se/home$/alor0001/My Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
'\\storage-lk.slu.se\home$\alor0001\My Documents\Ale\SS3\Vendace'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'r4ss' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : there is no package called 'r4ss'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'r4ss'
* removing '\\storage-lk.slu.se/home$/alor0001/My Documents/R/win-library/3.6/r4ss'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/alor0001/AppData/Local/Temp/RtmpqiBHLm/file27745b337ee1/r4ss_1.35.1.tar.gz’ had non-zero exit status
```

**Comment by kellijohnson-NOAA** [comment]
@aleorio are you able to install other packages from github? It looks like it might be a path thing and not a problem with r4ss itself. See the discussion [here](https://support.rstudio.com/hc/en-us/articles/203775903-Fixing-startup-error-where-manipulate-and-rstudio-packages-will-not-install-with-networked-drives) regarding network paths.

**Comment by aleorio** [comment]
@kellijohnson-NOAA I have checked and realized I can't install anything from github in 3.6 but I can in 3.5.

**Comment by iantaylor-NOAA** [comment]
R version 3.6.1 is working fine for me and I haven't seen further indication of issues with installation in general, so closing this issue.
