### ISSUE TITLE
improve SSplotBiology for models with empirical weight-at-age data

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#30]
Thanks to Teresa A'mar for input on this.
Need to add display of wtatage matrix by season and include writing to PNG files for those figures.

**Comment by taylori** [comment]
Long overdue fix for this issue committed in bf1ca70 thanks to question from Mikaela Bergenius. Now empirical weight-at-age models should not see things like weight-length relationships and instead will just get 2 biology plots: weight-at-age and spawning output at age (maturity x fecundity). There is not yet support for separate weight-at-age matrix by fleet.

**Comment by iantaylor-NOAA** [comment]
Most empirical weight-at-age models in SS3 have a single matrix repeated for each fleet, and if they have separate matrices, it shouldn't be too hard to make custom plots to represent them. Therefore closing this 2014 issue in spite of the identified limitation noted in 2018: "There is not yet support for separate weight-at-age matrix by fleet."
