### ISSUE TITLE
replace as.numeric with type.convert in SS_output and perhaps elsewhere

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#308]
As noted in pull request #307, the `type.convert` function has some benefits over `as.numeric`, and could clean up many messy sections in `SS_output`.

In particular, blocks of code like
```
  # make values numeric
  for(icol in (1:ncol(parameters))[!(names(parameters) %in%
                                  c("Label","Pr_type","Status"))]){
    parameters[,icol] <- as.numeric(parameters[,icol])
  }
```
which occur in almost 40 places in `SS_output`, could be replaced by
```
  parameters <- type.convert(parameters, as.is = TRUE)
```
where the `as.is = TRUE` avoids conversion to factors.

**Comment by iantaylor-NOAA** [comment]
Commit 75c6e03 in new branch `type.convert` replaces all the loops with `as.numeric()` in `SS_output()` to use `type.convert()` with no loop.
This reduces the function by 100 lines of code (out of about 3000) and makes it easier to read.

I used `dplyr::all_equal()` to compare the data frames created with the old approach to the new approach, which showed some differences in type for many of the tables. , where columns which were numeric but only contained integers are now stored as integers. NA values are now treated as logical rather than numeric. I don't believe any of these differences have any impact on the model results, but will keep these changes in the separate branch pending a bit more testing.

**Comment by iantaylor-NOAA** [comment]
Running `SS_output()` for each of a set of 100 models took 2 minutes 23 seconds with the old approach and 2 minutes 20 seconds with the new approach. That tiny improvement might just be noise, but at least the `type.convert()` function noes not appear to be slower.

**Comment by mkapur** [comment]
I updated my r4ss install and am now getting an error which may be related to this change.
I've confirmed that this error isn't showing up for the same model for a colleague who hasn't updated their r4ss in a while. 

I think the source is the call to `type.convert(df,...)` on in line 144 of [SS_readdat](https://github.com/r4ss/r4ss/blob/b90113ad2819bb5d183b0caf7b238f667863c87f/R/SS_readdat_3.30.R).

Let me know if I'm overlooking something obvious!
```
mod <- SS_output(path_to_model, 
                 printstats=FALSE, 
                 verbose = FALSE, 
                 hidewarn = TRUE, 
                 warn = FALSE,
                 forecast= FALSE
                 )

Error in utils::type.convert(df, as.is = TRUE) : the first argument must be of mode character
```

**Comment by iantaylor-NOAA** [comment]
Hi @mkapur. First, thanks for raising this issue which helps me realize I never merged the `type.convert` branch referenced above. Therefore, it is indeed surely the call in `SS_readdat` (which is called from `SS_output` for models that use the Dirichlet-Multinomial likelihood to get information on which parameters match which composition observations). If you installed the `development` branch of r4ss and got this error, could you please email me the `data.ss_new` file for the model you're using to me and @k-doering-NOAA  who has been working on improvements to the readdata functions. If it was the master branch you installed, try installing `development` instead to see if the problem has been fixed already.

**Comment by mkapur** [comment]
Thanks for the quick reply. My first issue occurred using the `master` branch; I have downloaded `development` and unfortunately the error persisted; emailing you and @k-doering-NOAA now.

**Comment by iantaylor-NOAA** [comment]
@mkapur thanks for your offline sleuthing and figuring out that updating R to a newer version of R fixed the problem. And thanks to @k-doering-NOAA for finding out that `type.convert` became a generic function in R 3.5.0 (thanks to @arni-magnusson!).

Commit 620564c to `development` changes the `depends` setting in `DESCRIPTION`  to `R (>= 3.5.0)` and also increments r4ss version from 1.37.0 to 1.37.1. This may not impact installation via `remotes::install_github()` but will definitely force people installing from CRAN to have a reasonably new version of R.

**Comment by iantaylor-NOAA** [comment]
I closed this issue after fixing the problem identified by @mkapur 2 weeks ago but never actually merged the `type.convert` branch into `development`. That's now been done in Pull Request #374 (the changes are in commit 75c6e032376d567a080448777724e575afe39ed9).
