### ISSUE TITLE
Error in development branch in SS_readdat_3.30 when reading the fleets using the utils package

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#319]
I have been encountering an issue using SS_output for a model where the Dirichlet data weighting is applied.  In this type of model the function uses the SS_readdat_3.30 to identify the fleets to match with the Dirichlet parameters.  The current development branch encounters an error when using the utils::type.convert function and is reporting this error:

tils::type.convert(df, as.is = TRUE) : 
  the first argument must be of mode character

Looking at what is read, it looks correct but clearly, something is not right.

**Comment by iantaylor-NOAA** [comment]
Commit e447ebd changes from SS_readdat_3.30 to SS_readdat following the new approach with these functions which may fix the issue. @chantelwetzel-noaa, let me know if it works for your model.

**Comment by iantaylor-NOAA** [comment]
`SS_output` continues to work for models with Dirichlet-Multinomial likelihood and I haven't heard of this problem occurring again, so I'm closing this issue.
