### ISSUE TITLE
aggregated comps by fleet

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#320]
sample sizes on the aggregated compositions by fleet show the same sample size for discards as retained fish
Specifically, I am talking about comp_lendat__aggregated_across_time. Melissa mentioned it during her presentation during the STAR panel. I think we can make these partition specific.

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this and sorry for the error. This should be fixed in commit a9126ad. Let me know if it doesn't work for Sablefish.

**Comment by iantaylor-NOAA** [comment]
The fix seems to have worked. Closing this issue.
