### ISSUE TITLE
Make column names and fleet names in SS_readctl_3.30 and SS_writectl_3.30 consistent with control.ss_new

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#353]
@kellijohnson-NOAA noted that the column names and fleet names created by `SS_readctl_3.30` and `SS_writectl_3.30` are not consistent with those created by control.ss_new.  See bottom of this message for more details.

It does seem like long term, making column names and fleet names consistent with .ss_new files would be the best plan.

However, making this consistent with control.ss_new will mean breaking back-compatibility with older versions of these functions; for example, if someone had saved a 3.30 control file read in using `SS_readctl` as a .rda file, they would not be able to read it out using future versions of `SS_writectl()`.  Or, if someone had code to manipulate a control file read in using SS_readctl, they column names they reference may not longer work in future versions. Would anyone be concerned about this?

Related to #138 

------

Additional details about the issue from @kellijohnson-NOAA :

I used the read functionality to read in the cod EM control_ss.new file from a run and then I wrote it back to the disk immediately using the write function. There are some differences in the files. One of the major differences that I noticed right away is that the column names for the parameter data frames are different than what is written out from SS in the ss_new files. I have attached the two files that I was comparing. 

`#_LO  HI  INIT  PRIOR  SD  PR_type  PHASE  env_var  use_dev  dev_minyr  dev_maxyr  dev_PH  Block  Block_Fxn`
vs. 
`#_          LO            HI          INIT         PRIOR         PR_SD       PR_type      PHASE    env-var    use_dev   dev_mnyr   dev_mxyr     dev_PH      Block    Blk_Fxn  #  parm_name`
for example.

A second thing that I noticed was that the fishery and survey names are different than what is automatically generated. There are no numbers in the names that come out of the function but there are in the ss_new file. 

I don't currently know if these differences break anything, but I think that they could have the potential to given that colnames are pretty important in people's downstream code with r4ss.

**Comment by iantaylor-NOAA** [comment]
Looks like the old column names match the SS 3.24 headers, but are in the order used by SS 3.30. It makes sense to me to updating them to match the 3.30 headers properly.

It's probably a good idea to also update the same headers defined in `SS_parlines` as well. That function is used by `SS_changepars` but the latter function only reference column number, not column name.

I'm not aware of any downstream code that will be broken due to this change.

**Comment by k-doering-NOAA** [comment]
Great point @iantaylor-NOAA . I will update the SS_parlines names to match and test if anything breaks.
