### ISSUE TITLE
SS_writewtatage writes debug statements

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [r4ss/r4ss#359]
Since `SS_writewtatage` uses `sink()`, all output is printed to the file. This means if you're debugging the function, you'll get debug statements in the `wtatage.ss` file. I don't think this needs to be fixed because anyone who is running in debug mode can figure out how to avoid it, but in case others run into it...there might be a way to fix through arguments to `sink()`?

**Comment by kellijohnson-NOAA** [comment]
with `sink()` you can add the argument `sink(split = TRUE)` and it will print the output to the screen as well as the file that you are writing to. It could be used in the context of `SS_writewtatage()` with the verbose argument, i.e.,
```
sink(zz, split = verbose)
```

**Comment by iantaylor-NOAA** [comment]
@ChristineStawitz-NOAA good point. The change proposed by @kellijohnson-NOAA makes sense to me, so if you have time to try that out or something similar, please do and/or issue a pull request.

**Comment by ChristineStawitz-NOAA** [comment]
I changed this to what @kellijohnson-NOAA suggested in the wtatage branch

**Comment by ChristineStawitz-NOAA** [comment]
merged in pull request
