### ISSUE TITLE
make use of Bmsy/Bzero output

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#36]
New information in header of SPAWN_RECRUIT section as of SSv3.24U. This should be included in output from SS_output and perhaps noted in yield plots or their captions.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA It looks like this was added in PR #402 starting on [this line](https://github.com/r4ss/r4ss/pull/402/files#diff-75e6b87d1560c0b301317992f5f31a42f6cacaab7275322547fe04a486511621R1765). Can this issue be closed?

**Comment by iantaylor-NOAA** [comment]
PR #402 accounts for the presence of the Bmsy/Bzero line but doesn't actually return the value in `SS_output()`. However, since both Bmsy and Bzero are reported in the derived quantities, and the yield curve with reference points shows the position of this value, I see no need to make a change to r4ss at this point.
