### ISSUE TITLE
Adding R project files to and removing misc. files from .gitignore and .Rbuildignore

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#367]
Does anyone have thoughts on these proposed changes to r4ss? Some proposed changes to [.gitignore](https://drive.google.com/drive/u/0/folders/1BLIQPceLueAUqMXfkker7boss9g8XRnn) and [.Rbuildignore](https://github.com/r4ss/r4ss/blob/4f7ae1db53f862166553fb7d78a2bc89ab08c11c/.Rbuildignore):

- [x] Add `\.Rhistory`, `*\.Rproj`, and `^\.Rproj\.user/` to the .gitignore file and `^.*\.Rproj$` and `^\.Rproj\.user$` to the .Rbuild ignore file. This would be helpful for those who use R studio and R studio projects so that those files that are necessary to have locally are ignored by Git.
- [ ] Remove some of the .gitignore files like [files in inst/extdata directory](https://github.com/r4ss/r4ss/blob/4f7ae1db53f862166553fb7d78a2bc89ab08c11c/.gitignore#L43-L49) to the extent possible. I think these were added to .gitignore because they are artifacts created by running the testthat tests. If possible, it would be better to save these files to a temporary directory instead of saving them in various locations throughout the R package files.

For me, I think these changes would make working with r4ss locally slightly easier and I think it would be the same for others who use R studio projects and run the testthat tests locally. I would be happy to make these changes, if others think they would be helpful and not cause any issues.

**Comment by iantaylor-NOAA** [comment]
These changes all make sense to me.
Thanks @k-doering-NOAA for improving the ignore files and taking a look at improving the tests to use `tempdir()` and write the output to that location as we just discussed.

**Comment by k-doering-NOAA** [comment]
Addressed in PR #368
