### ISSUE TITLE
reduce package dependencies

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#376]
The `mcmc.out` function includes a plot which uses the `hist2d` function from the `gplots` package and `gplots` depends on `caTools` which @k-doering-NOAA helpfully discovered has been recently updated and now depends on R version ≥ 3.6.0.

Asking all r4ss users to upgrade their R installation for the sake of a function that is probably almost never used doesn't make sense, so I just moved `gplots` from "Imports" to "Suggests" (in 13bffdbdf57d7ae2894ebaf1b1e1931a81c89a77) which means it won't get installed automatically, but have added a warning so that anyone trying to make that plot can be instructed to install `gplots`.

This change was easy enough that I went ahead and made similar changes to remove a few more dependencies (in commits 70017d7b75785e78a6b5228003593b68c8b3373e and 1964e70834e6865cc87fe078ddef1864fbc97c9d). 

Here's the list of things moved from "Imports" to "Suggests" which will no longer be installed automatically.
* `gplots`: only required for `hist2d` in a rarely-used MCMC plot created by `mcmc.out` (also see issue #25 for discussion of alternative MCMC diagnostics)
* `gtools` only used for the `running` function for running average plot in `mcmc.out` 
* `pso`: only used if you selected `altmethod = 'psoptim'` in `SS_fitbiasramp` to implement the alternative particle swarm optimization method
* `truncnorm`: only used for plotting fits if using the rarely-used truncated normal discard likelihood option in SS.

In all cases, you should get an informative error message if you try to run the function without the associated package being installed.

I haven't attempted to figure out how much faster this might make installation of the package, but at least the list of package offered for updates when you install r4ss via `remotes::install_github('r4ss/r4ss')` should go down (once these changes are merged into the `master` branch).

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA, do you think this issue is resolved? I know we looked a little bit more at dependencies in https://github.com/nmfs-fish-tools/SSMSE/issues/34 and my take home was that there isn't much more to remove.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA. 
The package dependency and installation issues continue to be a pain, but I don't see a good way to further reduce the packages that `r4ss` depends on without significantly impacting the functionality of the package. 

I'll close this issue now and we can rely on #25 to track any further work on removing links to those packages used by `mcmc.out()` if that is done in the future.
