### ISSUE TITLE
showmain = FALSE not supressing on SSplotSelex - dev branch

### ISSUE THREAD

**Issue by mkapur** [r4ss/r4ss#381]
Super minor, but I am working on the dev branch and noticed that the showmain=FALSE argument doesn't seem to actually supress the title. Not sure if this is something happening in dev or has been deprecated for a while and just not reflected in the man. I'm happy to take a look and/or do a pull request in the next few weeks unless it's something you're already aware of. I didn't yet test this functionality for the other plots.

**Comment by iantaylor-NOAA** [comment]
This option is definitely only partially implemented (in spite of having been identified in 2012 as noted in issue #6). It looks like `mainTitle = TRUE/FALSE` is the argument in most places other than `SSplotSelex` where is it `showmain` for no good reason that I can remember. Feel free to propose changes to functions that don't yet use this option.

**Comment by iantaylor-NOAA** [comment]
@mkapur thanks for long ago reporting this inconsistency in r4ss that I've just come across while cleaning up and labeling old issues. If you have any interest in working on this as you suggested, please say so and we can assign it to you. However, if you have other priorities (a lot has changed in 10 months), let me know and I'll assign it to myself.

**Comment by mkapur** [comment]
Hey Ian
Thanks for flagging this. I likely won't have the bandwidth to tackle this
anytime reasonably soon, so in the interest of efficiency you're welcome to
assign it to yourself!
Thanks and happy holidays.
MK

**Comment by iantaylor-NOAA** [comment]
I just sorted this out, hopefully, in commit 71d1d10 to `cleanup` branch, along with similar changes in additional commit to `SSplotTimeseries()` (all of this is part of longstanding issue #6).
The `showmain` input to `SSplotSelex()` is deprecated using `lifecycle::deprecated()` (thanks @k-doering-NOAA!) in favor of `mainTitle` used in other functions.
