### ISSUE TITLE
Recruitment Interval Incorrectly Calculated in SSsummarize

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#420]
User Alessandro Orio pointed out that the SSplotcomparison function is incorrectly plotting the uncertainty interval around recruitment a normally distributed.  The interval is calculated within the SSsummarize function and needs to be corrected.

**Comment by iantaylor-NOAA** [comment]
This is a duplication of issue #181 which somehow got lost in the shuffle. I promised to fix it in February 2018 and obviously failed to do so. I'll get it done right now.
