### ISSUE TITLE
support workflow of having SS executable in the path rather than directory with model files

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#429]
The SS User Manual notes workflow options under "Running SS", "Command Line Interface": "On all operating systems, a copy of the SS executable can either be located in the same directory as the model input files or in a central location and referenced either by adding it to the PATH or by a script files."

However, the `SSRunJitter()` and `SS_doRetro()` functions (and probably others too) only work with the executable in the same directory as the model input files.

It should be possible to modify the `check_model()` function to look for availability of `ss` in the path, such as by using a command like `system("where ss")` and then change all functions like `SS_doRetro()` to use `check_model()` (it is used by `SSRunJitter()` already).

**Comment by k-doering-NOAA** [comment]
I think from R, you can use
```r
bin_path <- Sys.which(bin_name)[[1]]
system(bin_path)
```
to find and run an executable called bin_name (for example, "ss") in the user's path.

Also, if the user is able to supply a relative (to the working directory) or absolute path to the executable, it should be possible to just include this path in the system call to run ss. For example, if the relative path to the wd is "./exe/ss.exe" running 
```
system("./exe/ss")
```
 should work.

These are a bit specific, but here are the [utility functions for running ss in SSMSE](https://github.com/nmfs-fish-tools/SSMSE/blob/master/R/runSS.R) (modified from the functions in ss3sim!) for more inspiration.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I left this open since I see you referenced it recently and gave it an `Epic` label! 🙌🏻 

Feel free to close if you don't need it, though.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I haven't taken the time to work all the way through a downstream function that uses `check_exe()` but what happens if I have an exe in the directory and in my path and I do NOT want to use the one in the path?

**Comment by iantaylor-NOAA** [comment]
Good catch @kellijohnson-NOAA. I have the logic backwards in the function.

"Windows always looks in the current directory first before searching the path" (from [here](https://stackoverflow.com/questions/23455637/in-windows-cmd-how-do-i-run-an-executable-in-the-current-directory-instead-of)).

Therefore, I think check_exe() should check the current directory first, and then the PATH. For Mac and Linux users, the addition of "./" controls whether the local version is run or the one in the path, but I think it would be a bad idea to have a local executable but run the exe in the PATH instead, so I don't see value in adding an option to exclude the "./" if a local file is found. Folks on all operating systems could still force the PATH version to run in place of the local file if they really want by specifying the full path to the exe in the PATH (e.g. `exe = "c:/ss/ss_v3.30.19.01/ss`).

**Comment by iantaylor-NOAA** [comment]
I think I've succeeded in cleaning up the logic in `check_exe()` so that it behaves as we would wish: returns local directory first (with "./" added on Linux or Mac), then checks PATH if not found locally, then error if not found in either place.
I've expanded the documentation a bit as well.
