### ISSUE TITLE
Add weight_comps function from ss3sim into r4ss

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#433]
The [ss3sim weight_comps function](https://github.com/ss3sim/ss3sim/blob/master/R/weight_comps.R) runs models automatically with Francis, MacAllister-Ianelli, or Dirichlet Multinomial  weighting options. It has use for running models with different weighting routines outside of ss3sim, so  it makes sense to migrate it into r4ss.

Some changes to the ss3sim function will be necessary to do this:
- [x] use the r4ss function `run_ss_models` instead of the ss3sim function for running models
- [x] Make sure bias adjustment and running without the hessian options remain available. This is needed for ss3sim, but may be less important for other users.

This could be added as a new function or perhaps integrated into the existing `SS_tune_comps` (which currently gets the weights for francis and MacAllister-Ianelli iterative weighting options, but does not include options to automate rerunning the models or options for the Dirichlet Multinomial.

**Comment by k-doering-NOAA** [comment]
I've started a new branch https://github.com/r4ss/r4ss/tree/issue-433 to start incorporating ss3sim::weight_comps into r4ss::SS_tune_comps to extend the capabilities of SS_tune_comps to run models and change the model to have DM parameters. It still needs testing. @kellijohnson-NOAA , @iantaylor-NOAA  and @chantelwetzel-noaa (or anyone else who would like!), feel free to take a look if you have time and let me know if you think this isn't going in the direction you imagined.

**Comment by k-doering-NOAA** [comment]
Some potential fixes/additions:
- [ ] If running DM after running Francis or MI, remove the iterative weights from the model.
- [ ] Check that "none" is working as expected
- [ ] Add option to run tuning models in new folders
- [ ] For output, add a summary of tunings used over iterations and maybe option for a plot to help visualize
- [ ] Threshold approach for determining number of iterations to tune? (for example, change in biomass is less than 5%?
- [ ] Make sure this function is still compatible with the other r4ss functions that call it.
- [ ] Make sure it is compatible with ss3sim

**Comment by kellijohnson-NOAA** [comment]
Isn't there an r4ss function that will copy the model over to a new function? I don't think it is too much to ask people to run that function by themselves before they call SS_tune_comps.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, this seems like a good list of fixes/additions, but none are essential for what you've done to be useful.
From what I can tell, the only function that calls SS_tune_comps() is SS_varadjust() which I think can be now deprecated as the functionality it provided.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA for making all the improvements in PR #439. 
This will make tuning composition data in any model using any or all of the three available methods much easier.

I'm happy to have you close this issue or leave open to keep track of the potential fixes/additions you listed in this https://github.com/r4ss/r4ss/issues/433#issuecomment-718230000 above.

**Comment by k-doering-NOAA** [comment]
Closing this issue, the SS_tune_comps that can automatically do data weighting routines works, including with ss3sim. There still are some improvements that could be made (see unchecked boxes on this issue), but I think those can be developed in future as needed by r4ss users.
