### ISSUE TITLE
replist$M_at_age returns characters

### ISSUE THREAD

**Issue by quang-huynh** [r4ss/r4ss#435]
SS_output returns values in replist$M_at_age as characters instead of numeric. Minor but this was quite a cryptic issue when I try to calculate F from Z_at_age - M_at_age.

**Comment by iantaylor-NOAA** [comment]
Thanks @quang-huynh for reporting this and sorry for the annoyance.
It seems to have been caused by a sloppy copy-paste from code above. Now fixed in commit dac0ba6 to the development branch: `remotes::install_github("r4ss/r4ss@development")`

**Comment by quang-huynh** [comment]
Great thanks for the quick turnaround!
