### ISSUE TITLE
processing initial F parameters in SS_readctl_3.30()

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#438]
The `stop()` on these lines doesn't seem to work well when running SS_readctl() using default inputs because `N_rows_equil_catch = 0` so it gets skipped:
https://github.com/r4ss/r4ss/blob/development/R/SS_readctl_3.30.R#L778-L785
This leads to the error `Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length` when the Q_setup table gets read incorrectly.

@k-doering-NOAA do you have ideas on how best to at least improve the error/warning?

**Comment by k-doering-NOAA** [comment]
This is a tricky one.  Maybe  this could be a warning (as opposed to stop) regardless of the value of `N_rows_equil_catch`, if `use_datlist = FALSE`? This would mean you may get the same strange error, but a potentially more helpful warning message.

I wonder if `N_rows_equil_catch = NULL` should be a valid option and the default. In this case, SS_readctl_3.30 will attempt to figure out the equilibrium catch inputs automatically if `use_datlist = FALSE`:

1. use keywords in the original file's comments to find the equilibrium catch vals
2. if any are found, see if they match with the expected next inputs
3. If they don't match, the SS_readctl_3.30 errors; if they do, then they can be read in.

Another route we could go is require a datafile always when using `SS_readctl` ( or at least `SS_readctl_3.30`) - however, I could see how it may be useful to be able to read in a ctl file without a data file by specifying the necessary values.

**Comment by iantaylor-NOAA** [comment]
Thanks for the input on this, @k-doering-NOAA.
I like `N_rows_equil_catch = NULL` and an attempt to figure out how many initial F parameters there are. I'm no longer in touch with what approaches are being used in `SS_readctl_3.30`, but a few indications (none perfectly reliable) that the model contains initial F parameters are 

- a line like `#_initial_F_parms; count = 2`
- 7 numerical values on at least one row between the `F_Method` input and `Q_setup`.
- numerical values followed by a comment (parameter label) that begins "InitF"

I like the idea of a test using something like one of the above, even if imperfect, before providing a warning and/or attempting to parse the lines appropriately. If a warning was displayed every time `use_datlist = FALSE` I think it would get routinely ignored, even for those situations where it was useful.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA I added this functionality in d47ae7d , just looking for the line `#_initial_F_parms; count = 2` if `N_rows_equil_catch = NULL` (now the default) . Let me know if you see any improvements. [This test](https://github.com/r4ss/r4ss/blob/ncpue/tests/testthat/test-control.R#L47-L56) can be used to see the new functionality for a model with no equilibrium catch (also, the bocaccio model has equil catch if you want to test it out with equil catch).

I ended up not doing these steps, because I felt like it was overkill:

2. if any are found, see if they match with the expected next inputs
3. If they don't match, the SS_readctl_3.30 errors; if they do, then they can be read in.

The function will stop on error if it can't read in a value from the `initial_F_parms` line, and I thought it seemed reasonable to ask the user to specify this value if that is the case.

**Comment by iantaylor-NOAA** [comment]
Looks good. Thank you @k-doering-NOAA.

I tested on a model with initial equilibrium F where I happened not to have updated from the "#_initial_F_parms; count = 0" and that didn't work. Rather than try to improve the detection, I just added a warning that should be triggered whenever the initial F parameters are read as if they were Q options. Updating the count got the model working fine.

Note that these changes are all in the `ncpue` branch so maybe we should leave this issue open until that gets merged.

**Comment by k-doering-NOAA** [comment]
Thanks for testing and adding this other check, it seems like a good enough solution to me for now.  I will open a PR to merge in the ncpue branch.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I should have mentioned, I think your addition of the error is a great idea! Just thinking that maybe in the future we will think of something that will work more reliably, but we need not worry about that now :)

**Comment by iantaylor-NOAA** [comment]
Fixes in Pull Request #440 from @k-doering-NOAA resolve this issue.
