### ISSUE TITLE
wrapper function to call SS_output, then SS_plots?

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#449]
It occurred to me today that I am constantly calling SS_output, then SS_plots, just in the R console, to check results of a model run. I personally prefer to turn off all the verbose output, which makes the call a little more complicated and I often forget which variables to specify in order to turn off all output to the console.

I wonder whether it is worth having even a higher level wrapper function within the r4ss package to create  plots from SS model files? Something simple like:
```r
run_SS_plots <- function(dir) {
  r4ss::SS_plots(r4ss::SS_output(dir = dir, verbose  = FALSE, printstats = F,
                                 hidewarn = TRUE), verbose = FALSE)
}
```
Although maybe there should a `verbose` = T/F option as well? This would save a bit on typing. 

I'm curious if other people would find this useful? I'm also curious about how other people typically use SS_output then SS_plots. For example, do you always call them together, or do you often inspect the returned object from SS_output somehow? Would this sort of function even be useful for your workflow, or is there some way it could be modified to be more useful?

Please feel free to comment on this and provide details about how you typically call these functions!

**Comment by kellijohnson-NOAA** [comment]
What about just adding an argument to SS_plots() that provides a model directory, and if !missing(dir_model) {SS_output()}?

**Comment by k-doering-NOAA** [comment]
I guess that could work, too! Or I wonder if the `replist` is a string (a path to the model dir) instead of a list, `SS_output` could be called? This would avoid adding a new argument, but it may not be intuitive that replist could be either a list object or a string...

This does seem a good solution because it would avoid creating a new function while still reducing typing for calling the plots.

In addition, it would be helpful if verbosity was controlled with just 1 variable. There are currently 3 variables that determine if output is written to the console or not. I'm no sure if the solution is try to deprecate 2 of these switches, make a new variable to be the main switch for verbosity, or if verbose should be changed to be a main switch?

**Comment by kellijohnson-NOAA** [comment]
when you read in SS_output()$inputs$dir is the directory location, so you could just make a check in SS_plots() to see if the rest of the list is empty and if it is, then read it in using 
```
# power users could call this
SS_plots(replist = list(inputs = list(dir = getwd()))
# this line would go in SS_plots after an if statement
replist <- SS_output(replist$inputs$dir)
```
this could just be a behind the scenes thing that would only minorly need to be documented.

**Comment by k-doering-NOAA** [comment]
I think I would prefer to call something more like
```r
SS_plots(replist = "path/to/my/model", verbose = FALSE)
```
I think the main problem is it is hard to remember so many function and variable names, and I don't think I would remember to call something like `replist = list(inputs =list(dir = getwd()))` without looking at the help file... it also isn't much less typing than 
```r
r4ss::SS_plots(r4ss::SS_output(dir = dir, verbose  = FALSE, printstats = F,
                                 hidewarn = TRUE), verbose = FALSE)
```

@kellijohnson-NOAA what is your workflow for calling SS_plots when you are developing models? Are you typing it directly into the R console, via the command line, or in a script? And do you bother turning off verbosity?

**Comment by kellijohnson-NOAA** [comment]
When I am developing a production stock assessment model, I normally don't call SS_plots() b/c it takes too long and I don't like how the html automatically opens. Instead, I target a single plot based on whatever parameters I am working on. With ss3sim, I just plot the time series using ggplot(). I hardly ever call R using the command line, most of the time I just have sublime and send things to R.

**Comment by iantaylor-NOAA** [comment]
Thanks for all the ideas. I've thought about this as well and don't have a great solution. One issue that I run into is that I usually want access to the object returned by `SS_output()`, so running the functions separately allows me to choose a different name for each run. I think it would be reasonable to have `SS_plots()` test for whether the `replist` input is a directory or a list created by `SS_output()` and act accordingly.

For the 2019 Big Skate assessment, I created a custom `getbs()` function to solve these problems: https://github.com/iantaylor-NOAA/BigSkate_Doc/blob/master/R/BigSkate_functions.R#L1-L31.
The command `getbs(101)` runs `SS_output()` looking for a directory within my hardwired master directory that starts with the name `bigskate101`. By default it just prints the messages like the following:
```
reading model from: bigskate101_DMtuning_new_prior_98perc
creating bs101
```
where `bs101` is the output from `SS_output()` that gets assigned to the workspace. Any subset of the plots can be created as well via something like `getbs(101, plot = 3)` which adds the additional step of making the time-series plots (group 3).

I will happily write a similar custom-built function for any future production assessment where I'm running lots of models and encourage any experienced user to create a one for themselves. If there's a good way to generalize this approach, I fully support that, but I worry the benefit of this function would be lost in trying to generalize it too much (such as for any naming convention).

@kellijohnson-NOAA, your ggplot solution seems great, but if you need it in the future, the argument `openfile = FALSE` can be used in `SS_plots()` to avoid opening the HTML view automatically (it is passed to `SS_html()` via the `...`).

**Comment by k-doering-NOAA** [comment]
Interesting, it sounds like even just between the 3 of us there are different ways of using the functions. Maybe I'll let this issue sit a bit (since it is a Friday) and see if anyone else has thoughts they want to add about their workflow and the usefulness or not of having a more streamlined call to get all the plots from r4ss.

**Comment by k-doering-NOAA** [comment]
closing this issue, since it wasn't clear this would benefit anyone besides me - and really, the gains would only be slight (avoid typing a few characters)
