### ISSUE TITLE
expand vignette to include commonly used r4ss functions

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#459]
It is hard to keep up with development in r4ss. In order to better illustrate the range of functions available, more examples of commonly called functions should be included in the [vignette](https://r4ss.github.io/r4ss/vignettes/r4ss-intro-vignette.html). Note that this is the [source rmarkdown file](https://github.com/r4ss/r4ss/blob/development/vignettes/r4ss-intro-vignette.Rmd).

Aspects that should be covered are:

- [x] Functions for automating common assessment tasks, like `SS_doRetro`, `SS_run_jitter`, and `SS_tune_comps` 
- [x] Utility functions (if not already referenced), like `copy_SS_inputs` and `copy_multiple_folders`
- [x] How to call individual plots for r4ss (just a general overview should be sufficient)

Have other thoughts? Please post them here! I assigned myself to work on this for now, but it would be great to have help or input from others on what to include.

**Comment by k-doering-NOAA** [comment]
In progress in update_vignette branch. Next steps:
- [ ] Ian read for grammar/correct function use
- [ ] KD check that renders correctly
- [ ] KD add new rendered version to github pages
- [ ] merge into development

**Comment by iantaylor-NOAA** [comment]
Looks good @k-doering-NOAA. I made minor changes in commit 74a796028f58c0532ac8f07996136934d3b36c98. 

Among other things, I looked up the original Thorson et al. (2016) paper and see they use the term "Dirichlet-multinomial" so I added hyphens and adjusted capitalization to match that throughout this vignette. We could expand that to the rest of the package someday.
