### ISSUE TITLE
SS_changepars output

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#46]
It would be nice if ```cat``` statements were only printed when ```verbose = TRUE```. It really only pertains to situations when using ```SS_changepars``` inside other functions, such as within ```ss3sim```. If the change is fine with you and you add me as a collaborator I am happy to change it.

**Comment by taylori** [comment]
`SS_changepars` modified here https://github.com/r4ss/r4ss/commit/759e9528d91e0f2d03152a4350137d25692028be
to make verbose work as it should.
