### ISSUE TITLE
create a single function for running SS models for use in r4ss, SSMSE, and ss3sim

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#460]
While discussing issues #430 and #456, @k-doering-NOAA and I realized that not only are there numerous inconsistent approaches within r4ss for running SS models, there are redundancies across packages with 
[runSS](https://github.com/nmfs-fish-tools/SSMSE/blob/main/R/runSS.R) in SSMSE, [run_ss3model](https://github.com/ss3sim/ss3sim/blob/master/R/run_ss3model.r) in ss3sim, and [run_SS_models](https://github.com/r4ss/r4ss/blob/development/R/run_SS_models.R) in r4ss.

It would be great to replace all these with a single function which could do the following:
- deal with exe in path, local directory, or directory provided (as noted in #429)
- add "./" for Mac and Linux systems but only when the executable is not in the path
- display the console output or save it to a file depending on what the user wants
- use `system2()` (as noted in #456)
- be useful for all the functions in r4ss that run SS (as noted in #430)
- be useful for all the needs of SSMSE and ss3sim
- have a short name (I like "runSS" best) and allow users to simply call `runSS()` to run SS within the working directory without additional input
- any other features that anyone adds to this issue

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, thanks for the cleanup to use `show_in_console` throughout the functions that call the executable in commit https://github.com/r4ss/r4ss/commit/0c55d6daf435bc0b201e3b2cc3b45020f663ceb9.
Do you think it's still worth pursuing the shift proposed in this issue to using `run_SS_models()` (or equivalent) in all of those functions?

I think the first three bullets in the original post are already included in that function. We would still need to change to `system2()`.
I like the idea of shortening the name as suggested by @kellijohnson-NOAA, maybe down to just `r4ss::run()`?

**Comment by iantaylor-NOAA** [comment]
Update: I made some progress on this in the [system2_issue456](https://github.com/r4ss/r4ss/tree/system2_issue456) branch (where I was associating the commits with related issue #456). There's still more work to do, especially testing all the changes I've made so far, but it's satisfying to see how much duplicate code can be removed (e.g. about 1/3 of SS_doRetro() [went away](https://github.com/r4ss/r4ss/commit/89bb47ead369d13a7003d03f10c49e2f815ddf65#diff-c3483e7a05e48b3a835217b3f86415f787d27d8b58a2b4a267641e2ea4b6c3c7)).

I'm trying to make use of `copy_SS_inputs()` as well as `run()` for stuff that repeated both of those things because those functions didn't exist at the time the code was written.

**Comment by yukio-takeuchi** [comment]
@iantaylor-NOAA 

Though it would be main focus of this work,
as for Linux and Mac, "~" can be very useful

**Comment by yukio-takeuchi** [comment]
Sorry I sent incomplete comments.

If exe_in_path is T, I would like to ask to consider  to insert a following pice of code before Sys.which is applied to exe

```
if (exe != basename(exe))
 exe <- normalizePath(exe)
```

This intends to make the results of Sys.which more consistent with which command in shell on Linux or Mac.

System which command conduct "~" expansion before search of exe is conducted. On the other hand Sys.which in R quotes its arguments before search is conducted. This behavior of Sys.which cause a trouble if e.g, ~/bin/ss_3.30.19/ss is given to the argument exe, while system which can find ss if ~/bin is in PATH. 

I hesitated to propose it as "~" expansion by normalizePath may not be so useful in windows, due to the fact that ~ in R on windows points to $R_HOME.

**Comment by iantaylor-NOAA** [comment]
Hi @yukio-takeuchi, 
Thanks for the suggestion. I just pushed 9d41ef5 which I think does what you want. On my Windows computer, I have a HOME environmental variable set as `C:\~` which causes `normalizePath()` to work similarly for me. I haven't actually tested that with this modified function in the way you describe but will do so soon. I wouldn't worry about Windows users entering an exe input in that notation if they don't know it will work. Let me know if this change looks OK.
-Ian

**Comment by yukio-takeuchi** [comment]
Hi @iantaylor-NOAA 

Thank you so much to include my suggestion.
I suspect, this insertion may only be benefit for very limited number of "shell" enthusiastic persons. 
But certainly it helps me a lot.  
After small number of tests on linux, I realized that ``normalizePath`` function returns warning if the file given as an argument was not found. if an additional argument ``mustWork = FALSE`` is given, normalizePath will not produce warning message with ``""`` as return value.
If such an additional warning is not wanted, please add an additional arugument ``mustWork = FALSE`` to normalizePath.

**Comment by iantaylor-NOAA** [comment]
Thanks @yukio-takeuchi, that seems reasonable to me, so I pushed the change in b3a4ac2a9de03a61732203c1f2f70ad460771b22.

I just tested on my Windows computer by adding "~\bin" to my path, putting an executable within a subfolder in there and running with both `mustWork = TRUE` and `mustWork = FALSE` in the function. I get the same warning either way when the input to `exe` doesn't work.

Successful example:
```
> run(dir = "inst/extdata/simple_3.30.13", exe = "~/bin/ss_3.30.19.01/ss", skipfinished = FALSE, verbose = TRUE)
Assuming path to the exe is provided in the input 'exe'
changing working directory to inst/extdata/simple_3.30.13
Running model in directory: C:/github/r4ss/inst/extdata/simple_3.30.13
Using the command: C:\~\bin\ss_3.30.19.01\ss.exe -stopph 0 -nohess    
 reading from starter.ss
...
```

Failure example:
```
r$> run(dir = "inst/extdata/simple_3.30.13", exe = "~/bin/ss_3.30.19.01/wrong", skipfinished = FALSE, verbose = TRUE, extras = "-stopph 0 -no 
    hess")
Assuming executable is in each dir folder, but missing from some folders
changing working directory to inst/extdata/simple_3.30.13
Running model in directory: C:/github/r4ss/inst/extdata/simple_3.30.13
Using the command: ~/bin/ss_3.30.19.01/wrong.exe -stopph 0 -nohess    
                          dir          results
1 inst/extdata/simple_3.30.13 model run failed
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="c:\~/bin/ss_3.30.19.01/wrong.exe": The system cannot find the file specified
2: In system2(command, args = extras, stdout = ifelse(show_in_console,  :
  '"~/bin/ss_3.30.19.01/wrong.exe"' not found
```
So I see no harm in adding `mustWork = FALSE` if it helps you avoid an unnecessary warning on linux.

@k-doering-NOAA, I see you've used `normalizePath(..., mustWork = TRUE)` in the vignette but not in the `run()` function (a.k.a. `run_SS_model()` outside of this branch). Please chime in if you have any concerns about this change or suggestions for further revisions.

**Comment by yukio-takeuchi** [comment]
@iantaylor-NOAA 


Thank you for testing for my additional suggestion.
As for mustWork in normalizePath, 
The default is NA, which throws a warning and returns ~expanded path if file is not found in ~expanded path. If mustWork is TRUE, error will be thrown instead of warning and stop execution. If mustWork is FALSE, normalizePath will be quiet and just return ~expanded path. 
To me, any one of three can be acceptable. I will follow your decision

**Comment by iantaylor-NOAA** [comment]
New issues opened in other repos: https://github.com/ss3sim/ss3sim/issues/385, https://github.com/nmfs-fish-tools/SSMSE/issues/140, and also https://github.com/nwfsc-assess/nwfscDiag/issues/18, so closing this one.

If the implementation of these changes in r4ss creates any problem for the other packages, please feel free to re-open this issue or create a new one.
