### ISSUE TITLE
troubleshoot run-tests-with-SS job

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#461]
PR #455 breaks this github actions test by adding additional dependencies to r4ss; for some reason, the run-tests-with-ss github action job fails because devtools::test() cannot find all the package dependencies. This was already happening for the kableExtra pkg, and also seems to be a problem for stringr.

This can be fixed temporarily be moving stringr from depends to suggests just for this job, but perhaps there is a better solution.

**Comment by kellijohnson-NOAA** [comment]
I had the same thing happen in sa4ss where some packages are not available for all platforms, which was surprising to me. At least this is what I think is going on because when I changed to a different operating system the test passed.

**Comment by k-doering-NOAA** [comment]
That is interesting, thanks for sharing! I'm not sure this is true for the other packages in the run, but for kableExtra, the strange thing is I can see that it downloads earlier in the run, but then it can't be found by devtools::test(). But maybe trying out a different OS would solve the issue, thanks for the suggestion!

**Comment by k-doering-NOAA** [comment]
Ended up going with the same solution as for kableExtra, by moving stringr from imports to suggests in the DESCRIPTION file at the beginning of the job. This works fine because neither of these packages are needed for the tests in this job.
