### ISSUE TITLE
SS_writedat_3.30  prints terminator  line (line starting from  -9999) for each method of generalized comps  while SS seems not to require it

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#465]
For printing out generalized size composition.
SS_writedat_3.30 prints terminator line for each method.

```
lapply(d[["sizefreq_data_list"]], print.df)
```

It seems that SS does not need terminator line for generalized size composition.
Changing above code to 
```
lapply(d[["sizefreq_data_list"]], print.df, terminate = FALSE)
```
seems to be able to avoid execution error.

**Comment by k-doering-NOAA** [comment]
Thanks for reporting this @yukio-takeuchi! I pushed a commit (a34b791) to the development branch that uses the fix you proposed.
