### ISSUE TITLE
SSplotMovementRates overwrites png files if multi-season, movement model is used

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#468]
Even If multi-season model is used and if movement occur in multiple season, SSplotMovementRates uses same file name for png so that only the plot for the last season is kept.  The following change for SS-lotMovementRates.r resolved the problem to my case.

Cheers,

```r
❯ git diff R/SSplotMovementRates.R
diff --git a/R/SSplotMovementRates.R b/R/SSplotMovementRates.R
index 3010857..188b7ac 100644
--- a/R/SSplotMovementRates.R
+++ b/R/SSplotMovementRates.R
@@ -109,7 +109,8 @@ SSplotMovementRates <-
           }
           if (plot) move.endyr.fn()
           if (print) {
-            file <- "move1_movement_rates.png"
+            #file <- "move1_movement_rates.png"
+            file <- paste0("move1_movement_rates_seas", moveseas[iseas], ".png")
             caption <- main
             plotinfo <- pngfun(file = file, caption = caption)
             move.endyr.fn()
```

**Comment by k-doering-NOAA** [comment]
Thanks @yukio-takeuchi, for finding all these bugs and reporting them!

Would you mind submitting this as a pull request to the development branch (even though it is a small change)? That way, you can get credit for the changes you make via commits and the proposed fixes will get tested with the github actions set up. If you prefer to just keep reporting via issues, though, that works, just thought I would mention there is another option! Let us know which way you prefer :)

**Comment by iantaylor-NOAA** [comment]
Changes made in commit 67c90b396d4a7f11883f276770d38b60bf10ed63 by @yukio-takeuchi (discussed in #467) sort this out.
Thanks @yukio-takeuchi. Go ahead and close the issue if you're satisfied.
