### ISSUE TITLE
convert function documentation to markdown

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#470]
As discussed on #469, markdown makes for easier-to-read function documentation.

In commit d4ecca647ebaa3ae96d82ae3c4e33b8e91cb87f6 to the new `roxygen2md` branch tried applying `roxygen2md::roxygen2md(scope='full')` (discussed at https://github.com/r-lib/roxygen2md) to convert all the existing roxygen2 comments to markdown. This mostly worked well except in cases where there were mathematical expressions or example code in the documentation. Most of those were easy to fix, often by wrapping the expression in \` marks, but there were a few cases that were hard.

- [ ] In SSplotSelex.R, converting `*` to `\*` didn't work to actually get `*` still resulted in `\emph{}` in the result (where the `\` worked well for other symbols elsewhere). See https://github.com/r4ss/r4ss/commit/d4ecca647ebaa3ae96d82ae3c4e33b8e91cb87f6#diff-36fc42f8aef077e6bd871a9009b2e48f442cf84d5b61815846fe8d6405c00a31R75-R76.
- [x] rm_dollar_sign.R includes examples of complex syntax which I'm not sure how to convert to markdown (see https://github.com/r4ss/r4ss/commit/d4ecca647ebaa3ae96d82ae3c4e33b8e91cb87f6#diff-118feabdc1edd0b6cdf69d0378c7e2b5cc146cf3ff580ffa61d5c17ea3cf8863R36). @k-doering-NOAA, maybe you can take a look at that one.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA I tried to fix this, but couldn't find a way to escape backticks, so in the end, I removed the example that wasn't showing up properly.

It looks like using markdown in r documentation is pretty new, I wonder if we can report these escaping issues somewhere? Maybe they are bugs?

**Comment by k-doering-NOAA** [comment]
Also note that while there aren't any error, R CMD CHECK caught some warnings and notes: https://github.com/r4ss/r4ss/runs/1750800364#step:9:301
