### ISSUE TITLE
SSplotsTimeseries does not work properly for multi-area model on subplot=11(sum total recruitment across birth seasons) 

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#471]
If there is more than 1 area, the following piece of code  around lines 280 of SSplotsTimeseries.r
```r
          for (y in ts[["Yr"]]) {
            yvals[ts[["Yr"]] == y & ts[["Seas"]] == 1] <- sum(yvals[ts[["Yr"]] == y], na.rm = TRUE)
            yvals[ts[["Yr"]] == y & ts[["Seas"]] > 1] <- 0
          }
```
repeatedly accumulate recruit of same year.
Following quick fix
```r
      for (y in ts[["Yr"]]) {
            yvals[ts[["Yr"]] == y & ts[["Seas"]] == 1 & ts[["Area"]] ==1] <- sum(yvals[ts[["Yr"]] == y], na.rm = TRUE)
            yvals[ts[["Yr"]] == y & (ts[["Seas"]] > 1 | ts[["Area"]] > 1)] <- 0
       }
```
seems working for my 8 areas model. 
But I do not know if this fix can works in general.
Also I do knot know if similar problem is happening for total, summary biomass or spawning output for multi-area model. I need to check one by one.

**Comment by iantaylor-NOAA** [comment]
Hi @yukio-takeuchi, 
Thanks for continuing to debug the plots associated with spatial and seasonal models. 

Your change looks good to me. As you figured out, the section you're improving is a clunky bit of code which replaces the recruitment in season 1 (and now also area 1) with the sum across all seasons (and now areas) and zeros out the other lines to facilitate showing the total in the plot. There's surely a more elegant approach in general, but that's a task for another day.

Could you try pushing this change to a fork of the repository and issuing a pull request? As with your previous suggestion, it wouldn't be hard for someone else to just adopt this change, but I think it will be useful to get used to the fork/PR workflow. As noted in issue #473, it shouldn't be possible to accidentally push to the main repository.

**Comment by iantaylor-NOAA** [comment]
Closing the issue because this change was added in commit 311ffb20c1baba3c34b8cb1f2be85d260f669ecb. Thanks @yukio-takeuchi.
