### ISSUE TITLE
Run_time in SS_output

### ISSUE THREAD

**Issue by allanhicks** [r4ss/r4ss#49]
The list from SS_output sets Run-time and repfiletime as the same, and they are both taken from the same line in the Report file.  It seems to me that Run_time should be the time it took to minimize (two lines below the Start Time in the header of the Report file).  I hesitate to change this in case this was intended. If so, it would be nice to have the time to minimize as output.  

A simple change to line 700 would do it:
stats$Run_time <- paste(as.character(matchfun2("StartTime",2,"StartTime",2,cols=4:9)),collapse=" ")

**Comment by taylori** [comment]
Haven't tested change by @awhitten but change is straightforward and makes lots of sense.
Thanks.

**Comment by taylori** [comment]
Thanks to @melmonk for noticing vestigial Run_time occurrence in SS_html. Reopening issue and will add fix and then close again.

**Comment by taylori** [comment]
I said I would reopen, fix, and then close this issue. I seem to have made the fix but failed to close. Closing now.
