### ISSUE TITLE
start using master branch routinely or get rid of parallel master and development branches?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#496]
The intention was to use of the `development` branch as a more active place to push small changes and merge pull requests which would then be periodically merged into a more stable `master` branch. However, that hasn't been the practice and `master` has languished with all users typically installing `development` to avoid bugs and get the latest features.

I might be better at merging `development` into `master` if we agreed on a schedule of weekly or monthly merging of whatever parts of development have been adequately tested. Does that seem useful or would it just add unnecessary complexity?

Also, the version on CRAN needs to be updated or pulled down (see #206).

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for seeking feedback prior to initiating action. I believe that many people still use CRAN to download packages because of the ease of install compared to github actions. Even for myself, I regularly install CRAN versions of things rather than github because 
* I don't have to type as much
* an automatic list will come up for me if I cannot think of the exact name on the fly
* people don't have to think about when the token / download limits arise and you don't know how to set permissions, 
* internet may not be readily available and packages are passed around on thumb drives
Additionally, CRAN increases searchability because many places on the internet list all packages that are available on CRAN. Therefore I would like to see r4ss updated more regularly and keep the master branch in line with CRAN. I need to be better about this with ss3sim too. I am open to other ideas though too.

**Comment by iantaylor-NOAA** [comment]
Thanks for the feedback @kellijohnson-NOAA (comment above) and @k-doering-NOAA (verbally).

Here's a proposed workflow and release plan going forward.
- Replace the combination of `development` and `master` with a single `main` branch which gets installed via `remotes::install_github("r4ss/r4ss")`
  - The continuous development of the development branch has been more reliable than in the past thanks to automated testing of every r4ss commit via GitHub Actions and frequent automated testing of `SS_output()` and `SS_plots()` on a set of 29 example models, eliminating the need for a separate development branch which in the past was less stable.
  - There are now only five of us have direct access to push to these branch in order to make sure less frequent contributors don't accidentally push to the main repo instead of their own forks, further reducing the danger of untested changes.
  - The five of us are increasingly using feature branches which get tested before merging.
  - Changes which can be completed in a single commit and/or aren't expected to substantially impact the code can continue to get pushed directly to `main`, but anything more complex, or more important to make visible to those watching this repository should go through pull requests, even if the person making the commits merges their own pull request.
  - Increasing the coverage of our tests (currently at 49%) would further improve things.

- Submit a new r4ss release to CRAN in association with each new SS release (e.g. 3.30.16.00, but not 3.30.16.01).
  - Having r4ss on CRAN has all the benefits that @kellijohnson-NOAA just noted in the previous comment
  - This frequency shouldn't be a burden
  - Testing procedures SS and r4ss are now robust enough that there shouldn't be too many bugs found immediately after users start making use of the new release
  - These releases would also be added to https://github.com/r4ss/r4ss/releases

Anyone should free to suggest changes to this as you wish.

Once we settle on a plan, we can update https://github.com/r4ss/r4ss/wiki/Git-Workflow and get to work on reworking branches and/or submitting to CRAN.

**Comment by k-doering-NOAA** [comment]
This plan sounds good to me.

 Maybe on the readme or some other visible place, instructions on how to download the current version on cran from github could be included, since the master/main branch would no longer mirror it.  For example, to download the latest cran version, the call is `remotes::install_github("r4ss/r4ss@v1.38.0")`.

**Comment by iantaylor-NOAA** [comment]
The `development` branch is now named `main`

According to the github message, if you have a local clone, you can update it by running:
```
git branch -m development main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
However, I made the change in GitKraken instead.

I also renamed `master` to `development` after bringing it into sync with the old `development` (now `main`), so that folks who have been trained to use `devtools::install_github("r4ss/r4ss", ref = "development")` or similar will have a grace period in which that will still work. Perhaps this will lead to some conflicts between old development and new development, but hopefully they can be worked out without too much pain.

Commit 414f60b88f404a92eb7eab323c6cc580798565ea revises the README to recommend installing via `devtools::install_github("r4ss/r4ss")` to get the main branch.

**Comment by k-doering-NOAA** [comment]
Thanks, @iantaylor-NOAA, I think this will simplify r4ss workflows a lot!

I was able to update my local clone using the github commands recommended, but then found I also needed to run

```
git fetch
git merge --ff-only
```
while on the main branch in order to get all the latest changes.

**Comment by iantaylor-NOAA** [comment]
As noted in the comment https://github.com/r4ss/r4ss/issues/496#issuecomment-812240244 from 1 April, the `development` branch was kept around even after focusing development on `main` going forward to allow a transition for folks who have been in the habit of updating from `development` could transition to the new approach.

As part of some cleanup associated with upcoming release of Stock Synthesis version 3.30.17, I just deleted the `development` branch. Unless you're looking for a specific branch, all installation of r4ss should be done via `remotes::install_github("r4ss/r4ss")` as discussed on the r4ss README: https://github.com/r4ss/r4ss/#installation
