### ISSUE TITLE
readdat fails at loading agecomp

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#499]
Updated r4ss from github and SS_readdat_3.30 fails on this file

https://github.com/iotcwpm/ALB/blob/main/OM/data/PSLFwt/CPUE_SouthWest/abt.dat

Error is in line  521

```
zero_agecomp <- apply(datlist[["agecomp"]][,-(1:9)], MARGIN = 1, FUN = sum) == 0
```

as datlist$agecomp is NULL from line 499

```
datlist[["agecomp"]] <- get.df(dat, ind)
```
If I go back to 308c23236fbcecca53984cf356f4291c0aaea10f it works.

**Comment by k-doering-NOAA** [comment]
Thanks for reporting @iagomosqueira. A check was added in 9625ad0 and f06c1c8 to warn the user if there were any lines of data with all zeros (see #494 ), but unfortunately we forgot to account for the scenario when there is no agecomp data being read. I think 9f023d8 should fix this, could you test and let me know?

**Comment by iagomosqueira** [comment]
Yes, that works now,. Many thanks.
