### ISSUE TITLE
Move sensitivity_plot_issue_200 into development branch

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#507]
The sensitivity_plot_issue_200 adds functionality inside r4ss to create Jason Cope's relative change in quantities of interest for sensitivities.  It would be helpful to have this incorporated in the development branch for testing of application for this year's assessments.

**Comment by iantaylor-NOAA** [comment]
Thanks for the reminder @chantelwetzel-noaa. Please report any issues you have with this plot.
