### ISSUE TITLE
Change column headers within r4ss read/write functions

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#512]
Thanks to Ian for suggesting this. I am splitting this off into a new issue.

3. I would change the column headers throughout. Even if it requires some modification to dependent code, I think the mismatch  from what's in the function inputs and the .ss_new files is confusing.

Related to number 3, it occurs to me that we could consider a refresh to all the column headers to match those used throughout data.ss_new: `yr month fleet sex part Nsamp` (from https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_write_ssnew.tpl#L191) as opposed to the `r4ss::SS_writedat()` headers, which are currently `Yr Seas FltSvy Gender Part Nsamp` (from https://github.com/r4ss/r4ss/blob/main/R/SS_readdat_3.30.R#L400)

_Originally posted by @iantaylor-NOAA in https://github.com/r4ss/r4ss/issues/505#issuecomment-814355871_

**Comment by k-doering-NOAA** [comment]
Note some inputs are by month and others are by season, as noted in [this issue](https://github.com/nmfs-stock-synthesis/ss-documentation/issues/45)

**Comment by iantaylor-NOAA** [comment]
Work on a scripted R workflow for adding data to the 2021 Lingcod stock assessment has highlighted for me the benefit of getting consistent terminology not just between and within r4ss and SS but also the data-processing tools like the nwfscSurvey and PacFIN.Utilities packages in use at NWFSC. The r4ss read/write functions have been vital but will be all the better when these things are more consisten.

Case also matters in R and with different column names in so many places, I ended up going with all lowercase to make it easier to remember as shown here:
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/f437f9b24f010fb0367eb4206ac641ea555aef71/R/add_data.R#L400-L411
but I'd be happy with just about any convention as long as it's consistent.

**Comment by k-doering-NOAA** [comment]
I was also thinking about the mismatched naming conventions within lists, @iantaylor-NOAA , while writing code for SSMSE. I like the idea of using a consistent style to make it easier to remember the names of list elements.

**Comment by kellijohnson-NOAA** [comment]
I feel like it is easier on downstream users to rename things when the output and tools that work with the output all change at a consistent time. It seems like too big of a task to do all names at once, but I think it would be doable to fix a certain data set or column within all known packages at one time and work our way through. For example we could start with Year, YEAR, year, SAMPLE_YEAR.

**Comment by iantaylor-NOAA** [comment]
I'd like to make progress on this issue.
I would love to just change the following strings in the few places they occur in `SS_readdat_3.30()` and `tune_comps()`

old | new
-- | --
"Yr" | "yr"
"Seas" | "month"
"FltSvy" | "fleet"
"Gender" | "sex"
"Part" | "part"
"Ageerr" | "ageerr"

But I see these old/bad r4ss data file column names in use in many other packages: 
* SSMSE: https://github.com/nmfs-fish-tools/SSMSE/search?q=FltSvy
* ss3sim: https://github.com/ss3sim/ss3sim/search?q=FltSvy
* r4atlantis/atlantisom: https://github.com/r4atlantis/atlantisom/search?q=FltSvy
* flr/ss3om https://github.com/flr/ss3om/search?q=FltSvy

I'm sure there's lots more code that's not on github.

The idea of a coordinated large-scale roll-out of changes in r4ss and all packages that depend on it is appealing but seems hard.

Instead, what about the idea of a new optional input `new_names = TRUE/FALSE` with default `FALSE`. Then any package developers who have time to make the change can adopt the new names and turn on the switch. Then someday we can retire the old names and disconnect the `new_names` switch (while leaving it in place so we don't break the code that uses it). Or we can keep the code bloated until r4ss retires. Either way, at least those who want can have column names that match the ones used by SS3.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I think that the code in tunecomps is standalone and we could start the change there because I don't think that changing it would break anyone's downstream code. Then see how it goes. But, I would advocate for a message in r4ss that warns users that it is going to change and just repeat the columns. Then upon the next release remove them. 

One question ... why `yr` instead of `year`?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA,
Good points.
Your question about `yr` vs `year` helped me see that unfortunately the [ss_new output](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_write_ssnew.tpl) contains some of both, but more of `yr` than `year`. Do you think it's better to 
1. always use the same thing in r4ss regardless of match with SS3?
2. always match the SS3 headers (in the current release)
3. change the SS3 headers for a future release to be internally consistent?

I guess 3 can be combined with either 1 or 2.
5.

**Comment by kellijohnson-NOAA** [comment]
I would advocate for (1) and (3). But, I would for sure use `year` and I am not sure what to do about `ageerr` ... maybe `ageing`? Linters do not like things that do not pass spell checks and it would be nice to not have a separator so one word, to match all the other entries, would be ideal. Sorry for being so opinionated.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA do you feel like this is at a place where we can close this issue now?

**Comment by iantaylor-NOAA** [comment]
Yes, @e-perl-NOAA, thanks for all your work making this happen.

For those not watching the ss3-source-code repo, the next version of SS3 will have "year" instead of "yr" in the data file following the suggestion by @kellijohnson-NOAA in the comments on this issue so we'll have internally consistent terminology and also a more standard column name in the input files.
