### ISSUE TITLE
extend testing of read/write functions

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#517]
It would be helpful to test out read/writing of more SS input files. Now that there is [a public repo of some ss models for testing](https://github.com/nmfs-stock-synthesis/ss-test-models), a test that test could be written to see if these files are available, and if they are, then try reading/writing them. I think read/write functions work pretty fast, so hopefully this wouldn't slow down the run time too much if it were added to R-CMD-CHECK?

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA. This is a great idea. An even more rigorous test would be to run SS without estimation, then read and write the input files and run SS without estimation again to confirm that the results are the same, or at least that it runs without crashing. But that could come further down the road. I predict that there will be some work to do in debugging the proposed test of read and then write the input files from `ss-test-models`.

**Comment by k-doering-NOAA** [comment]
That's also a good idea to try to run the produced files, I hadn't thought of that - I know it takes ~ 5 min to run all the models without estimation,  so this would add some time to the run, but perhaps not so much that the check shouldn't be done on github actions.

**Comment by k-doering-NOAA** [comment]
closing this, as the basic tests were added in pull request #538. The additional step of making sure that SS can parse the files produced that @iantaylor-NOAA came up with could be added in the future.
