### ISSUE TITLE
biasadj pars

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#52]
How come the ```bias_adjustment_ramp``` parameters are not read in using ```SS_output```? Would you mind if I looked at adding this. You can calculate the rounded values from the ```recruits``` table, but if minor differences are produced for the ramp values these will not follow through into the actual used values in the years, thus I think it is better to report the actual values in the ramp line.

**Comment by taylori** [comment]
Either the parameters weren't available in Report.sso in some previous versions of SS or I just wasn't observant enough to see them there.
Yes, using the output labeled "breakpoints_for_bias_adjustment_ramp" would be a good improvement.

If you're inspired, you could augment the code to parse all of the text that is read with this line (currently 996), which is currently only used for the couple lines of the rmse_table
`     srhead <- matchfun2("SPAWN_RECRUIT",0,"SPAWN_RECRUIT",last_row_index,cols=1:6)`

**Comment by kellijohnson** [comment]
As far as I can tell all of the other information is available in the Report file already in places like the timeseries and parameter estimates. So I only included one new item in ```returndat```.  Although, one may want to move ```rmse_table``` to ```returndat``` rather than just printing it in the ```stats```. All changes are in a new local branch but I do not seem to have right to push.

**Comment by taylori** [comment]
Thank you @kellijohnson. You've now been added to the r4ss contributor team. Sorry for not thinking to do that earlier. Others who are interested in contributing are welcome to join as well.
It's buried deep in the code, but on line 1779, everything in `stats` is added to the list `returndat` with the command:
`returndat <- c(returndat,stats)`.

**Comment by kellijohnson** [comment]
I entered a pull request with my commit (@1411fd2fd1482ccaaa0f1255cd71b86953cd9c60).

**Comment by kellijohnson** [comment]
Ian I am pretty sure this issue can be closed, but I thought I should check with you first.
