### ISSUE TITLE
refine github actions

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#520]
The following issue is based on a conversation with @k-doering-NOAA.

The `run-tests-with-SS` workflow is failing for recent commits to the `cleanup` branch when it tries to read output from 3.30.12 model for which no executable is available, but none of the changes to that branch make sense as the cause of these failures.

Instead of digging deeper, this is motivation to refresh the github actions in a few ways:
- [x] bring the `run-tests-with-SS` workflow into the `R-CMD-check` workflow
- [x] remove tests for older SS models and focus on only on 3.30.16 for now

**Comment by k-doering-NOAA** [comment]
When rerunning the job, the job no longer failed, so the commits causing issues are  not a concern. Still, the suggestions here are useful and should be implemented!
