### ISSUE TITLE
add summary biomass to SSsummarize() and SSplotComparisons()

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#524]
Comparing spawning output for models which have different maturity or fecundity relationships is problematic. Adding a comparison of summary biomass would help for these cases and may be useful in general where summary biomass can be used as a reasonable proxy for available biomass (with appropriate choice of `min age for calc of summary biomass` in the starter file).

**Comment by IJStewart** [comment]
Great idea. Might also be helpful to have uncertainty calculated for summary biomass as an option in SS to support interpretation of these plots.

**Comment by iantaylor-NOAA** [comment]
Summary biomass is now available in the output from `SSsummarize()` in the [compare-summary-biomass](https://github.com/r4ss/r4ss/compare/compare-summary-biomass) branch via 3331f22. If Summary Biomass is included in the "read specs for more stddev reporting" at the bottom of the control file, you get the associated uncertainty, otherwise just point estimates from the timeseries table.

The next step to resolve this issue is to add it to `SSplotComparisons()`.
