### ISSUE TITLE
Inconsistent Language Between CAAL Fit Plots and Caption

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#531]
The conditional-age-at-length fit plots (the Andre plots) use language in the legend of observed and **expected**.  However, the caption that is provided in the html refers to the items in the figure as observed and **predicted**.   This is an easy fix but I wanted to post an issue so we can decide as a team the preferred term (expected vs. predicted) for this figure.

**Comment by kellijohnson-NOAA** [comment]
Across all figures shouldn't predicted be for the forecast period and expected is for years fit to data?

**Comment by iantaylor-NOAA** [comment]
I think @kellijohnson-NOAA's suggestion seems reasonable but I haven't ever thought of that distinction before.
Regardless, I would change "pred." to "exp." in the caption for the Andre plots. I'm not sure if I was the one who wrote that caption initially but if so, I certainly didn't intend anything different from expectation.

"Expected" is used in many many places and the only other case of "predicted" or "pred." is in "predicted discards" here https://github.com/r4ss/r4ss/blob/main/R/SSplotCatch.R#L102, so I would change that to "expected discards".

**Comment by chantelwetzel-noaa** [comment]
I think of I often use expected and predicted interchangeably.  However, I think @kellijohnson-NOAA seems to be the more appropriate use of the terms to me.    Thanks for the input. I went ahead and assigned the task to myself and will close the issue when done.
