### ISSUE TITLE
add informative warning associated with duplicate inputs that cause rownames() error

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#533]
As noted in #532, this message isn't very useful: `Error in .rowNamesDF<-: invalid 'row.names' length`.

However, the use of rownames in the `SS_readdat` and `SS_readctl` functions is really useful for keeping track of things but R's rules about avoiding duplicate rownames are more strict than the rules SS uses in making use of these inputs, so models that run fine may contain duplicate information that causes the r4ss functions to fail. Having those r4ss functions warn about these issues in an informative way instead of just failing would be helpful by allowing the functions to play through while also helping track down the problem so users can fix it.

I don't know of a comprehensive way to do this, but in the case I just looked at, the use of `rownames()` within a loop over rows of the lambda inputs in https://github.com/r4ss/r4ss/blob/main/R/SS_readctl_3.30.R#L1539-L1574 has some repeated code that could be condensed into a function which would make it easy to add something like 
```
if (new_rowname %in% rownames(ctllist[["lambdas"]])) {
  warning("Duplicate lambda input ", i, "associated with likelihood component ", like_comp, " fleet ", fl, " phase ", phz)
} else {
  rownames(ctllist[["lambdas"]])[i] <- new_rowname
}
```
In this case, the default rownames (e.g. "#_lambdas23") can remain and the function should play through just fine.

@k-doering-NOAA, does this seem like a good strategy?

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA , that makes sense! I will add this check when I have a chance!

**Comment by k-doering-NOAA** [comment]
https://github.com/r4ss/r4ss/commit/c22c3fdc566317705ec606cfe1433d66d71366d4 adds the warning and will change the rownames if there are duplicates so that each is unique. Thanks @iantaylor-NOAA for suggesting a solution.
