### ISSUE TITLE
Provide index figures without added estimated variance

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#534]
It would be useful to have index data figures without the added estimated variance (if present) to better reflect the data input into SS.

**Comment by iantaylor-NOAA** [comment]
Good idea. Do you see any point is showing the index with added variance but no expected values? That would save adding extra plots by making the change in the strikethrough below to the default plots, where the first one would be truly a pre-model input and the second one would reflect the model results for expected value and estimated added variance:

1. data with input variance ~~and added variance~~
2. data with input variance and added variance and expected value

**Comment by chantelwetzel-noaa** [comment]
I don't see a need for a figure of the index with added variance but no expected values.  I think #1 and #2 in your list would provide all the items that I typically want to include in documents.

**Comment by iantaylor-NOAA** [comment]
I just made this change in commit 26a8396bf0bfba029b7417237234619c928a3e59.
@chantelwetzel-noaa can you update r4ss and confirm that it works for your model?

**Comment by chantelwetzel-noaa** [comment]
Bingo.  Thank you @iantaylor-NOAA
