### ISSUE TITLE
problem with aggregation of tag recaps by fleet/area

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#546]
These lines in `SSplotTags()` are somehow adding observed recaptures to fleets which have none in the disaggregated table: https://github.com/r4ss/r4ss/blob/main/R/SSplotTags.R#L335-L337.
I'm assigning to @k-doering-NOAA who is more familiar with `dplyr` functions than me (I've just become a believer, but have a lot to learn first).
Thanks to Max Cardinale for reporting strange patterns in the resulting figures.

This function also isn't working well for models with many tag groups, so I may revert to the old version in the short-term while working out these two things.

**Comment by kellijohnson-NOAA** [comment]
My guess is that the error is in the code above rather than in the dplyr code. All the dplyr is doing is summing expected and observed numbers by fleet and year. Maybe the assignment of expected and observed to a given fleet a few lines above is where the mistake is happening?

**Comment by iantaylor-NOAA** [comment]
Problem was indeed not with the dplyr commands, but with converting fleet numbers from character strings to numeric and ending up in the wrong place. This should be fixed in 3436b920bbbcbad074ad8ec89d04962ba0bee766.
