### ISSUE TITLE
Units in Executive Summary captions and column headers

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#549]
https://github.com/r4ss/r4ss/blob/64b9e62aa80d87d68107a602f9bb08bd3d5bf0f5/R/SSexecutivesummary.r#L1190

I am not going to worry about it at the moment for lingcod, but it would be good in the future to look up the units and add these to the caption and / or the column headers. For example, catches are in mt and recruits are in 1000s of fish for most models.

**Comment by iantaylor-NOAA** [comment]
Duplicate of #559 (keeping that one as it includes a response).
