### ISSUE TITLE
SS_output not working with ss3.30.18

### ISSUE THREAD

**Issue by mcoshima** [r4ss/r4ss#556]
Hello,
I am having trouble reading in the report file with SS_output after updating to the newest version of SS3 (ss3.30.18). I keep getting the error 
`Error in 1:ncol(morph_indexing) : argument of length 0`. 
If you have any suggestions or fixes for that, that would be great.
Thanks,
Meg

**Comment by k-doering-NOAA** [comment]
Resolved via email Oct 8, 2021
