### ISSUE TITLE
caption of phase plot doesn't explain colors

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#562]
Thanks to @chantelwetzel-noaa who [explains the colors in the dover assessment](https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/ebef222484576b93b088796cd96ce9ad5e640b07/write_up/01executive.Rmd#L111) with

> warmer colors (red) represent early years and colder colors (blue) represent recent years

This text should be included in the automated caption.

**Comment by iantaylor-NOAA** [comment]
Good idea @kellijohnson-NOAA and @chantelwetzel-noaa.
Additional text added in commit f508058 appears as highlighted below:
![image](https://user-images.githubusercontent.com/4992918/139502609-05fc6aaf-8b01-473a-bbb8-434379d8a06b.png)
