### ISSUE TITLE
add functions to read/write input files all at once

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#563]
A while back @iantaylor-NOAA mentioned there were some helpful functions created in lingcod that might be good to have accessible in r4ss. 
-  https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/R/get_inputs_ling.R reads in all the input files for a Stock Synthesis model. It would be helpful to do this generally in a directory.  Maybe call this `SS_read_inputs()`?
- There could be a similar function writing all at the same time, maybe `SS_write_inputs()`

**Comment by kellijohnson-NOAA** [comment]
Do you think that we should shorten the names to `SS_read` and `SS_write` or would this make things difficult for autocomplete features of IDEs and text editors? I can start a branch with a version of the read function that I already started.

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I think this is complete, right?

**Comment by k-doering-NOAA** [comment]
Yes, thanks @kellijohnson-NOAA !
