### ISSUE TITLE
SS_readctl having trouble to terminate reading ctl file

### ISSUE THREAD

**Issue by elwise** [r4ss/r4ss#571]
Hello, while using the function SS_readctl3.30 I get a warning message and then a error:
Warning message:
In SS_readctl_3.30(file = file, verbose = verbose, echoall = echoall,  :
  Error: final value is1 but should be 999
 
It seems that for some reason it stops when reading the 'specs for more stddev reporting'

The end of my ctl file looks  like this:
#
1 # (0/1) read specs for more stddev reporting 
0 2 -1 7 # selex_fleet, 1=len/2=age/3=both, year, N selex bins
0 0       # 0 or Growth pattern, N growth ages
-1 2016 6    # 0 or NatAge_area(-1 for sum), NatAge_yr, N Natages
#
999

I have no trouble running ss just reading the file in R. It also has issues writing the ctl file with SS_writectl()

I'm using 'use_datlist = TRUE, datlist = dat' in the function so I'm not sure what is hapenning.
Thanks.

**Comment by kellijohnson-NOAA** [comment]
Thanks @elwise for reporting. @k-doering-NOAA I have these input files and it appears as though it is reading in the `stddev_reporting_specs` as they are written in the control file but it is not picking `stddev_reporting_selex` where the first number in this vector is 1 and `ctllist$.i` doesn't increment forward because
```
 ctllist[["stddev_reporting_specs"]][1] > 0
stddev_reporting_specs_1 
                   FALSE 
```
So is the control file wrong in that the first element of `stddev_reporting_specs` is 0 or does the code have a bug?

**Comment by kellijohnson-NOAA** [comment]
```
4 #_maxlambdaphase
1 #_sd_offset; must be 1 if any growthCV, sigmaR, or survey extraSD is an estimated parameter
# read 3 changes to default Lambdas (default value is 1.0)
#_like_comp	fleet	phase	value	sizefreq_method
    9	1	1	1	1	#_init_equ_catch_purse_seine_lambda_for_init_equ_catch_can_only_enable/disable for_all_fleets_Phz1
    4	2	2	1	1	#_length_Acoustic_survey_sizefreq_method_1_Phz2                                                   
    4	2	3	1	1	#_length_Acoustic_survey_sizefreq_method_1_Phz3
    4	2	4	1	1	#_length_Acoustic_survey_sizefreq_method_1_Phz3                                                   
-9999	0	0	0	0	#_terminator                                                                                      
#
1 # (0/1) read specs for more stddev reporting 
 0 2 -1 7 0 0 -1 2020 6 # selex type, len/age, year, N selex bins, Growth pattern, N growth ages, NatAge_area(-1 for all), NatAge_yr, N Natages
 1 2 3 4 5 6 # vector with NatAge std bin picks (-1 in first bin to self-generate)
999
```

**Comment by elwise** [comment]
Thanks @kellijohnson-NOAA and @iantaylor-NOAA . I'm afraid that even with the control input file ending as Kelli shows here I get the same error. I'm happy to share the input files if needed (or Kelli can share them with you if it's easier). Thanks

**Comment by kellijohnson-NOAA** [comment]
I gave Ian the link to the GitHub and pointed him to Setupa.

**Comment by iantaylor-NOAA** [comment]
I just pushed a change (1f8081d) to fix this issue for both the read and write step.

It appears that the read/write functions never supported the option to sum across areas within the extra stddev quantities for numbers at age (which seems to have been available in SS [from when it was added to git 7 years ago](https://github.com/nmfs-stock-synthesis/stock-synthesis/blame/main/SS_objfunc.tpl#L1101)), so just got overlooked in writing the r4ss functions.

In this case there is only one area so these inputs should produce the identical result within SS, but until this fix, the -1 option didn't work for r4ss:
`-1 2016 6 # 0 or NatAge_area(-1 for sum), NatAge_yr, N Natages`
and
`1 2016 6 # 0 or NatAge_area(-1 for sum), NatAge_yr, N Natages`

@elwise, thanks again for reporting this and please let us know if updating r4ss doesn't fix it for you.

**Comment by elwise** [comment]
Thanks @iantaylor-NOAA, the fix is working fine for me. Great!
