### ISSUE TITLE
Create function to download "models" directory and provide documentation

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#574]
https://github.com/r4ss/r4ss/blob/44cf139540e8d7e13fe89c69a05f8f7a55d2959e/tests/testthat/test-readwrite.R#L4
as well as 
https://github.com/r4ss/r4ss/blob/44cf139540e8d7e13fe89c69a05f8f7a55d2959e/tests/testthat/test-readwrite.R#L8
reference a directory called "models" in r4ss. This directory is not actually present in the r4ss repository but is something that developers download from [Stock Synthesis ss-test-models repository](https://github.com/nmfs-stock-synthesis/ss-test-models/tree/main/models). Being able to easily download those models, e.g., if you are setting up a new machine, to test the `SS_read*()` and `SS_write*()` functions and documentation in the test how to get the models would be good.
I think we should create a function in r4ss that downloads the models for you, that way in the test we can just call the function to download the models. This function could have a check to see if you already have the models directory in r4ss\inst\models it does nothing. I am currently looking into how to download a single directory. @k-doering-NOAA found how to download individual files. Perhaps {usethis} has something.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA and @k-doering-NOAA, this seems like a great idea. Let me know how I can help.

**Comment by iantaylor-NOAA** [comment]
I modified test-readwrite.R without remembering that the github actions don't run it because it requires inst/extdata/models. Running the test locally helped me sort out a bunch of issues (in #638) but it made me appreciate the day when we can test all those models via github actions.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA, I think the r cmd check github actions should run it, because it includes a step to download the models: https://github.com/r4ss/r4ss/blob/main/.github/workflows/call-r-cmd-check.yml#L20, which links to this workflow: https://github.com/nmfs-stock-synthesis/workflows/blob/main/.github/workflows/r4ss-extra-tests.yml#L61-L71

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA this is helpful, thank you!

I still have a variety of questions about workflows that a meeting might address better than more github issue, but for future reference, here's a few:
- The code coverage calculation doesn't seem to  account for the pieces that require SS3 input files in `inst/extdata/models`: https://app.codecov.io/gh/r4ss/r4ss/compare/638/diff. Do you know if we can fix that?
- The `call-r-cmd-check` workflow indeed seems to be running the tests in `test-readwrite.R` judging by the message indicating 8 skipped tests and 93 passed, with explanation that the skipped once needed the SS3 executable: https://github.com/r4ss/r4ss/runs/5795970595?check_suite_focus=true#step:10:57. However, there's very little information about the 93 passed tests. Do you think that changing to verbose = TRUE in the tests would make it easier to confirm which ones are getting run or is there another way to show more output there?
- I find myself confused by the presence of older workflows that haven't been run for months (screenshot below), but I can't figure out how to delete the old ones, just the individual runs of those workflows. Any idea how to clean this up?
![image](https://user-images.githubusercontent.com/4992918/161618072-75d48116-7b30-4468-a90a-4a28d135fefe.png)

**Comment by k-doering-NOAA** [comment]
Thanks for all these questions @iantaylor-NOAA, I totally see why these are confusing. Happy to meet and discuss. 

> The code coverage calculation doesn't seem to account for the pieces that require SS3 input files in inst/extdata/models: https://app.codecov.io/gh/r4ss/r4ss/compare/638/diff. Do you know if we can fix that?

Yes, you are absolutely correct. I bet we could include a step to download the models and then run codecov. BTW, looks like there are a lot of options I didn't know about for the covr package (https://covr.r-lib.org/)

> The call-r-cmd-check workflow indeed seems to be running the tests in test-readwrite.R judging by the message indicating 8 skipped tests and 93 passed, with explanation that the skipped once needed the SS3 executable: https://github.com/r4ss/r4ss/runs/5795970595?check_suite_focus=true#step:10:57. However, there's very little information about the 93 passed tests. Do you think that changing to verbose = TRUE in the tests would make it easier to confirm which ones are getting run or is there another way to show more output there?

I think they way it is coded, it will run those tests, but with fewer models? My guess is the number of tests is higher for the step where the models are downloaded first (that comes after R cmd check). 

I'm happy to turn on verbosity, if it would help in the logs! There is already quite a bit of output coming from the model runs.

> I find myself confused by the presence of older workflows that haven't been run for months (screenshot below), but I can't figure out how to delete the old ones, just the individual runs of those workflows. Any idea how to clean this up?

I just found this option to manually disable workflows, so they show up with a stop sign symbol (see below). I think they are persisting because we have old branches with these workflows still available.
![image showing github actions buttons](https://user-images.githubusercontent.com/48930335/161621315-377db916-b383-434c-8c62-23cf4988ff02.png)

**Comment by iantaylor-NOAA** [comment]
Seems like this issue has already been covered (and is extended by #645)

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I think Kelli was thinking about adding a function to r4ss, to download the models directory, which we don't currently have.

**Comment by k-doering-NOAA** [comment]
That's a good point, we could have them do that. I heard a while back that having nested git repos was a bad idea, so I've never explored it. But clearly there are ways to do it and they seem to work fine.

The alternative would be to make a `use_this` kind of function, which we could build on top of [this usethis function to download a github file](https://github.com/r-lib/usethis/blob/a05255da31f7e3cb047250571d75d83f17ece6f4/R/use_github_file.R#L44). The pros of this approach is I think it would be more intuitive for people and it could be used outside of r4ss testing (for example, someone could download the model files to test their own software that uses ss3 locally). The cons are the downloaded files aren't in git, so not version controlled.

I personally am a bit wary of the git repo within a git repo still, but could be persuaded.

**Comment by k-doering-NOAA** [comment]
Just found this nice utility to download a folder from github: https://download-directory.github.io/

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA did add [an example](https://github.com/r4ss/r4ss/blob/c06efbaf1ed61a23ba8a9064550d50f28e1cdb16/R/SS_read.R#L50-L58) for how to get input files off of github and into your R workspace using SS_read.

However, I still feel that we need a function or example to download all the models.
