### ISSUE TITLE
move double normal selectivity shiny app to a separate repo so it can be hosted

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#576]
There is code for a double normal selectivity tool written as a shiny app within r4ss (see #48). Currently, it can only be run locally by running the function `selShapes()`.

Move this code to a separate repository within the r4ss organization, then work with @ChristineStawitz-NOAA to host the app on Rstudio connect.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, thanks for taking this on. Assuming you're successful with this effort, it may also be worth trying to add get things working for cubic spline selectivity as well (discussed in #63 as well as #48).

**Comment by k-doering-NOAA** [comment]
I've moved the shiny app code to https://github.com/r4ss/shiny_selex with git history. The files still haven't been removed from r4ss, but perhaps this an be done once we determine the separate git history is  the way to go.
