### ISSUE TITLE
create function to calculate risk of various things in MLE forecasts

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#58]
Recent Pacific Hake assessments have included forecast risk tables based on MCMC distributions. Similar tables can be created from the normal approximations around derived quantities in MLE forecasts but a function to automate those calculations would be useful.

**Comment by allanhicks** [comment]
I have some hake code that would be a good start

**Comment by taylori** [comment]
Great. I was going to try assigning it to you but I see you've done that already.

**Comment by taylori** [comment]
This issue is redundant with #136, so will close this one to clean things up. 
@allanhicks, if you've already created something along these lines, please let me know or assign #136 to yourself. Otherwise, you're off the hook as the assignee of this closed issue.
