### ISSUE TITLE
outdated `SS_makedatlist()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#591]
The code for `SS_makedatlist()` is stale, i.e., has not been changed except for styling since 2014 and the version of SS3 referenced is 
https://github.com/r4ss/r4ss/blob/e0fd227b6314ee7b58c2a3ec9d8286b657cdb915/R/SS_makedatlist.R#L107

I suggest that we remove the function from the codebase after the holidays. I think it is easier to read in the simple example data file stored in the package and augment the structures in the returned list. We could include information regarding how to do that in the vignette for users instead of trying to maintain this function. I am open to other ideas as well.

**Comment by iantaylor-NOAA** [comment]
Function removed from the package in 5eec484. The telling comment written when the function was first created (8+ years ago) is "In hindsight, this function doesn't seem very useful...".
