### ISSUE TITLE
SS_output crash at call of get_dat_new_name

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#592]
When I called SS_output as
``
> out <- r4ss::SS_output(dir=".", covar = F)
``
SS_output stopped if data.ss_new exist but data_echo.ss_new  as

``
Finished dimensioning
Reading data.ss_new (or data_echo.ss_new) for info on Dirichlet-Multinomial parameters
Char version is  3.30
Numeric version is  3.3
Running SS_readdat_3.30
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In get_dat_new_name(dir) :
  Neither data.ss_new or data_echo.ss_new found in dir .
2: In file(con, "r") : cannot open file './NA': No such file or directory
``

If I called get_dat_new_name directly, I got 

``
> r4ss:::get_dat_new_name(dir=".")
[1] NA
Warning message:
In r4ss:::get_dat_new_name(dir = ".") :
  Neither data.ss_new or data_echo.ss_new found in dir .
``

On the other hand 
``
> file.exists(file.path(".", "data.ss_new")
+ )
[1] TRUE
``
hence data.ss_new exists

According to the source codes of get_dat_new_name. 
"data.ss_new" is set to datname  if the file data.ss_new exists in dirt.
But then datname is reset if the file data_echo.ss_new does not exist.

One potential solution may be to let skip the latter part if datname is set to 
"data.ss_new" by "ifelse".  But I am not sure if this change is appropriate.   

``

**Comment by kellijohnson-NOAA** [comment]
Thank you @yukio-takeuchi for alerting us of this problem. We have fixed it in pull request #593 and will merge it into main as soon as the checks finish.
