### ISSUE TITLE
Add options to remove upper margins and not print title when SS_html is used to get captions

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#6]
Google Code issue 47:
Reported by IanTaylorNMFS, May 4, 2012
Switch to change main=NA should be easy. Shrinking margins will be more complex in multi-figure plots.

**Comment by taylori** [comment]
Side and bottom margins could be reduced in many cases as well.

**Comment by taylori** [comment]
This issue required copying modified r4ss in hake assessment code instead of calling function directly:
https://github.com/cgrandin/hake-assessment/blob/master/doc/r/figures-age-comps.r#L374
Need to sort it out by end of 2016 for next year's hake assessment.

**Comment by iantaylor-NOAA** [comment]
This would take a while and is too low of a priority to leave as an open issue.
