### ISSUE TITLE
add SD of log(SpawnBio) in final year 

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#60]
This will facilitate comparison to Pacific Council sigma defaults (0.36 for Category 1, 0.72 for Category 2), for application of P* in forecasts.
Thanks @melmonk for noting that this isn't readily available.
Can use the formula 
sigma <- sqrt(log((SD/EST)^2+1))
which I think is due to Owen Hamel.
Implementing this will probably take no more time than writing up this issue.

**Comment by taylori** [comment]
Pstar_sigma to list produced by SS_output with this change: d348f6838e5d2782ceba3ba33e75233bcb32a790.

Pstar_sigma = NULL if no derived quantity
has label SPB_YYYY where YYYY is ending year + 1. Pstar_sigma = 0 if
uncertainty wasn't calculated (as with -nohess option).

Not tested on many models yet so leaving issue open for now.

**Comment by taylori** [comment]
Looks reasonable in a few additional tests, so closing this issue.

**Comment by iantaylor-NOAA** [comment]
`$OFL_sigma` just added to the list returned by SS_output, calculated the same way as `$Pstar_sigma`. This addition is based on request from Pacific Fishery Management Council SSC to see a "sigma" (standard deviation on a log scale) calculated for both current year spawning biomass and OFL values (where current year is endyr+1 = 2019 for west coast groundfish assessments)
