### ISSUE TITLE
SS_changepars phase

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#61]
Is it the intent that you cannot change the phase to a different positive phase, only turn the parameter on and off? It would be nice if you could give it a new phase value.

**Comment by taylori** [comment]
I think this was originally written for use with likelihood profiles and at first you could only change the value. @cstawitz improved the function to allow changing bounds so further expansions make sense.
I think that leaving the `estimate` input as is while adding something like a `newphase` input with default NULL makes lots of sense. It wouldn't break any existing uses but expand the utility. If you want help with that, let me know.

**Comment by kellijohnson** [comment]
Added ```newphs``` which works with ```estimate``` to change the phase while also turning the parameter on and off in commit e152212f1676ed6b8bd8f1e208e37b28e0916a8a

**Comment by taylori** [comment]
I haven't tested this but looked over code and trust that it will work so am closing issue. Thanks @kellijohnson.
