### ISSUE TITLE
Make sure r4ss is works with new features in upcoming Stock Synthesis version 3.30.19

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#610]
After looking through milestone list at https://github.com/orgs/nmfs-stock-synthesis/projects/2/views/1, this is the only one that jumps out as needing changes in r4ss

- [x] new MEY benchmark option will require changes to r4ss read/write forecast functions: https://github.com/r4ss/r4ss/issues/586 [feature is still in progress]

@k-doering-NOAA, are you aware of other changes that require work on the r4ss end? If so, please feel free to edit this list.

**Comment by k-doering-NOAA** [comment]
There might be some due to the breaking up of data.ss_new into data_echo.ss_new, data_expval.ss_new, and data_bootxxx.ss_new; and perhaps supporting ss_new and sso subfolders if they exist?

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I'm starting to work on this - let me know, though, if you are already addressing this issue!

**Comment by k-doering-NOAA** [comment]
I ran the r4ss tests using a test executable of stock synthesis  and they all pased, so I think we have done enough checks for now.
