### ISSUE TITLE
Forecasting multiple management strategies

### ISSUE THREAD

**Issue by lsolinger** [r4ss/r4ss#616]
I'm performing a simulation analysis for summer flounder in SS and wondering if there is a more efficient way to forecast multiple management strategies without rerunning the model with a new forecast file. For example, say I generate 100 bootstraps from my base model and I want to forecast 3 management strategies for each of the bootstrap. To do this, each of the 100 bootstrapped datasets is run through SS three times, though the model converges each three times on the same parameter estimates and only the forecasted period varies. If my model takes ~10 minutes to run, a single simulation then takes 30 minutes to generate forecasted stock status according to each of the proposed management strategies. Is there a way to save the converged model and only run the forecast based on that model? I thought perhaps I could run each simulation, then rerun the forecast with the ss.par file and close the parameters to estimation to quicken the model run, but I wasn't sure if there is any guidance or function that addresses this issue. Thanks a ton for any help.

**Comment by iantaylor-NOAA** [comment]
Hello @lsolinger,
Good question. You definitely want to avoid re-running the model every time. 

When modifying a forecast file I often use a command like `ss -maxfn 0 -phase 50 -nohess` to re-run the model without estimation as described in the SS3 User Manual here:
https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#running-without-estimation.
That requires modifying the starter file to use ss.par for initial parameter values which you could script within r4ss using the `SS_readstarter()` and `SS_writestarter()` functions.

Please let us know if that doesn't work for you.
-Ian

**Comment by lsolinger** [comment]
Thank you very much, Ian. That is exactly what I needed to know.
