### ISSUE TITLE
add ADMB executables to r4ss package for selfit_spline

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#63]
This is related to #48  

A short-term fix to make selfit_spline easier to use would be to include ADMB executables for different operating systems in the r4ss package.

@seananderson points to the function get_bin_loc in https://r-forge.r-project.org/scm/viewvc.php/pkg/R/glmm.admb.R?view=markup&root=glmmadmb
and the binaries at: https://r-forge.r-project.org/scm/viewvc.php/pkg/inst/bin/?root=glmmadmb

**Comment by taylori** [comment]
Windows executable and TPL moved to new location in recent commit  but issue should remain open until other operating systems are supported and perhaps executables are installed automatically.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA It looks like this isn't even a part of r4ss anymore. Plus the executables for glmmadmb are over 8 years old. Can this issue be closed?

**Comment by iantaylor-NOAA** [comment]
Won't fix. Thanks @e-perl-NOAA for noting this.
