### ISSUE TITLE
add_legend: missing type

### ISSUE THREAD

**Issue by efletcherPIFSC** [r4ss/r4ss#631]
When `add_legend` was refactored as a common plot legend function (#617) , The object `type` is not defined in the function or arguments. The `type` comparison to turn off points on top of the lines of the legend.

https://github.com/r4ss/r4ss/blob/32f777b6bec5b6354583056cd97bf321bc0a7839/R/helper_fxns.R#L166-L170

Defining a default to `type` will resolve this.

**Comment by iantaylor-NOAA** [comment]
@efletcherPIFSC, I presume that Pull Request #629 from @MOshima-PIFSC sorts this out adequately. If so, go ahead and close this issue.

**Comment by efletcherPIFSC** [comment]
Yes
