### ISSUE TITLE
Update to {roxygen2} to use _PACKAGE

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#658]
https://github.com/r4ss/r4ss/blob/03ea31db712125f7f9b8617935f1491ee171bddb/R/r4ss-package.R#L57

should be `"_PACKAGE"` as well as identifying the file as an internal file. See [guidance from the {roxygen2} vignette](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html#cb9-2).
```
#' @keywords internal
"_PACKAGE"
```

**Comment by iantaylor-NOAA** [comment]
Not totally clear to me what the the "special sentinel" `"_PACKAGE"` does, but was easy enough to add in 2a606ae.

**Comment by kellijohnson-NOAA** [comment]
It allows information to be ported from the DESCRIPTION to `?r4ss` without having to retype it. See the [news feed for {roxygen2}](https://roxygen2.r-lib.org/articles/releases/roxygen2-6.0.0.html).

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, got it. That makes a lot of sense.
I was able to remove the redundant (and not exactly matching) description section and some other stuff in commit [1d03680](https://github.com/r4ss/r4ss/commit/1d0368057691a93958f64fb49c303c3d578779a3), but could not get the author list or any other fields to port over in spite of various tries, perhaps because we aren't using the more advanced `Authors@R` format https://r-pkgs.org/description.html#description-authors. Nevertheless, definitely an improvement. Thank you for the tip.

**Comment by iantaylor-NOAA** [comment]
One more thing, I went ahead and switched to using the `Authors@R` format for the author list in commit 9d3cf99 and those entries are now being copied over to `r4ss-package.Rd` automatically thanks to the use of `"_PACKAGE"` with improved formatting and designation of me as maintainer: https://github.com/r4ss/r4ss/blob/main/man/r4ss-package.Rd#L29-L67.

I also added @lee-qi, @MOshima-PIFSC, and @efletcherPIFSC to the author list for r4ss as they have all contributed to the package (Lee Qi back in 2019) but were missing from the list.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I ran `check()` and got
```
Authors@R field gives persons with no role:
Ian J. Stewart
...
```
so everyone below Ian Stewart does not have a "role".

**Comment by iantaylor-NOAA** [comment]
I was being lazy and assuming that the automatically generated designation of "Other contributors:" was adequate, but if there's a warning about it, that's not good. I've just parsed `family` and `given` and added `role = "aut"` in e0dfe24. The [R package book](https://r-pkgs.org/description.html#description-authors) suggests a distinction between 
* aut: authors, those who have made significant contributions to the package.
* ctb: contributors, those who have made smaller contributions, like patches.

but I'm not inspired to try to figure out how to draw a line between those groups right now.
