### ISSUE TITLE
replace cat() and other print statements with message() and warning()

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#660]
There are still instances of `cat()` being used to print r4ss messages to the screen. It would be fairly simple to replace these with message() or if they are a warning, with warning(). That way, users can handle the messages and warnings in the way they desire (e.g., turn off messages for their R session if they don't want to see them).

**Comment by kellijohnson-NOAA** [comment]
See #79 for a discussion of `cat()` versus `message()` for `SS_plots()`. It would be good to tackle both of these issues at the same time.

**Comment by iantaylor-NOAA** [comment]
One additional comment on this for the record.
There was an issue with printing a table of likelihood changes by fleet in `PinerPlot()` introduced here: https://github.com/r4ss/r4ss/commit/7074826b3c60123a4832cbf8f6d78ce5ec7095d6#diff-7fe3ea93723085ca675a5a31bcb7db89699fa49d4bb076bac356f2e5e575cd65R241

I initially reverted the change to the old approach using `print()`, but then saw the use of `utils::capture.output()` in other functions so seem to have got it working again in c0c050b. 
@k-doering-NOAA, feel free to make further if what I ended up with didn't match your original intention.

**Comment by k-doering-NOAA** [comment]
Thanks for noticing this, @iantaylor-NOAA - I probably removed a `print()` statement that shouldn't have been removed. Thanks for catching this!
