### ISSUE TITLE
dynamic B0 warning message

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#665]
I keep getting this warning when running `SS_plots`:

```r
In SSplotDynamicB0(replist = replist, yrs = yrs, uncertainty = (uncertainty &  :
  No element "Dynamic_Bzero" in replist input
```

I wonder if this should be changed to a message instead of warning, as there may be many cases where SS3 users don't request output for dynamic b0?

**Comment by kellijohnson-NOAA** [comment]
Seems like maybe we should keep the warning in `SSplotDynamicB0()` and, instead, wrap the actual call to `SSplotDynamicB0()` inside of [`SS_plots()`](https://github.com/r4ss/r4ss/blob/aadc58f2c05a45bfbf4c0c125004a79289fd5ad5/R/SS_plots.R#L639) in an `if{}else{}` statement where it doesn't try to plot it if the information doesn't exist. We could put the message inside the `else{}` part saying that the information doesn't exist and therefore will not be plotted even though the subplot number was included.

**Comment by kellijohnson-NOAA** [comment]
Maybe what I said above is overkill and @k-doering-NOAA's suggestion is better? I guess it depends on what you want the user experience to be when someone tries to run `SSplotDynamicB0()` and they don't get any output.

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this @k-doering-NOAA. 

Adding a `message()` and skipping the function call as suggested by @kellijohnson-NOAA is consistent with a bunch of other cases in `SS_plots()` (just search for the word "skipping"), so I've done that in https://github.com/r4ss/r4ss/commit/77522678f538979f2eafed5ad9f1b9ca8f751d15.  I should have done it when first adding the new plot.

I left the `warning()` and `return()` in the `SSplotDynamicB0()` function just in case somebody calls it directly.
