### ISSUE TITLE
Deprecate Ptype column in SS_readctl_3.30

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#668]
Thanks Megumi Oshima for reporting that Ptype is included in some parameter dataframes output from SS_readctl_3.30, but not all. Given it is not a part of the SS3 control file, it makes sense to remove it as a dataframes column

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA this makes lots of sense. Thanks for stepping up to take this on.
And thanks @MOshima-PIFSC for finding the inconsistency.

**Comment by MOshima-PIFSC** [comment]
@k-doering-NOAA and @iantaylor-NOAA I just tried this out and it works great! Thanks for making that change!

**Comment by k-doering-NOAA** [comment]
Thanks @MOshima-PIFSC! It ended up simplifying the code a lot, too, so was a win all around!
