### ISSUE TITLE
subplots and subplot both used as variables in plotting functions

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#687]
Wile working on #311, I noticed that both `subplots` and `subplot` are used as arguments in the SSplot* functions, though as far as I can tell, they mean the same thing (at least in most cases). To reduce confusion, I think it would be great to change all of these to subplots and soft deprecate subplot using `lifecycle::deprecated()` until the next release of r4ss.

The 4 functions where subplot is used:
```
R\SSplotData.R:
  11  #' @template plotdir
  12: #' @param subplot vector controlling which subplots to create
  13  #' Currently there are only 2 subplots:

R\SSplotSelex.R:
  26  #' Selectivity, 2. Retention, 3. Discard mortality, 4. Keep.
  27: #' @param subplot Vector controlling which subplots to create.
  28  #' Numbering of subplots is as follows,

R\SSplotSpawnrecruit.R:
  6  #' @template replist
  7: #' @param subplot vector of which subplots to show.  1=plot without labels,
  8  #' 2=plot with year labels.

R\SSplotTimeseries.R:
  7  #' @template replist
  8: #' @param subplot number controlling which subplot to create
  9  #' Numbering of subplots is as follows, where the spawning biomass plots
```

**Comment by iantaylor-NOAA** [comment]
The mix of `subplots` and `subplot` was surely just sloppiness on my part. It's grated on me over the years when I've gotten it wrong when using the function, but somehow I never thought to fix it.

The one exception is `SSplotTimeseries()`, where the function can only do one plot at a time. We should probably leave that one as `subplot` and not use a template in the documentation.

**Comment by k-doering-NOAA** [comment]
I know in my own code I have done this sort of thing over and over again, so you are certainly not the only one, @iantaylor-NOAA. I agree that `SSplotTImeseries()` is different and should be left.

I added this change to PR #688 in a new commit.
