### ISSUE TITLE
Naming conventions across SS_output list elements

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#69]
I have noticed that the various data.frames in the SS_output list do not use the same naming conventions for what appear to be the same dimensions. For example, watage has

```
yr seas gender growpattern birthseas fleet      X0     X1        X2        X3    ...
```

while catage has

```
Area Fleet Gender XX XX Morph   Yr Seas XX  Era 0   1   2   3   4 ...
```

This makes difficult reusing code for plotting or manipulating those data.frames

Cheers.

r4ss 1.23.5

**Comment by kellijohnson** [comment]
The colnames are taken directly from their respective files (i.e., Report.sso and wtatage.ss_new for catch at age and weight at age). You can easily remove the XX columns using:
```
report <- SS_output(...)
report$catage <- report$catage[, colnames(report$catage) != "XX"]
```

**Comment by iagomosqueira** [comment]
On 02/09/15 19:47, Kelli Johnson wrote:
> The colnames are taken directly from their respective files (i.e., Report.sso and wtatage.ss_new for catch at age and weight at age). You can easily remove the XX columns using:
> ```
> report <- SS_output(...)
> report$catage <- report$catage[, colnames(report$catage) != "XX"]
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/r4ss/r4ss/issues/69#issuecomment-137185900
>

Thanks. Yes, I know how to remove them but I just found it strange that 
the output is a not-too-correct data.frame.

**Comment by taylori** [comment]
This issue overlaps #141 which has more information, so closing this one.
