### ISSUE TITLE
write_fwf4 with data.frame having column(s) of factors

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#698]
When I wrote write_fwf4 function, I simplified it to accept columns of numeric( or int) or character.
However, although it is rarely happen with recent version of R with recent SS_read* functions, R may still accidentally identify  one or more of columns of data.frame  as factor.  In fact, I recently met such situation when I manipulated some of data.frame  in a datlist by external R codes.  Within write_fwf4, a piece of code like
```
if (is.factor(x[, I])
  x[,I] <- type.convert(as.character(x[,I]),as.is=TRUE)
```
may avoid error due to column(s) of factor.
I am wondering if this change is necessary or not as no one reported an error of write_fwf4 related to column(s) of factor.

**Comment by iantaylor-NOAA** [comment]
Hi @yukio-takeuchi, this seems like a good idea. Thanks for thinking of it.
Could you be put together a pull request for a change to `write_fwf4()`, or do you want me to just insert the suggested change?
