### ISSUE TITLE
refine phase plot

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#703]
A data and stock assessment open discussion (I think on May 6) focused on phase plots identified a few potential improvements.
These changes have been attempted in the [phase_plot_changes](https://github.com/r4ss/r4ss/tree/phase_plot_changes) branch, including
- add a reference point line at the SPR target when `SPR_report_basis` has SPRratio equal to raw SPR (and thus the target doesn't correspond a ratio of 1.0)
- add labels to point at each decade in addition to the status-quo labels on the start and end year (this leads to some overlapping labels which I can't be bothered to sort out, but am open to ideas)
- expand the caption to note the relationship between color and time period

I made these changes a while ago and then forgot about them so I'm not sure what further work was needed before merging this into the main branch. Maybe I just wanted some feedback on whether this looks OK or if folks have other suggested changes. Please comment below if you have suggestions.

**Example of status-quo phase plot:**
![image](https://user-images.githubusercontent.com/4992918/176941193-fd5ba2e2-b4ae-4eb8-a4b0-873a99ff2a1e.png)
**Modified phase plot:**
![image](https://user-images.githubusercontent.com/4992918/176941111-d72829b7-90c2-4a52-8fd7-8f2bdae3db21.png)

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA overplotting of labels is easily dealt with using [ggrepel](https://github.com/slowkow/ggrepel) but I am guessing that change isn't what you are looking for 😉. I tried [`plotrix::spread.labels()`](https://www.rdocumentation.org/packages/plotrix/versions/3.7-2/topics/spread.labels) as suggested on [stack exchange](https://stats.stackexchange.com/questions/16057/how-do-i-avoid-overlapping-labels-in-an-r-plot) and found it did not quite work that great, i.e., some labels are outside of the figure.
![plot](https://user-images.githubusercontent.com/4108564/176947097-92be6181-3eb5-496a-be25-b59e8af575fe.png)

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, thanks for trying out a solution even though it didn't work that well. I look forward to {ggrepel} in future packages, but for now I think living with the overlap is fine. 

In general there will be little mystery about what any unreadable overlapping labels say as it will typically just be all the decades before relative fishing intensity went up relative spawning output went down.

**Comment by iantaylor-NOAA** [comment]
Forgot to close this issue after merging #704.
