### ISSUE TITLE
show partitioning of added variance in index plots

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#71]
@melmonk indices that SSC requested this feature during September 2015 meeting.
Starting point may be code developed long ago during discussions with Chantel Wetzel on desktop at c:/SS/R/example_index_plot.R

**Comment by taylori** [comment]
Note that this will probably look similar to Francis weight plots with thick and thin lines. Probably also useful to have a switch that would allow display of only input variance or only total variance without indication of partitioning.

**Comment by melmonk** [comment]
Yes, this addresses the comment from the SSC.

**Comment by taylori** [comment]
This issue hopefully addressed with recent change: https://github.com/r4ss/r4ss/commit/b60df1f1a7a3339dc1677f002348eab0c0ca13db
Waiting for others to test before closing.

Currently input uncertainty is only shown (via thicker line) when added variance parameter is defined and new input show_input_uncertainty is TRUE (the default). However, in models where the parameter is defined but fixed at zero it might be better to turn the thicker line off.

**Comment by taylori** [comment]
Variance partitioning in index plots seemed to work just fine for @allanhicks in CAPAM demo so closing issue. Allan, thanks for testing.
