### ISSUE TITLE
Clarification to MGparmLabel for fecundity params in SS_readctl_3.30

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#714]
Hi, 
In lines 444-476 of SS_readctl_3.30.r, labels for 2 params of fecundity are conditioned on ``ctllist[["maturity_option"]]``.  I suspect, they should be conditionded on ``ctllist[["decundity_option"]]``, although probably this potential typo may be harmless.

**Comment by k-doering-NOAA** [comment]
Thanks @yukio-takeuchi for realizing this! I double-checked in the manual and you are right. However, I also realized that there are always 2 parameters, so I got rid of all the if else statements and just labeled them as Eggs_alpha and Eggs_beta (see 46f86ce1084795ff5478fc88b24b0bb89a495cdf). Let me know if you would prefer the names as in SS3 be retained!
