### ISSUE TITLE
SS_readctl() possible bug

### ISSUE THREAD

**Issue by latreesedenson-NOAA** [r4ss/r4ss#716]
Hi,

When using the SS_readctl() function on a newly transitioned 3.30.19 model I get the following error:
Error in SS_readctl_3.30(file = file, verbose = verbose, echoall = echoall,  : 
  Cannot find data file specified in datlist: data.ss_new

I have both a data.ss_new and data_echo.ss_new file in my directory but it will not recognize either.

Thanks,
LaTreese

**Comment by iantaylor-NOAA** [comment]
Hi @latreesedenson-NOAA,
Sorry for the error. Can you try updating r4ss from github and confirm that the error still persists?
The current version should return 1.45.2 from packageVersion("r4ss"). I ask because the echoall argument should no longer be present in the internal function call.
-Ian

**Comment by k-doering-NOAA** [comment]
Oops, sorry for the crossed message with Ian! A better suggestion to try first, I think.

**Comment by latreesedenson-NOAA** [comment]
OK, for version 1.45.2 the error still persists but if I point datlist to the SS_readdat() object, it works. Maybe you all can update the help file to say something along the lines of "should be the name of the data object"?

Thanks for the help.

LaTreese

**Comment by iantaylor-NOAA** [comment]
The documentation at https://github.com/r4ss/r4ss/blob/main/man-roxygen/readctl_vars.R#L3-L4 suggests that it could either be a list created by `SS_readdat()` or the name of the file. @k-doering-NOAA, do you have ideas on how to debug the file name option?

**Comment by k-doering-NOAA** [comment]
@latreesedenson-NOAA , I'm wondering if the issue is that the full file path isn't provided for the datlist when it is looking for data.ss_new ? The current default assumes that data.ss_new is in the R working directory.

 Maybe we could append the same folder path as used for the ctl file input, as a more sensible default? so use `file.path(dirname(file), "data_echo.ss_new")` as the default value?

**Comment by latreesedenson-NOAA** [comment]
Ah OK, I didn't realize that was the assumption. If that makes it more flexible, I could see it being helpful.

**Comment by iantaylor-NOAA** [comment]
Good idea @k-doering-NOAA. In the changes I've slowly been working through related to all functions that run models in the `system2_issue456` branch, I've been trying to replace worthless default paths like
https://github.com/r4ss/r4ss/blob/b03e4d0a2699569ca5d7401f67ec1b0cb1ce908a/R/SS_profile.R#L180
with `dir = getwd()`, so this would be in line with that plan.

**Comment by k-doering-NOAA** [comment]
Perfect, I pushed these new defaults in 94a8394. Thanks @latreesedenson-NOAA for reporting this, as hopefully the new defaults will be more intuitive to others! Feel free to reopen if you have any other suggestions.
