### ISSUE TITLE
helper_fxns.R  'par' is out of scope of save_png

### ISSUE THREAD

**Issue by efletcherPIFSC** [r4ss/r4ss#720]
The variable `par` is not defined within **save_png** (in `helper_fxns.R`).    

https://github.com/r4ss/r4ss/blob/c9be845f11b5c2814b3f37e56c99242a382f8c98/R/helper_fxns.R#L263-L266

**Comment by iantaylor-NOAA** [comment]
Thanks @efletcherPIFSC. I just caught this as well. Sorry about the error. I fixed it in the branch I'm working on https://github.com/r4ss/r4ss/commit/e56f45aebbbda1761ba660bdbcaafade7d886e72. Which will hopefully be ready for merging into `main` at the start of next week. If you need a fix sooner, we could make the change in main right away or you could try out the [system2_issue456](https://github.com/r4ss/r4ss/compare/system2_issue456) branch.

**Comment by iantaylor-NOAA** [comment]
The [system2_issue456](https://github.com/r4ss/r4ss/compare/system2_issue456) branch, in which the problematic `par()` command was fixed, has now been merged in Pull Request #722, so closing this.
