### ISSUE TITLE
simplify function names that run models

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#723]
As discussed in PR #722, we can rename the functions that call the executable as follows to avoid a bunch of inconsistent capitalization. Also `run_SS_models()` has already been renamed to `run()` as part of that PR.

  old | new
  -- | --
  SS_RunJitter() | jitter()
  SS_doRetro() | retro()
  SS_profile() | profile()
  SS_tune_comps() | tune()

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for these proposed changes. I am only slightly worried about the use of `tune()` because it is not very clear what it is doing because there are various parts of the model that can be tuned.

**Comment by chantelwetzel-noaa** [comment]
I had the same thought as @kellijohnson-NOAA but I think all of the other proposed function name changes look reasonable.

**Comment by iantaylor-NOAA** [comment]
We can definitely pick something other than `tune()`. How about `tune_comps()`? We don't typically do any other iterative tuning and if we were to add that functionality, it could be put into the same function.

**Comment by chantelwetzel-noaa** [comment]
That would work for me. Plus, its new naming structure would align with all other proposed changes that just cut out the SS_ part.

**Comment by iantaylor-NOAA** [comment]
**Update and questions:**

I started on this effort by first reading https://lifecycle.r-lib.org/articles/communicate.html#rename-a-function
and watching the Hadley Wickham RStudio 2021 keynote about the {lifecycle} package: https://www.rstudio.com/resources/rstudioglobal-2021/maintaining-the-house-the-tidyverse-built/

Then I renamed SS_profile() to profile() in commit 7e2dfe2 in the [rename_functions_issue723](https://github.com/r4ss/r4ss/tree/rename_functions_issue723) branch, via the following changes:
1. copy contents of `R/SS_profile.R` into `R/profile.R`
2. replace the contents of the `SS_profile()` function with a call to `lifecycle::deprecate_stop()`
3. do a global find/replace for `SS_profile` to `profile` to update the tests cross references in documentation
4. update the NEWS.md file to note the changes

I can repeat these for the 3 other functions that are proposed for renaming in this issue but wanted to give folks a chance to provide feedback on two things that could have been done differently

**Question 1**: In terms of git history, does it make sense to create a new file for the new function name or use `git mv R\SS_profile.R R\profile.R` and then create a new file for the old function name? I think GitHub's blame won't work for either approach, so I'm not sure how much it matters.

**Question 2:** Is it OK to use `deprecate_stop()`? The example in https://lifecycle.r-lib.org/articles/communicate.html#rename-a-function uses `deprecate_warn()` as the first step and calls the new function from the old function, passing the inputs over. My fear with that approach is that these functions have lots of arguments, many of which just changed in PR #722, so this mapping will be prone to error and require maintenance as the functions evolves in the future. That seems like more work than just forcing users to update their code when they see the error message which won't be that hard, especially for the users of {nwfscDiags} who don't even need to know that there's been a change.

**Comment by kellijohnson-NOAA** [comment]
1. @iantaylor-NOAA I don't see why you need to create a new file. You can have both the new and the old function in a single file and then the history will be cleaner. Inside the original file, first rename the old function to the new function name, then add additional code at the end of the file that uses deprecate and the old function name, then you can change the name of the file with git mv to match the new function name.
2. do whatever is easiest for you to maintain and provide example code for users / good documentation ... I don't thinkt hat you need to call the new function from the old function.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, your 1-file solution for new and old functions is excellent. I will do that.

**Comment by kellijohnson-NOAA** [comment]
And, if you want to document the functions in one file, just use
```
@rdName newfunctionname
```
or if you do not want documentation for the old function name you can use
```
@noRd
```

**Comment by iantaylor-NOAA** [comment]
Thanks to Laura Lee, I discovered a mistake in the deprecated function names where folks running existing code got a message like `Error in SS_profile(dir = "blah") : unused argument (dir = "blah")` instead of the more useful error message:
```
Error: `SS_profile()` was deprecated in r4ss 4.6.1 and is now defunct.
Please use `profile()` instead.
```
That's been corrected in commit 4d4aa6f (by adding a `...` argument to all the old function names). Hopefully that's enough and now closing this issue (which I forgot to do before). We can reopen if further problems are identified.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I see that `base::jitter()` exists and when loading {r4ss} it overrides this base function. I do not think it is a huge deal, just wanted to make sure that you knew.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, yes, I've seen that. I have used `base::jitter()` only rarely (and thus forgot it existed). I'm hoping other users also don't use it heavily such that using `base::jitter()` won't be a burden. It's probably worth adding a note in the documentation and/or useful exit message when you provide a vector of numeric values rather than inputs like dir and Njitter.

The renamed functions in {r4ss} also overrise `stats::profile()` which seems to also be for profiling parameters in fitted models. I wasn't aware that it existed and am again hoping it's not a big deal.
