### ISSUE TITLE
setwd("..") in SS_doRetro

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#724]
https://github.com/r4ss/r4ss/blob/c7ecd71b3ecc744c5a133738531eeb8e9ec1b040/R/SS_doRetro.R#L206

Can someone explain to me what this line is doing? When I run the code it appears to be setting the working directory to the inner folder where the first retrospective run was done (e.g., the newdir set on line 90). So when the code moves on to iyr > 1 when we get to lines:

https://github.com/r4ss/r4ss/blob/c7ecd71b3ecc744c5a133738531eeb8e9ec1b040/R/SS_doRetro.R#L137-L139

it is trying to create a folder deep in the newdir which does not work.  Am I missing something here?

**Comment by kellijohnson-NOAA** [comment]
I think that `newdir` will be messed up if `masterdir` is not a full path. If we added a `normalizePath()` call in there and removed the `setwd("..")` I think that the code would be more robust.

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa, I'm not sure what it was doing before, but that line has been removed in draft Pull Request #722, where `SS_doRetro()` no longer contains dir.create() or setwd() and those tasks are farmed out to `copy_SS_inputs()` and `run()`, respectively.

**Comment by iantaylor-NOAA** [comment]
Pull Request #722 has been merged so the offending line of code is gone.
@chantelwetzel-noaa, if you have a chance to test the revised `SS_doRetro()` and have any problems, please open a new issue.
