### ISSUE TITLE
`SS_output()` when no hessian leads to a warning

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#734]
https://github.com/r4ss/r4ss/blob/37b89fe4046fd271fa76548779e36b22276a0910/R/SS_output.R#L1894-L1898

when the Report.sso looks like
```
Convergence_Level: 3.13908e-14 is_final_gradient
Hessian: Not requested.
```
Leads to 
```
NA
Warning message:
NAs introduced by coercion
```

**Comment by iantaylor-NOAA** [comment]
Oops, I tested the recent change to this section on older models that didn't include that output, but forgot to test on models that used "-nohess". I'll get this fixed shortly. The goal was to get rid of the warnings about missing ".cor" file, not to generate new warnings.

**Comment by iantaylor-NOAA** [comment]
In PR #739 the read of the "Hessian: Not requested." output has been added in the code below and now automatically turns `covar` to FALSE so it won't try to read that file or give a message about "covar file not found", which is an additional benefit.
https://github.com/r4ss/r4ss/blob/e3d75cd1513f48010ea6285393fd28292dbeca48/R/SS_output.R#L1107-L1115
