### ISSUE TITLE
Space in exe path and `shQuote()` lead to invalid result from `check_exe()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#747]
https://github.com/r4ss/r4ss/blob/2e4ded428a1d42f9390d247101582c5045d9f5ad/R/check_exe.R#L59

I recently changed computers and there is a space in the file path to my executable, e.g.,
```
C:/Program Files/R/R-devel/library/ss3sim/bin/Windows64/ss3.exe
```
If this value is passed to `check_exe(exe = "C:/Program Files/R/R-devel/library/ss3sim/bin/Windows64/ss3.exe")` then everything is fine but if the results of `shQuote("C:/Program Files/R/R-devel/library/ss3sim/bin/Windows64/ss3.exe")` are passed to `check_exe()` then it leads to nonsensical results because the terminal character of the string is not `.exe` instead it looks like this
```
"\"C:/Program Files/R/R-devel/library/ss3sim/bin/Windows64/ss3.exe\""
```
which is a valid executable path. I just checked 😉.

The desired fix here would be to create a smarter regex that can search for the .exe extension and leave it if you are on a windows machine instead of removing it for all if present and then adding it back if it is windows.

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this @kellijohnson-NOAA. I made a low-tech fix to deal with the quotes in 0bf8670 (mixed in with some other changes I already had in the hopper). 

Unfortunately `run()` needs changes as well:
```
system2(shQuote("C:/SS/SSv3.30.20.00_Sept29/folder with spaces/ss_win.exe"))
Warning message:
In system2(shQuote("C:/SS/SSv3.30.20.00_Sept29/folder with spaces/ss_win.exe")) :
  '"\"C:/SS/SSv3.30.20.00_Sept29/folder' not found
```

Should we remove the quotes before passing to `system2()`, because the following does work?
```
system2("C:/SS/SSv3.30.20.00_Sept29/folder with spaces/ss_win.exe")
```

**Comment by kellijohnson-NOAA** [comment]
I mean if it works with spaces and I do not have to use `shQuote()` then I think we may be good to go and the error would just be on my end thinking that I needed to wrap it?

**Comment by iantaylor-NOAA** [comment]
Apparently `system2()` doesn't use the command line processor so somehow handles the spaces fine: https://stackoverflow.com/questions/67912413/in-r-invoke-external-program-in-path-with-spaces-with-command-line-parameters. 

So I went ahead and removed the code in `check_exe()` for handling escaped quotes added by `shQuotes()`. If something isn't working with the current setup an not using `shQuotes()`, we can add that stuff back and then remove them in `run()`

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA and sorry I didn't investigate this further prior to making an issue. {ss3sim} is now working when the file path has a space in it given the removal of `shQuote()`.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, don't worry this was a useful learning experience for me.
I forgot to actually push the change to remove the treatment of the `shQuotes()` until now (in 
8d46c0e). I think the removed code would have been ignored if you are no longer using `shQuotes()` in {ss3sim}, so this shouldn't impact anything, but if you have any further issue, reopen this issue.
