### ISSUE TITLE
Remove RCurl from dependencies

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#75]
RCurl installation issues have been noted by @allanhicks and @colemonnahan but it just occurred to me that RCurl may have only been required for a older version of update_r4ss_files which has now does nothing but point to devtools installation method: https://github.com/r4ss/r4ss/blob/master/R/update_r4ss_files.R

Anybody know of a place that RCurl is still used or can we remove the dependency and make installation of r4ss and ss3sim easier?

**Comment by colemonnahan** [comment]
I'm not aware of it being used in ss3sim and think it's a good idea to remove if possible. @seananderson do you know about this?

**Comment by kellijohnson** [comment]
@colemonnahan did not we determine that it was a dependency of devtools
that is not automatically loaded? Even so it does not make sense to have it
in ss3sim or r4ss if you should be loading/installing devtools prior to
ss3sim and r4ss. It would be nice if it was automatically installed with
devtools though. Or at least I think that is what needs to happen.

On Wed, Oct 21, 2015 at 10:40 PM, Cole Monnahan <notifications@github.com>
wrote:

> I'm not aware of it being used in ss3sim and think it's a good idea to
> remove if possible. @seananderson <https://github.com/seananderson> do
> you know about this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r4ss/r4ss/issues/75#issuecomment-150112968>.
>



-- 
Kelli Faye Johnson
kellifayejohnson@gmail.com

**Comment by colemonnahan** [comment]
@kellijohnson I believe we did infer that, but I'm not 100% convinced it's not used in ss3sim otherwise. @seananderson obviously put it in there for a specific reason -- I'm wondering if we're overlooking something here.

**Comment by seananderson** [comment]
RCurl is not imported by ss3sim and as far as I can tell it no longer needs to be imported in r4ss. It's imported [here](https://github.com/r4ss/r4ss/blob/master/R/r4ss-package.R#L33) but `getURL` is no longer used anywhere when I grep for it. I didn't add it myself anywhere that I'm aware of.

**Comment by taylori** [comment]
Dependency removed. We can reopen this issue if it causes any problems.
