### ISSUE TITLE
[Bug]: error when 2nd "LIKELIHOOD" in Report.sso apears after line 200 in profile.r

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#753]
### Describe the bug

In lines 471-479 of profile.r, value of likelihood from Report.sso is read if  "read_like" is TRUE.
The core of codes are lines 474-475
```
        Rep <- readLines("Report.sso", n = 200)
        like <- read.table("Report.sso", skip = grep("LIKELIHOOD", Rep)[2] + 0, nrows = 11, header = TRUE, fill = TRUE)
```

### To Reproduce

As the above codes assumed the second "LIKELIHOOD" will show up line 200 or above. However 2nd "LIKELIHOOD" may appears after line 200. In some ``Report.sso``  e.g.
```
❯ grep -iIn "LIKELIHOOD" Report.sso
55:Y LIKELIHOOD report:2
210:LIKELIHOOD report:2 540679
```
This caused profile function to crash

### Expected behavior

It is expected that profile function can find 2nd "LIKELIHOOD" in Report.sso and can read value of likelihood

### Which OS are you seeing the problem on?

Linux

### Which versions of r4ss and SS3 are you seeing the problem on?

r4ss 1.46.1, ss3 3.30.20

### Additional Context

Simple solution would be to increase 200 in line 474 to e.g.300

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Hi @yukio-takeuchi,
I just increased the range to search from 200 to 400 in 2e1f854. We could also switch to using `SS_output()` within `profile()`, but that seems unnecessary as it would slow things down a bit.
Can you confirm that the fix works for your model and if so, close the issue?
-Ian

**Comment by yukio-takeuchi** [comment]
Thanks @iantaylor-NOAA for your quick reaction.

I made a quick test running profile. That did not produced the error.

I agree to close this issue.

In relation to this issue, I am inspired that the value of brows= 11 might be better to increase e.g. 16 if tagging data is included in the model. But I am not sure if number of components in the likelihoods can change depending on the use of tagging data.
I will check this tomorrow.

**Comment by iantaylor-NOAA** [comment]
@yukio-takeuchi, good catch.
I never look at the table of likelihoods returned by `profile()`, preferring to read the full model output using `SSgetoutput()` after all the profile models have run. However, it's more efficient to skip that extra step if you don't require more information so the table should be complete.

I've made the length of the LIKELIHOOD table dynamic in commit 3c60b0f, based on the observation that the final line of the LIKELIHOODS has remained "Crash_Pen" going back at least to SS3 version 3.24.

**Comment by yukio-takeuchi** [comment]
Thanks @iantaylor-NOAA 

This changes looks better as the function write_SS_summary in [SS_write.tpl](SS_write.tpl) has 9 unconditional likelihood components and 12 conditional ones conditional to use of corresponding components in the model.

I now fully agree with closing this issue.
