### ISSUE TITLE
selShapes host not working

### ISSUE THREAD

**Issue by allanhicks** [r4ss/r4ss#788]
Running selShapes() opens the website [https://connect.fisheries.noaa.gov/shiny-selex-ss3/](https://connect.fisheries.noaa.gov/shiny-selex-ss3/), but this website returns a 404 error. I see this comment (below) from @k-doering-NOAA that the shiny app is no longer in r4ss.  Is this shiny app available somewhere?

              Closing, as the shiny app has been around for a while now and is no longer housed within r4ss.

_Originally posted by @k-doering-NOAA in https://github.com/r4ss/r4ss/issues/48#issuecomment-1115215497_

**Comment by iantaylor-NOAA** [comment]
@ChristineStawitz-NOAA, I have a 2021 email from @k-doering-NOAA saying that it's thanks to you that this r4ss Shiny app was running the on the Rstudio connect server. Is this just an address change and/or is there somewhere else online that we can post this?

**Comment by ChristineStawitz-NOAA** [comment]
Is this the app? https://connect.fisheries.noaa.gov/ss3-helper/

**Comment by iantaylor-NOAA** [comment]
@ChristineStawitz-NOAA, yes, thank you! I forgot this existed, but thank you for setting it up and helping find it again.

@allanhicks, thanks for catching this and posting the issue. I just pushed a fix in 2809c25. Let me know if that doesn't work for you after you update r4ss.

**Comment by allanhicks** [comment]
Thank you @ChristineStawitz-NOAA  and @iantaylor-NOAA. That works perfectly now. And, an amazing response time!

**Comment by iantaylor-NOAA** [comment]
Sadly, the response time doesn't quite make up for all the other issues that have been languishing for a decade.
