### ISSUE TITLE
Add more functions to make tables

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#8]
Google Code Issue 56:
Among the tables that are standardized in US west coast assessment documents: Executive summary table b (SB, rec, depletion with 95% intervals). Table c with intervals. Table g with formatting and intervals.  Time series with Total, SB summary bio, recruits, etc.

**Comment by taylori** [comment]
Table-making ideas are outlined on the r4ss wiki at https://github.com/r4ss/r4ss/wiki/r4ss%20table%20making%20ideas
and also subject of issue #86.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA is this an issue that should stay open or should it be closed since it looks like has been/is being tackled in sa4ss and likely the workflows project that Sam is working on?

**Comment by iantaylor-NOAA** [comment]
As noted by @e-perl-NOAA, table-making is better suited to other packages.
