### ISSUE TITLE
[Bug]: tune_comps() does not work for dirichlet-multinomial without age data

### ISSUE THREAD

**Issue by okenk** [r4ss/r4ss#802]
### Describe the bug

If a model does not have age data and you are trying to use the `tune_comps()` function to set up the dirichlet-multinomial parameters, it errors out at line 160 because `dat[["age_info"]]` is empty.

### To Reproduce

1. Use SS3 model files [here](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/main/model/Sensitivity_Anal/5.4_SS_Model_Warnings/2_23.model.settlement_events/run), for example of working model without age data.
2. Run `tune_comps(dir = working_directory, option = 'DM')`

### Expected behavior

The SS3 input files should still get updated for D-M data weighting, even if there is no age data.

### Which OS are you seeing the problem on?

Windows

### Which versions of r4ss and SS3 are you seeing the problem on?

r4ss version 1.48.0 (just updated), SS3 version 3.30.21.00

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Thanks for posting this @okenk. I will work on it ASAP.

Other tasks for `tune_comps()` include stuff in #800 and #498, but might take a little longer so this issue shouldn't wait for them.

**Comment by iantaylor-NOAA** [comment]
@okenk, pull request #807 fixes this issue and worked for the model you linked in the original post.
Let me know if you or the folks in the class have any time to try the fix via 
`pak::pkg_install("r4ss/r4ss@tuning_issue_498")`
and provide feedback or if I should go ahead and merge the changes into the main r4ss branch.
