### ISSUE TITLE
Unable to install r4ss using pak::pkg_install("r4ss/r4ss")

### ISSUE THREAD

**Issue by allanhicks** [r4ss/r4ss#809]
I get the error shown below when attempting to install r4ss using 'pak'. This was as an administrator on a brand new install of R 4.3.0. I have had this issue with other versions. I installed ggplot2 and then tried this.

remotes::install_github("r4ss/r4ss")  did work to install r4ss, but I have seen some people have issues with this and pak worked for them.

I am wondering if offering the remotes option in the README would be beneficial for anyone that has this same issue.

> .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error: 
! Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
ℹ See `$stderr` for standard error.
---
Backtrace:
1. pak::pkg_install("r4ss/r4ss")
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::start_task(state, task)
 7. pkgdepends:::start_task_build(state, task)
 8. pkgdepends:::make_build_process(path, pkg, tmp_dir, lib, vignettes, needscompilation, …
 9. withr::with_libpaths(c(tmplib, lib), action = "prefix", pkgbuild_process$new(path, …
10. base::force(code)
11. pkgbuild_process$new(path, tmp_dir, binary = binary, vignettes = vignettes, …
12. local initialize(...)
13. pkgbuild:::rcb_init(self, private, super, path, dest_path, binary, vignettes, …
14. pkgbuild:::build_setup(path, dest_path, binary, vignettes, manual, clean_doc, …
15. pkgbuild:::build_setup_binary(path, dest_path, args, needs_compilation)
16. pkgbuild::check_build_tools(quiet = TRUE)
17. base::stop("Could not find tools necessary to compile a package\n", …
18. | base::.handleSimpleError(function (e) …
19. global h(simpleError(msg, call))

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this, @allanhicks. Someone else reported something like this which was resolved by installing the {pkgbuild} package. Maybe that should be listed as a dependency. When I get a chance I will do some experiments. 

For the time being, the easy solution is to update the README as you suggested. Here's the new text:

> ## Installation

> There is a CRAN version of r4ss but it is out of date 
(last updated in May 2022). Installing directly from github via either the 
{pak} package or {remotes} will get the most recent main branch which should 
always work with the latest version of Stock Synthesis (as well as many older 
versions).

```
# option 1: install via {pak}
install.packages("pak")
pak::pkg_install("r4ss/r4ss")

# option 2: install via {remotes}
install.packages("remotes")
remotes::install_github("r4ss/r4ss")
```

**Comment by allanhicks** [comment]
Fantastic! Thanks @iantaylor-NOAA
