### ISSUE TITLE
Line endings broken for Windows?

### ISSUE THREAD

**Issue by colemonnahan** [r4ss/r4ss#81]
@taylori and @seananderson 

I've been working with the `r4ss` repo for months now with no issues. When I went to pull today I had a tone of changed files (that I had nothing to do with). It looks like when I pulled changes down my git config was changing the line endings. Maybe something like this:

http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone

I tried recloning to the same effect, and it's happening on two of my computers (Win 8 and Win 10). It would be crazy for me to commit all of these. Is there a recent change to how line returns were dealt with? How should I proceed?

**Comment by taylori** [comment]
I'm facing the same issue looking at r4ss today for first time in a while.
Didn't one of you or was it @kellijohnson who said that there's a way to
have it ignore line break differences?

**Comment by amart** [comment]
There is some information on configuring your local git interactions w.r.t. line endings on page 390 of the Pro Git book:  https://git-scm.com/book/en/v2

**Comment by colemonnahan** [comment]
@amart I don't think fixing it on every users local machine is the right approach. I advocate reverting the repo back to the previous settings so not everyone has to alter their local git setup.

**Comment by taylori** [comment]
Surely this is related to the new .gitattributes file
that @seananderson added in his most recent commit
https://github.com/r4ss/r4ss/commit/5db1e764c86ff39459ee2d1044a5ba0e9a1393f3
which was intended to make line ending issues go away.

We might want to wait for @seananderson to guide us but since he's not a
Windows guy I'm not sure he'll be the right one to debug.

**Comment by colemonnahan** [comment]
@taylori I followed the instructions here: https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

To "normalize" the line endings. I think now it will work without any issues. Can you please test something on the `fix_crlf` branch, which is where I made these changes?

**Comment by taylori** [comment]
Thanks @colemonnahan.
I seem to be rusty on checking out a branch and testing. Could we just
trust that your fix is good and have you either merge to the trunk
yourself, or issue a pull request, or tell me how to initiate that pull
request.

**Comment by kellijohnson** [comment]
@seananderson and I were talking about this a few days ago because I was having problems as well. I can test it right now.

**Comment by kellijohnson** [comment]
@colemonnahan looks good, I was able to switch to the branch, open a file, make changes to a single file, and only that file came up when I used `git status`.

**Comment by colemonnahan** [comment]
Thanks @kellijohnson. I merged it in and closed the branch: https://github.com/r4ss/r4ss/commit/229d8b46d57360759097f727d4e96cccd2df2667. We should be good to go so closing this now.

**Comment by colemonnahan** [comment]
I'm reopening this issue because of some problems I'm running into and I need advice. The line endings are all fixed in the master branch, but now to rebase master into other branches (in my case halibut) causes a ton of conflicts because, for instance, a line ending could be replaced in master but deleted in the new branch. 

This is going to be an issue for all branches, so I'm wondering if there is a general fix to this that I should approach? 

@seananderson or @taylori .. any ideas?

**Comment by seananderson** [comment]
Maybe this approach, which should always pick the branch in a case of conflict? This should probably be checked carefully after or done on a file by file basis. 

```git
git checkout halibut
git merge -s ours master
```

**Comment by colemonnahan** [comment]
What if we roll back the line endings commits and rebase any branches that are actively being used? Then fix CFLR issue again and rebasing shouldn't have any conflicts.

**Comment by taylori** [comment]
I have no insights or preferences on this. I'm happy with anything you
think might work.

**Comment by colemonnahan** [comment]
This may just be an issue for me in the halibut branch. In that case I'm probably going to have hundreds (maybe thousands) of conflicts across a handful of files. 

It's not as simple as my line endings are wrong. I've deleted and changed lines with the old line endings, which are spread out throughout comments and code.  That's why I'm hesitant to try the 'ours' strategy for merging... I have no experience with it but can't easily imagine how it would resolve this.

@seananderson Any thoughts about this? 

@taylori Do you have a sense which branches are effectively dead? It looks like I'm the only one using "active" branches right now.

@kellijohnson @allanhicks What are your plans for the stale branches you've worked on in the last year?

If I understand git right (and I rarely do) I could just roll back the line ending commits, rebase my branches, and then fix the line endings in master, rebase my branches, and then do a pull request for mine. Does anyone have any objections to this?

**Comment by seananderson** [comment]
Git does know the difference between line ending changes and changes to 
text itself. How about this? http://stackoverflow.com/a/862920

**Comment by colemonnahan** [comment]
This is what happens with `git merge master -s recursive -Xignore-space-at-eol`:

````
error: addinfo_cache failed for path 'R/SSplotPars.R'
error: addinfo_cache failed for path 'R/SSplotData.R'
error: addinfo_cache failed for path 'R/SSplotComparisons.R'
Auto-merging man/SSplotData.Rd
Auto-merging man/SSplotComparisons.Rd
Auto-merging man/SSplotBiology.Rd
Auto-merging man/SS_plots.Rd
Auto-merging NAMESPACE
R/SSplotComparisons.R: unmerged (2fc404ef72a1f34da2e910c8a96ec181a9809d25)
R/SSplotComparisons.R: unmerged (06e83d17754de2ebec54e0cfe8f1636d3fce136b)
R/SSplotComparisons.R: unmerged (d3ae9c3d1d06d245c8d981c424dfb27ca2e0582a)
R/SSplotData.R: unmerged (8b9f840eed8ad3ec42913f2ad49d5e6a0428caa9)
R/SSplotData.R: unmerged (bb7f052bf794fa9284c9776d0688e5834653d96f)
R/SSplotData.R: unmerged (ed4a09b4ca664c95ca7c5824210e8add4de651ce)
R/SSplotPars.R: unmerged (6ef0fdf250eb45d08e0aa46e8f0fac03d162cd37)
R/SSplotPars.R: unmerged (4b8d46a9d2d3a2ce597730b51647a42d36958dab)
R/SSplotPars.R: unmerged (9b4abd9a4fab9180ddc9bf0570789a688fddfd1f)
fatal: git write-tree failed to write a tree
````

**Comment by colemonnahan** [comment]
It looks like `git merge master -s recursive -X renormalize` did the trick. Anyone trying to do pull requests on branches should try that out.

Thanks @seananderson!

**Comment by taylori** [comment]
Glad it worked out. None of the stale branches need to be worried about at
this point. If there's a way that they should be further cleaned up to
avoid confusion, let me know.

**Comment by allanhicks** [comment]
Thanks Cole,
An interesting thread that is way over my head. I think that my stale
branch would be useful to develop further (the shiny one). This is to
create a shiny app to investigate selectivity, which will hopefully replace
the tcl/tk one sometime. However, I haven't had time to work on it.  The
indices plot branch which I started (and forgot about) may have already
been done. I'll have to look into that.

Thanks for continuing this work,
Allan

**Comment by taylori** [comment]
Hi Allan,
Don't worry, there's still plenty of opportunity to pursue both of these ideas. Since relatively few files were modified in each case, it's probably best to just create a new branch and copy over the changes that matter. Presumably there's a fancy way to do that automatically but I'm not sure what it is.

For future reference, here are the internal links to the issues associated with the two branches you mention: 
Issue #48 is to convert the tcl/tk function to shiny
Issue #67 is to add the index comparison plots
