### ISSUE TITLE
copy_SS_inputs returns logical, can it be invisible?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#811]
I think the return statements in copy_SS_inputs should be invisible so if you don't want to save the output then nothing is printed to the screen. Happy to make a pull request but wanted to check if it was desirable first.

https://github.com/r4ss/r4ss/blob/41444594bdf21f1b364364fbe83cca925d9bb7e3/R/copy_SS_inputs.R#L205

**Comment by iantaylor-NOAA** [comment]
Good idea. Go ahead with PR and/or push the change to main if you want.
