### ISSUE TITLE
[Feature]: provide input with units of spawning output

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#838]
### Describe the feature request.

Stock Synthesis is ignorant of the units of spawning output (if different from biomass) because it depends on the units you choose for the fecundity parameters. In the case of petrale sole, we have chosen parameter values such that the resulting units are in trillions of eggs to avoid really long numbers in the figure axis labels and table.

I think it would be useful for the user to be able to provide inputs to the various functions that will add the units to the axis labels or table headers, but I'm not sure how best to do that.

My current thinking is that the best approach would be providing an additional argument to `SS_output()` so that the units are added to the list created by that function and automatically used (if not `NULL`) by the various functions that use the output, such as `SSplotTimeseries()`, `SSplotBiology()`, `SSplotSpawnrecruit()` and `SSexecutivesummary()`.

### Describe alternatives you have considered

Additional arguments to `SS_plots()` and `SSexecutivesummary()` and have the user add the units each time one of those functions is run. However, that seems like more work than adding the units in one place and would result in differences between plots created by `SS_plots()` vs the individual plotting functions.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA I think this would be relatively easy to do. I believe it would have to be specified in SS_plots as well as all of the different plotting functions that will use it. I could see an additional param of spawn_output_units = NULL. At least for the SSplotSpawnrecruit I see the labels specified here:
https://github.com/r4ss/r4ss/blob/80ba8213ccf17bfe205fbe9fcd56c55ef8b79aeb/R/SSplotSpawnrecruit.R#L59-L64
and that spawning output label used here:
https://github.com/r4ss/r4ss/blob/80ba8213ccf17bfe205fbe9fcd56c55ef8b79aeb/R/SSplotSpawnrecruit.R#L110-L113

I think that could be changed to something like:
```
if(!is.null(spawn_output_units){
xlab <- paste(labels[3], spawn_output_units, sep = " ")
} else {
xlab <- paste(labels[3]
}
```

or just a general:
```
if(!is.null(spawn_output_units){
labels[3] <- paste(labels[3], spawn_output_units, sep = " ")
}
```

or even simpler without having to specify a particular label closer to the beginning of each plotting function:
```
if(!is.null(spawn_output_units){
gsub("(.*?)Spawning output(.*?)", paste0("Spawning output (", spawn_output_units,")"), labels)
}
```

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA is there no way to figure out the scale from the fecundity parameters?
