### ISSUE TITLE
failed to load using pak

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [r4ss/r4ss#840]
### Describe the bug

> install.packages("pak")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/pak_0.5.1.zip'
Content type 'application/zip' length 11862567 bytes (11.3 MB)
downloaded 11.3 MB

package ‘pak’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Richard.Methot\AppData\Local\Temp\Rtmpeg8ZKS\downloaded_packages
> pak::pkg_install("r4ss/r4ss")
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Updated metadata database: 5.04 MB in 14 files.                          
✔ Updating metadata database ... done                                      
                                                                             
→ Will update 1 package.
→ Will download 1 package with unknown size.
+ r4ss 1.48.1 → 1.48.1 [bld][cmp][dl] (GitHub: 80ba821)
? Do you want to continue (Y/n) y
ℹ Getting 1 pkg with unknown size
✔ Got r4ss 1.48.1 (source) (7.96 MB)                    
✔ Downloaded 1 package (7.96 MB)in 3.7s                 
ℹ Packaging r4ss 1.48.1
✖ Failed to uncompress r4ss 1.48.1                              
Error:                                                          
! error in pak subprocess
Caused by error in `stop_task_package_uncompress(state, worker)`:
! Failed to uncompress 'r4ss' from 'C:\\Users\\RICHAR~1.MET\\AppData\\Local\\Temp\\RtmpmQPdSp\\filebe429f05dff/src/contrib/r4ss_1.48.1_80ba821.tar.gz-t'.
Type .Last.error to see the more details.
> .Last.error.trace
1. pak::pkg_install("r4ss/r4ss")
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)

### To Reproduce

see above

### Expected behavior

wanted to use r4ss

### Which versions of r4ss and SS3 are you seeing the problem on?

1.48.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA a temporary fix to allow you to work with r4ss is:
```
install.packages("devtools") # if needed
library(devtools)
install_github("r4ss/r4ss")
```

**Comment by Rick-Methot-NOAA** [comment]
My R just got updated to 4.3.1.
When I tried the "pak" approach, I did not have "remotes" enabled, so perhaps that was issue.
I was successful after going back to my accustomed approach, which is what Elizabeth wrote out.

**Comment by iantaylor-NOAA** [comment]
Got it. Good to hear everything is up to date.

I was hoping that pak would avoid some of the issues with the old approach related to dependent packages where remotes wanted to update everything but often couldn't because it said they were in use. So I often was having to restart R or manually delete dependencies from the R library folder. Hopefully this is a rare issue.

**Comment by Rick-Methot-NOAA** [comment]
Yep.  I went through all those steps when I went back to the dev_tools approach.
I'm determined to have much higher R proficiency by the time of the class.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA do you think we can close out this issue?

**Comment by iantaylor-NOAA** [comment]
Yes, it's frustrating that sometimes pak works better than remotes and sometimes worse, but since the install instructions list both options, I think we can close.

Thanks for going through all these old issues, @e-perl-NOAA.
