### ISSUE TITLE
Time series table for West Coast assessments

### ISSUE THREAD

**Issue by allanhicks** [r4ss/r4ss#86]
Create a table of various time-series quantities as in Table 21 of the Rougheye assessment: http://www.pcouncil.org/wp-content/uploads/Rougheye_and_Blackspotted_2013_Assessment.pdf

**Comment by CWetzel** [comment]
I have existing code to do this.  I can convert it into a function that could be included with r4ss.

**Comment by taylori** [comment]
Thank you Chantel for offering to contribute something.
Table-making ideas are outlined on the r4ss wiki at https://github.com/r4ss/r4ss/wiki/r4ss%20table%20making%20ideas
and also subject of issue #8.

**Comment by taylori** [comment]
Also note that Jim Hastie requests that time-series tables should include the first few forecast years.

**Comment by CWetzel** [comment]
The package now includes an SStimeseries function which will write the time-series table into a csv file.
