### ISSUE TITLE
[Feature]: SS3 minimal template set-up

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [r4ss/r4ss#864]
### Describe the feature request.

Creating this issue to keep a record of discussions had during the ICES Course.

During the course, we recognized that people would like some templates to help fill out essential SS3 inputs depending on the dimensions of their data. We discussed potentially adding a function in r4ss to have the users put in their dimensions/inputs (Start year, end year, number of fleets, number of areas, if they want to use wtatage, etc.) that would create a template of SS3 input files based on their starting inputs.

This could be an r4ss function or maybe even a shiny app.

Steps to do:

1. Review Jason Cope's data-limited shiny app to help us determine placeholders for all necessary values.
2. Create a list of the minimal inputs that we would need users to define
3. Determine how to best create a function or app to use those inputs to create templates (or even if r4ss is the best place to put this capability)

### Describe alternatives you have considered

- Excel helper sheets
- Creating a function but not having it in r4ss

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by Rick-Methot-NOAA** [comment]
Let's start by reviewing other tools, starting with Jason Cope's Data-Limited approach which must be able to provide placeholders for all necessary values.

**Comment by e-gugliotti-NOAA** [comment]
Decided to refer people to Jason's tool as it's provides a more user-accessible interface to enter in SS3 values rather than the input text files.
