### ISSUE TITLE
[Feature]: Add forecast detail to ss_write function

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [r4ss/r4ss#866]
### Describe the feature request.

Need to make sure that r4ss is updated after the following issues have been completed in regards to the forecast file in the stock-synthesis repo:
[Issue #493](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/493)
[Issue #490](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/490)
[Issue #487](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/487)

### Describe alternatives you have considered

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Resolved via Pull Request https://github.com/r4ss/r4ss/pull/873.
