### ISSUE TITLE
Can SSplotData make one plot with datasize=T

### ISSUE THREAD

**Issue by allanhicks** [r4ss/r4ss#87]
When SSplotData is called with datasize=T, it makes two plots: the original and the datasize plots.  For some applications (like knitr) it would be nice to create a single plot of the datasize one. This would be easy to add another parameter, but that would be redundant.  Instead I see two better solutions, but they could possibly break someone's code:

1) If datasize=T, then the original plot is not produced.

2) Remove the datasize argument and put in a subplot argument with c(1,2), where 1 is the original and 2 is the datasize  Then if subplot contains that number, make the plot.

Or, if you don't want to break anyone's code, but keep adding arguments:

3) add subplot to the argument list with c(1,2), or an argument called both perhaps. Then check for datasize and this new argument.

I implemented option 3, but feel free to revert if you don't like it.  Otherwise, this issue can be closed.

**Comment by colemonnahan** [comment]
@allanhicks I don't have a strong preference and will leave it up to you and @taylori. Again, I made this at the request of Ian S. for the halibut model specifically. Does the original plot have any advantages over the new version? We could just replace it outright.

**Comment by allanhicks** [comment]
The original plot may be desired if there is a huge difference in sample
sizes for a year and you just want to show where data are.

**Comment by taylori** [comment]
This issue seems to have been adequately sorted out for the application where @allanhicks needed it. In addition to folks perhaps having different preferences, the new version doesn't work for seasonal models (see issue #89). Until that enhancement is made, it's definitely worth keeping both plots. Therefore I'm closing this issue.
