### ISSUE TITLE
[Feature]: Change all instances of gender to sex

### ISSUE THREAD

**Issue by e-perl-NOAA** [r4ss/r4ss#879]
### Describe the feature request.

Change gender to sex in code following issue [#516](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/516) in the stock synthesis repository. 

Instances can be found searching though [this quick search of gender](https://github.com/search?q=repo%3Ar4ss%2Fr4ss%20gender&type=code).
### Describe alternatives you have considered

Not changing. Will not be in alignment with new release of ss3.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Thanks for posting this @e-gugliotti-NOAA. The hard part of this is described in issue https://github.com/r4ss/r4ss/issues/512, but that's not an excuse for not making progress. I will try to work on it this week.
