### ISSUE TITLE
error to produce data range plots in SS_plots

### ISSUE THREAD

**Issue by huihualee** [r4ss/r4ss#88]
There is error for data range plot in SS_plots function

Error in symbols(x = x, y = y, circles = sqrt(size.cex) * maxsize, bg = adjustcolor(fleetcol[fleets ==  : 
  x/y/parameter length mismatch

**Comment by allanhicks** [comment]
Can you send me (@allanhicks) your model, or put it on the Google Drive and I'll try to recreate your error?

**Comment by allanhicks** [comment]
This error is the result of catch occurring in multiple seasons for a single fleet. Thus, the flooring of year and the min(yr):max(yr) does not allow the season to be retained.  

However, can you have a single fleet with catch in multiple seasons in SS? Or do you have to define a fleet as fishing in one season, thus would have to define four separate fleet if there is one fishery over the entire year in a 4 season model?

**Comment by taylori** [comment]
Hi Hui-Hua,
Sorry, I've been on leave for a while and didn't have a chance to test some
of the recent changes. You definitely do not need to define separate fleets
in a seasonal model. I'll work on fixing this bug as soon as I can.
-Ian

**Comment by allanhicks** [comment]
Thanks Ian,
I don't think that it is a bug, I just think that the seasonal aspect is
not implemented. I could attempt some changes I was considering, but I'm
not sure how it would affect non-seasonal models. There is a bit more
thought needed that I don't have time for right now.
Allan

**Comment by taylori** [comment]
What's strange to me is that the offending bit of code you identified has
been in place for years and yet doesn't seem to have caused a problem for
models with catch in multiple seasons in the past. I'll look deeper later
this morning and come up with a minimal fix and then we can discuss
longer-term ideas when there's more time.

**Comment by taylori** [comment]
@huihualee please test recent commit, which simply turns off the data size plot and defaults to the old plot, to see if this makes things work for you. Then we can close the issue.  I've opened a new issue #89 noting that we could improve the function in the future to represent data size for seasonal models.

**Comment by huihualee** [comment]
It works now for bluefin tuna model! We have sardine model encountered the same issue. I will have them to test it! Thank you so much Allen and Ian!
