### ISSUE TITLE
[Bug]: jitter not fully working, test needs improving

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#885]
### Describe the bug

Changes in PR #870 caused some of the functionality of `jitter()` to stop working. The vector of total likelihoods is provided, but the output files are not being saved so it's not possible to run `SSsummarize()` to get more detail on the results. @okenk is working on a fix.
If you need some of the missing functionality of jitter today, you can install the version of r4ss from Oct 3, before the change, via 
`remotes::install_github("r4ss/r4ss@1d60153697d225470be078ddbc169068bfbbde01")` and will not be missing out on anything.

Meanwhile the testthat test for jitter, in https://github.com/r4ss/r4ss/blob/main/tests/testthat/test-runs.R#L119-L157, only looks for the vector of total likelihoods, not the model output, so we need to expand that to include the `SSsummarize()` step (which is included in the help page for `jitter()`) so it could detect an issue like this in the future.

- [ ] fix jitter() to get output files
- [ ] improve test so that it would have caught this bug

### To Reproduce

Run jitter(), look for output files from each jitter.

### Expected behavior

Renamed output files in the main directory.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by e-gugliotti-NOAA** [comment]
@okenk I added a test for the jitter output if you would like to test it out for me.

**Comment by iantaylor-NOAA** [comment]
Thanks for making this happen @e-gugliotti-NOAA. 
I think the test is running automatically (or maybe you triggered it manually).
