### ISSUE TITLE
[Feature]: Remove likelihood table from `SSexecutivesummary()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#887]
### Describe the feature request.

I propose removing the table of likelihoods produced by `SSexecutivesummary()` that was added in f3697c0 because, as @iantaylor-NOAA pointed out to me in an offline conversation, the likelihood values are meaningless unless they are being compared to another model fit to the same data (e.g., a sensitivity analysis).

### Describe alternatives you have considered

Leave the code as is or leave it and update the name column to include more complete text, e.g., Equil to Equilibrium. Please, if you use this table for anything, let us know by commenting below, sending an email, marking this issue with a thumbs down, or using any form of communication works for your situation.

### Additional context

The PFMC TOR does not require that we report the base model likelihoods by themselves, only when comparing the base model to another model. ![image](https://github.com/r4ss/r4ss/assets/4108564/bc835446-8b07-4f4f-bf80-f09494dbe306)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by e-perl-NOAA** [comment]
@kellijohnson-NOAA do you still think that the likelihood table should be removed from `SSexectivesummary()` or did some of the changes that you made in PR #889 satisfy some of the issues that you had with this table?

**Comment by iantaylor-NOAA** [comment]
I went ahead and removed the table from the main branch of r4ss in 63b18e9
The table was initially added by @chantelwetzel-noaa, who is welcome to reopen this issue and/or reverse the change if there's a compelling reason to keep the table.
