### ISSUE TITLE
[Feature]: automatically avoid profile error "At least one parameter needs to be estimated in phase 1"

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#891]
### Describe the feature request.

@maitepons ran into, and then solved, a common problem where a profile over log(R0) fixes the only parameter in phase 1, causing an error.

I think we could make `profile()` slightly smarter, so instead of this warning about the issue (which should be an error anyway, so you have to deal with it), the function just changes the phase of the first parameter in phase 2 (or whatever positive phase is lowest) to be in phase 1. A warning could be added to say which parameter was changed such that if the user wants to modify a different one they could do so manually.

https://github.com/r4ss/r4ss/blob/43f55e12558d533c6b6ca9872032bb0e05bd88b6/R/profile.R#L437-L446

If anyone has or concerns, feel free to chime in. If I don't hear objections, I'll just make the change when I get around to it.

### Describe alternatives you have considered

Keep the status-quo.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by kellijohnson-NOAA** [comment]
I don't have any problems with the proposed change but I am wondering if this can be dealt with within SS3 rather than in r4ss? It seems like it could be a problem for more than just profile models.

**Comment by Rick-Methot-NOAA** [comment]
It would require new code in SS3 tpl.  
Currently the closest code is that for depletion fleets.  There SS3 adds 1 to every parameter's phase such that only ln(R0) will be active in phase 1.

**Comment by iantaylor-NOAA** [comment]
I think that if you're running a single SS3 model, it's an easy fix to deal with this manually. 
It becomes more annoying in automated workflows like profiling in r4ss, and I think that's the easiest place to make the fix.

Perhaps the ideal solution would have been to have ADMB just skip straight to phase 2 if there are no phase 1 parameters, rather than producing the "no active parameters" error https://github.com/admb-project/admb/blob/dfd6a490ed8ce37b7ff956e2dcf5b71efdb3527f/src/nh99/con2fmin.cpp#L172, but the effort to change that is surely not worth the tiny benefit.

**Comment by okenk** [comment]
Sure, I can add this, too, I think it shouldn't be too hard.

I am almost ready for a pull request on it. I am just struggling with inconsistently getting warnings from `SS_parlines()` about introducing NAs by coercion, but they very consistently appear when I run the more automated R CMD check.

**Comment by iantaylor-NOAA** [comment]
@okenk, thank you.

As noted in https://github.com/r4ss/r4ss/blob/main/R/SS_parlines.R#L13-L15, the `SS_parlines()` function is not very sophisticated, so if there are rows that have 7 or 14 numerical elements but are not a parameter line, they could cause problems. Likewise, a parameter line that had no comment after it might also cause issues.

Finally, the NAs by coercion warning is temporarily suppressed within the function here: https://github.com/r4ss/r4ss/blob/4d22fec2b21c57a8794b9644d148177c2e3efc85/R/SS_parlines.R#L68 
(in order to check for non-numeric 8th or 15th elements), so if R CMD check somehow interferes with the call to `options()` that could also cause an issue.
