### ISSUE TITLE
[Bug]: Re-run simple small file with v.3.30.22 exe

### ISSUE THREAD

**Issue by e-perl-NOAA** [r4ss/r4ss#893]
### Describe the bug

Simple small file needs to be updated, maybe add an r-script

### To Reproduce

NA

### Expected behavior

Should be upated to v.3.30.22

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA I'm going to wait to do this until we release the v.3.30.22.1 bug fixes.
