### ISSUE TITLE
use blank lines to help parse output files

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#9]
Google Code Issue 60: revise SS_output to use "blank.lines.skip=FALSE" and use blanks to help parse the file. This will make SS_output more robust to changes in model output.

**Comment by taylori** [comment]
I did an experiment some time ago which found little improvement in speed of adjusting how the SS_output parsed Report files. At this point, a total rewrite doesn't seem a high priority so I'm closing this issue.

**Comment by iantaylor-NOAA** [comment]
I'm finally planning to implement the use of blank lines for parsing Report.sso in `SS_output()` starting in a branch sometime next week to clean up the code and support the planned option for more conditional output from SS.

**Comment by kellijohnson-NOAA** [comment]
Let me know if you need any help with this or if you want someone to listen to talk over the design of the code before you get started.

**Comment by iantaylor-NOAA** [comment]
Progress on this issue has been made on this issue in the `use_blank_lines` branch (commit history [here](https://github.com/r4ss/r4ss/commits/use_blank_lines)) available via
```
remotes::install_github('r4ss/r4ss@use_blank_lines')
```
This has been tested on 3.24 and 3.30.15 models and tests with ongoing development version of SS (eventually version 3.30.16) is ongoing.

Please feel free to test it out and report any problems on this issue.

**Comment by iantaylor-NOAA** [comment]
Revised `SS_output()` using blank lines for parsing is resolved in `development` branch by the changes in Pull Request #402. It can be tested via 
```
remotes::install_github('r4ss/r4ss@development')
```
Most of the changes are behind the scenes so the list created by the new `SS_output()` should match what the old one created. However, one minor change is that there should no longer be `NA` elements as it was cleaner to use `NULL`. Therefore any code that tested for presence/absence of elements in the list returned by `SS_output()` using `is.na()` should be changed to `is.null()`.
