### ISSUE TITLE
test and improve SS_varadjust

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#91]
Note says "Function has not been fully tested yet".
Gwladys Lambert has provided some useful feedback by email that I plan to look into as soon as I have time.

**Comment by GwladysLambert** [comment]
Here are the 2 issues I came across and how I think they can be addressed:

1) Problem with indexing of lines for copying back in new ctl file:
line 129 
writeLines(ctl_lines[1:(min(good_rows_absolute)+1)])
Should be:
writeLines(ctl_lines[1:(min(good_rows_absolute)**-1**)])

2) Need to add some code to replace the old var_adjust values by the new ones
As a suggestion, the code below (or similar) could be inserted line 95:
 #replace table
  if (!is.null(rownumber)){
    ctl[rownumber,1:nfleets] <- newrow
  }
  if (!is.null(newtable)){
    ctl[1:6,1:nfleets] <- newrow
  }

**Comment by taylori** [comment]
Closing this issue now that improved file was contributed by @GwladysLambert in this recent commit:
fa8717b4b91a93ed70758eb61ba7a3efa2674525
