### ISSUE TITLE
Error in 1:grep("fleet_name", tolower(names(fleetdefs))) :    argument of length 0

### ISSUE THREAD

**Issue by jimianelli** [r4ss/r4ss#938]
Updated r4ss and got this (from https://github.com/afsc-assessments/AI_PCOD)

m241<- SS_output(dir = "M24.1")
Getting header info from:
  M24.1/Report.sso
This function tested on SS versions 3.24 and 3.30.
  You are using 3.30.xx.yy which SHOULD work with this package.
Report file time:Mon May 20 09:47:04 2024
Reading full report file
Got all columns using ncols = 157
Got Report file
!warning: temporary files were written in this run:
                       TempFile                            Size                            <NA> 
"size of file gradfil1.tmp = 0" "size of file gradfil2.tmp = 0" "size of file varssave.tmp = 0" 
                           <NA> 
 "size of file cmpdiff.tmp = 0" 
warning.sso file is missing the string 'N warnings'
Finished reading files
Error in 1:grep("fleet_name", tolower(names(fleetdefs))) : 
  argument of length 0

**Comment by iantaylor-NOAA** [comment]
@jimianelli, I don't get an error when I read the output from M24.1 using SS3 version 3.30.22.1.
Can you provide more detail on what version of SS3 is being used or what changes it might include?

Also, maybe check that your r4ss worked as expected by confirming that `packageVersion("r4ss")` returns `1.49.2`.

**Comment by jimianelli** [comment]
I recompiled ss3 (r4ss worked fine for me and the version I had about a month ago...¯\_(ツ)_/¯ ) and that worked, sorry for the bother! (I was using 1.49.2)

**Comment by gavinfay** [comment]
I also just got this message when trying to run `SS_output()`.
Using the posted `ss3_osx_arm64` executable of latest SS3 version 3.30.22.1 which `r4ss` tells me is `3.30.22.beta`
`packageVersion("r4ss")` returns `1.50.0`
@iantaylor-NOAA any suggestions?

**Comment by gavinfay** [comment]
Never mind, I did something (not sure what), including restarting R, and it now works. Sunday brain I guess.
