### ISSUE TITLE
scaling of recruitment in SSplotComparisons()

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#972]
Hey Ian,

I have updated r4ss and I am able to run the SSplotComparisons() function. There is one issue I have noticed and it has to do with the Age-0 recruitment plot. The plot shows recruitment for the model with fixed weight-at-age (Base-3, in first attached figure) is significantly higher than the other models (millions version thousands). 
![compare9_recruits](https://github.com/user-attachments/assets/01924789-e73c-47f8-9e94-f83679731c10)

However, when I look at the r4ss age-0 recruitment plot for just the Base-3 model the recruitment scale is in the thousand (second attached figure). I believe there is a scaling error in SSplotComparisons() function. 

![ts11_Age-0_recruits_(1000s)](https://github.com/user-attachments/assets/9daa0589-ff44-4b0f-9ef5-9a1ad1782c62)

_Originally posted by @Lee-Cronin-Fine-NOAA in https://github.com/r4ss/r4ss/issues/969#issuecomment-2405728276_

**Comment by iantaylor-NOAA** [comment]
@Lee-Cronin-Fine-NOAA,
thanks for reporting this additional problem, I've moved it to a separate issue.

The scale for Base-3 appears the same in both plots (where 600 million = 6e+05 in thousands in the second plot). The time series plots from SS_plots() just show the units reported by SS3 whereas the SSplotComparisons() applies a rescaling to avoid having to use scientific notation in the axis labels. But the differences in scale between the models is clearly an issue.

The scaling should be equal for all the models in SSplotComparisons(), so you should look at the `$recruits` dataframe in the list returned by SSsummarize() to see if the values match the derived quantities from the individual model. That is, `model$derived_quants["Recr_2020", "Value"]` should match the value associated with that model in the `summary$recruits |> dplyr::filter(Label == "Recr_2020")`.

If the summary matches the individual model output, then I would look for big differences in R0 or M estimates or some other key difference among the models.

**Comment by Lee-Cronin-Fine-NOAA** [comment]
Hey Ian,

I have solved the problem. It had to do with the weight units. The model using watage.ss had the weight at age in kg and the other models has them in grams. So there is nothing you need to do on your end.

Thanks for the help,

Lee

**Comment by iantaylor-NOAA** [comment]
@Lee-Cronin-Fine-NOAA, great you sorted it out!
