### ISSUE TITLE
yield curve plot no longer depends on forecast file

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#99]
For recent versions of SS, SSplotYield should be modified to play through even when forecast = FALSE

**Comment by CWetzel** [comment]
FYI: In the upcoming version of SS (v3.30) I believe at least one forecast year will be required.  We should do some testing with the new model to ensure that this is still the case and how that may impact the need for forecast = FALSE option in the code.

**Comment by taylori** [comment]
Yield curve is only plot that wasn't working in recent test of r4ss applied to 3.30. Looks like it's an issue with format of "SPR/YPR_Profile" which may be an SS problem not specific to r4ss.

**Comment by taylori** [comment]
Yield curve no longer depends on forecast=TRUE as of commit 49862c8. 

Only missing information if forecast=FALSE is thresholds for biomass targets.

In SS 3.30, as @CWetzel pointed out, there is always a minimum 1-year forecast, so the user should never have to use forecast=FALSE. The option may still be useful for cases where the forecast-report.sso file is not present (e.g. someone just shared their report file).
